# IMPORTS

In [71]:
import numpy as np
import pandas as pd
from pathlib import Path
from pprint import pprint
import re

In [72]:
pd.set_option('display.max_columns', None)  # Show all columns
pd.set_option('display.width', 1000)

# DATA

In [73]:
df = pd.read_parquet(Path().cwd() / "model_store" / "global_dataset.parquet")

In [74]:
df.head()

   Capacity_Moment  Capacity_Shear  Capacity_Axial    g  tws   Bp  tp   e     d     p1     p2     p3     p4     p5   p6   p7   p8  p9  p10  p11  p12  ts  tbs  tst  Hole    BEAM  COLUMN DrawingCode  Bolt SlipCritical grado_acero clase_tornillo                                   standard BEAM_type  BEAM_d_mm COLUMN_type  COLUMN_d_mm  fy_acero_mpa  fu_acero_mpa  fy_tornillo_mpa  fu_tornillo_mpa  fv_tornillo_mpa  n_cantonera  n_alma  Unicode         Lh tornillo_1    tornillo_2     tornillo_3         tornillo_4          tornillo_5     tornillo_6         tornillo_7         tornillo_8         tornillo_9         tornillo_10 tornillo_11           p1_transition                p2_transition                     p3_transition                          p4_transition                 p5_transition                     p6_transition                         p7_transition                         p8_transition                          p9_transition                p10_transition
0        298.57275          0.0000          0.0000  140    0  320  30  50  60.0  145.0  130.0  145.0    0.0    0.0    0    0    0   0    0    0    0  20    0    0    33  HEB300  HEB700         MLE    30           NO      S355JR           10.9  EN 1993-1-8 - SP RK EN 1993-1-8:2005/2011        HE        300          HE          700           355           490              900             1000              500            0       2  MLE2364    0.00000   superior  viga primero  viga inferior           inferior            no_usado       no_usado           no_usado           no_usado           no_usado            no_usado    no_usado  superior__viga primero  viga primero__viga inferior           viga inferior__inferior                                 UNUSED                        UNUSED                            UNUSED                                UNUSED                                UNUSED                                 UNUSED                        UNUSED
1       1348.03440       1065.5325        832.2975  155    0  300  30  50  65.0  155.0   85.0  140.0  140.0  140.0  160  135  135  85  200    0    0  15   15   15    33  HEA700  HEB700         MHE    30          YES      S355JR          A325M                             AISC-360-05/10        HE        690          HE          700           355           490              660              830              372            4       5  MHE0176  557.72036   superior  viga primero   viga central       viga central        viga central  viga inferior  cantonera primero  cantonera central  cantonera central  cantonera inferior    inferior  superior__viga primero   viga primero__viga central        viga central__viga central             viga central__viga central   viga central__viga inferior  viga inferior__cantonera primero  cantonera primero__cantonera central  cantonera central__cantonera central  cantonera central__cantonera inferior  cantonera inferior__inferior
2        219.78000          0.0000          0.0000  105    0  240  25  40  40.0   90.0  110.0  150.0  110.0    0.0    0    0    0   0    0    0    0  12   10    0    22  HEA220  HEB500         MLE    20           NO      S355JR           10.9                             AISC-360-05/10        HE        210          HE          500           355           490              900             1000              500            1       2  MOE6213  170.00000   superior  viga primero  viga inferior  cantonera central            inferior       no_usado           no_usado           no_usado           no_usado            no_usado    no_usado  superior__viga primero  viga primero__viga inferior  viga inferior__cantonera central            cantonera central__inferior                        UNUSED                            UNUSED                                UNUSED                                UNUSED                                 UNUSED                        UNUSED
3        591.07500          0.0000          0.0000  140    0  320  25  50  50.0  130.0  130.0  195.0  110.0  130.0    0    0    0   0    0    0    0  15   15    0    30  HEA340  HEB340         MHE    27           NO      S355JR           10.9  EN 1993-1-8 - SP RK EN 1993-1-8:2005/2011        HE        330          HE          340           355           490              900             1000              500            2       2  MHE2248  265.00000   superior  viga primero  viga inferior  cantonera primero  cantonera inferior       inferior           no_usado           no_usado           no_usado            no_usado    no_usado  superior__viga primero  viga primero__viga inferior  viga inferior__cantonera primero  cantonera primero__cantonera inferior  cantonera inferior__inferior                            UNUSED                                UNUSED                                UNUSED                                 UNUSED                        UNUSED
4         54.82000         97.1300          0.0000   90    0  220  15  40  39.0   85.0   60.0   85.0    0.0    0.0    0    0    0   0    0    0    0  10   10    0    22  HEA160  HEA320         MLE    20           NO      S355JR           10.9                             AISC-360-05/10        HE        152          HE          310           355           490              900             1000              500            0       2  MLE6001    0.00000   superior  viga primero  viga inferior           inferior            no_usado       no_usado           no_usado           no_usado           no_usado            no_usado    no_usado  superior__viga primero  viga primero__viga inferior           viga inferior__inferior                                 UNUSED                        UNUSED                            UNUSED                                UNUSED                                UNUSED                                 UNUSED                        UNUSED

In [75]:
pprint(df.columns)

Index(['Capacity_Moment', 'Capacity_Shear', 'Capacity_Axial', 'g', 'tws', 'Bp', 'tp', 'e', 'd', 'p1', 'p2', 'p3', 'p4', 'p5', 'p6', 'p7', 'p8', 'p9', 'p10', 'p11', 'p12', 'ts', 'tbs', 'tst', 'Hole', 'BEAM', 'COLUMN', 'DrawingCode', 'Bolt', 'SlipCritical', 'grado_acero', 'clase_tornillo', 'standard', 'BEAM_type', 'BEAM_d_mm', 'COLUMN_type', 'COLUMN_d_mm', 'fy_acero_mpa', 'fu_acero_mpa', 'fy_tornillo_mpa', 'fu_tornillo_mpa', 'fv_tornillo_mpa', 'n_cantonera', 'n_alma', 'Unicode', 'Lh', 'tornillo_1', 'tornillo_2', 'tornillo_3', 'tornillo_4', 'tornillo_5', 'tornillo_6', 'tornillo_7', 'tornillo_8', 'tornillo_9', 'tornillo_10', 'tornillo_11', 'p1_transition', 'p2_transition', 'p3_transition', 'p4_transition', 'p5_transition', 'p6_transition', 'p7_transition', 'p8_transition', 'p9_transition', 'p10_transition'], dtype='str')

# ELIMINACIÓN DE DATOS SOBRANTES

In [76]:
df.drop(columns=["Lp", "Source", 'BEAM_bf_mm', 
                 'BEAM_tw_mm', 'BEAM_tf_mm', 'BEAM_r1_mm', 'BEAM_wely_mm', 'BEAM_w_kgm', 
                 'COLUMN_bf_mm', 'COLUMN_tw_mm', 'COLUMN_tf_mm', 'COLUMN_r1_mm', 
                 'COLUMN_wely_mm', 'COLUMN_w_kgm', 'p1_label', 'p2_label', 'p3_label', 
                 'p4_label', 'p5_label', 'p6_label', 'p7_label', 'p8_label', 'p9_label', 
                 'p10_label', 'p11_label', 'p12_label'
                ],
                inplace=True
        )

KeyError: "['Lp', 'Source', 'BEAM_bf_mm', 'BEAM_tw_mm', 'BEAM_tf_mm', 'BEAM_r1_mm', 'BEAM_wely_mm', 'BEAM_w_kgm', 'COLUMN_bf_mm', 'COLUMN_tw_mm', 'COLUMN_tf_mm', 'COLUMN_r1_mm', 'COLUMN_wely_mm', 'COLUMN_w_kgm', 'p1_label', 'p2_label', 'p3_label', 'p4_label', 'p5_label', 'p6_label', 'p7_label', 'p8_label', 'p9_label', 'p10_label', 'p11_label', 'p12_label'] not found in axis"

# AÑADIR COLUMNAS FALTANTES O AUXILIARES

In [ ]:
excel = pd.read_excel(Path().cwd() / "model_store" / "CONEXIONES_MOMENTO_ATORNILLADAS_CHAPA_FRONTAL.xlsx")
excel.head()

   Unicode    BEAM  COLUMN  Capacity_Moment_Percentage  Capacity_Moment  Capacity_Shear_Percentage  Capacity_Shear  Capacity_Axial_Percentage  Capacity_Axial  Pr_Porcen DrawingCode    g  tws  Lws  Bws   Bp   Lp  tp     Lh   e     d  pfo    p1     p2    p3        p4        p5  p6  p7  p8  p9  p10  p11  p12  ts  tbs  tst   thw   thf  w1  w2 w3 w4 w5 w6 Bolt  Hole SlipCritical      Normativas AceroEstructural ElectrodoSoldadura EstandarTornillos  Ordinary_Moment_Frames Calculation_Tool    Source Designation  rib_thk  Representation_Angle  BoltConnectionTypeSelection National_Annex   p0  tso  Lst  SpecialMomentFrames MzEd_PanelZone Vgra Havg  Yieldmethod Acero_Estructural_Perfil
0  JBE6000  IPE300  HEA260                       121.0           242.94                          0             0.0                          0             0.0         50         MOE  110    0    0    0  190  705  20  245.0  40  40.0  NaN  90.7  198.6  90.7  140.6447  104.3553   0   0   0   0    0    0    0  12   10    0  10.0  10.0   0   6  0  0  6  6  M20    22           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19        0                     0                            0              -  0.0  0.0  0.0                  0.0              -    -    -          1.0                   S355JR
1  JBE6001  HEA180  HEA300                       121.0           125.60                          0             0.0                          0             0.0         50         MOE  110    0    0    0  200  466  20  135.0  35  40.0  NaN  89.5   45.0  50.0   45.0000  155.0000   0   0   0   0    0    0    0  10   10    0  10.0  10.0   0   5  0  0  6  6  M16    18           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19        0                     0                            0              -  0.0  0.0  0.0                  0.0            NaN  NaN  NaN          NaN                      NaN
2  JBE6002  IPE300  HEA320                       121.0           242.94                          0             0.0                          0             0.0         50         MOE  110    0    0    0  190  705  20  245.0  40  40.0  NaN  90.7  198.6  90.7  140.6447  104.3553   0   0   0   0    0    0    0  12   10    0  10.0  10.0   0   6  0  0  6  6  M20    22           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19        0                     0                            0              -  0.0  0.0  0.0                  0.0            NaN  NaN  NaN          NaN                      NaN
3  JBE6003  HEA200  HEA280                       121.0           166.04                          0             0.0                          0             0.0         50         MOE  110    0    0    0  220  565  20  215.0  35  40.0  NaN  90.0   90.0  90.0  111.4530  103.5470   0   0   0   0    0    0    0  10   10    0  10.0  10.0   0   5  0  0  6  6  M16    18           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19        0                     0                            0              -  0.0  0.0  0.0                  0.0            NaN  NaN  NaN          NaN                      NaN
4  JBE6004  HEA240  HEA300                       121.0           287.86                          0             0.0                          0             0.0         50         MOE  120    0    0    0  240  600  25  210.0  40  40.0  NaN  92.0  126.0  92.0  104.1436  105.8564   0   0   0   0    0    0    0  12   10    0  10.0  10.0   0   6  0  0  7  7  M20    22           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19        0                     0                            0              -  0.0  0.0  0.0                  0.0            NaN  NaN  NaN          NaN                      NaN

In [ ]:
excel_join = excel[["Unicode", "BEAM", "COLUMN", "Capacity_Moment", "Capacity_Shear", 
                    "Capacity_Axial", "DrawingCode", "g", "e", "d", "p1", "p2", "p3", 
                    "p4", "p5", "p6", "p7", "p8", "p9", "p10", "p11", "p12", "Lh"]]

In [ ]:
df = df.merge(
    excel_join,
    on=["BEAM", "COLUMN", "Capacity_Moment", "Capacity_Shear", 
                    "Capacity_Axial", "DrawingCode", "g", "e", "d", "p1", "p2", "p3", 
                    "p4", "p5", "p6", "p7", "p8", "p9", "p10", "p11", "p12"],
    how="inner",
)

df.head()

   Capacity_Moment  Capacity_Shear  Capacity_Axial    g  tws   Bp  tp   e     d     p1     p2     p3     p4     p5   p6   p7   p8  p9  p10  p11  p12  ts  tbs  tst  Hole    BEAM  COLUMN DrawingCode  Bolt SlipCritical grado_acero clase_tornillo                                   standard BEAM_type  BEAM_d_mm COLUMN_type  COLUMN_d_mm  fy_acero_mpa  fu_acero_mpa  fy_tornillo_mpa  fu_tornillo_mpa  fv_tornillo_mpa  n_cantonera  n_alma  Unicode         Lh
0        298.57275          0.0000          0.0000  140    0  320  30  50  60.0  145.0  130.0  145.0    0.0    0.0    0    0    0   0    0    0    0  20    0    0    33  HEB300  HEB700         MLE    30           NO      S355JR           10.9  EN 1993-1-8 - SP RK EN 1993-1-8:2005/2011        HE        300          HE          700           355           490              900             1000              500            0       2  MLE2364    0.00000
1       1348.03440       1065.5325        832.2975  155    0  300  30  50  65.0  155.0   85.0  140.0  140.0  140.0  160  135  135  85  200    0    0  15   15   15    33  HEA700  HEB700         MHE    30          YES      S355JR          A325M                             AISC-360-05/10        HE        690          HE          700           355           490              660              830              372            4       5  MHE0176  557.72036
2        219.78000          0.0000          0.0000  105    0  240  25  40  40.0   90.0  110.0  150.0  110.0    0.0    0    0    0   0    0    0    0  12   10    0    22  HEA220  HEB500         MLE    20           NO      S355JR           10.9                             AISC-360-05/10        HE        210          HE          500           355           490              900             1000              500            1       2  MOE6213  170.00000
3        591.07500          0.0000          0.0000  140    0  320  25  50  50.0  130.0  130.0  195.0  110.0  130.0    0    0    0   0    0    0    0  15   15    0    30  HEA340  HEB340         MHE    27           NO      S355JR           10.9  EN 1993-1-8 - SP RK EN 1993-1-8:2005/2011        HE        330          HE          340           355           490              900             1000              500            2       2  MHE2248  265.00000
4         54.82000         97.1300          0.0000   90    0  220  15  40  39.0   85.0   60.0   85.0    0.0    0.0    0    0    0   0    0    0    0  10   10    0    22  HEA160  HEA320         MLE    20           NO      S355JR           10.9                             AISC-360-05/10        HE        152          HE          310           355           490              900             1000              500            0       2  MLE6001    0.00000

In [ ]:
import pandas as pd


def etiquetas_zona(nombre_zona, cantidad):
    """
    Devuelve las etiquetas de los tornillos interiores de una zona,
    ordenados de arriba hacia abajo.
    """
    cantidad = int(cantidad)

    if cantidad <= 0:
        return []

    if cantidad == 1:
        return [f"{nombre_zona} central"]

    if cantidad == 2:
        return [
            f"{nombre_zona} primero",
            f"{nombre_zona} inferior"
        ]

    return (
        [f"{nombre_zona} primero"]
        + [f"{nombre_zona} central"] * (cantidad - 2)
        + [f"{nombre_zona} inferior"]
    )


def clasificar_fila(fila):
    n_cantonera = int(fila["n_cantonera"])
    n_alma = int(fila["n_alma"])

    clasificaciones = ["superior"]

    clasificaciones += etiquetas_zona(
        nombre_zona="viga",
        cantidad=n_alma
    )

    clasificaciones += etiquetas_zona(
        nombre_zona="cantonera",
        cantidad=n_cantonera
    )

    clasificaciones.append("inferior")

    return pd.Series(
        clasificaciones,
        index=[
            f"tornillo_{i}"
            for i in range(1, len(clasificaciones) + 1)
        ]
    )

In [ ]:
# Generar las columnas de clasificación
clasificacion_tornillos = df.apply(
    clasificar_fila,
    axis=1
)

# Ordenar tornillo_1, tornillo_2, ..., tornillo_10...
columnas_tornillos = sorted(
    clasificacion_tornillos.columns,
    key=lambda columna: int(columna.split("_")[-1])
)

clasificacion_tornillos = clasificacion_tornillos[columnas_tornillos]

# Añadirlas al final del DataFrame original
df = pd.concat(
    [df, clasificacion_tornillos],
    axis=1
)

In [ ]:
df[[f"tornillo_{i}" for i in range(1, 12)]] = df[[f"tornillo_{i}" for i in range(1, 12)]].fillna("no_usado")

In [ ]:
df.head()

   Capacity_Moment  Capacity_Shear  Capacity_Axial    g  tws   Bp  tp   e     d     p1     p2     p3     p4     p5   p6   p7   p8  p9  p10  p11  p12  ts  tbs  tst  Hole    BEAM  COLUMN DrawingCode  Bolt SlipCritical grado_acero clase_tornillo                                   standard BEAM_type  BEAM_d_mm COLUMN_type  COLUMN_d_mm  fy_acero_mpa  fu_acero_mpa  fy_tornillo_mpa  fu_tornillo_mpa  fv_tornillo_mpa  n_cantonera  n_alma  Unicode         Lh tornillo_1    tornillo_2     tornillo_3         tornillo_4          tornillo_5     tornillo_6         tornillo_7         tornillo_8         tornillo_9         tornillo_10 tornillo_11
0        298.57275          0.0000          0.0000  140    0  320  30  50  60.0  145.0  130.0  145.0    0.0    0.0    0    0    0   0    0    0    0  20    0    0    33  HEB300  HEB700         MLE    30           NO      S355JR           10.9  EN 1993-1-8 - SP RK EN 1993-1-8:2005/2011        HE        300          HE          700           355           490              900             1000              500            0       2  MLE2364    0.00000   superior  viga primero  viga inferior           inferior            no_usado       no_usado           no_usado           no_usado           no_usado            no_usado    no_usado
1       1348.03440       1065.5325        832.2975  155    0  300  30  50  65.0  155.0   85.0  140.0  140.0  140.0  160  135  135  85  200    0    0  15   15   15    33  HEA700  HEB700         MHE    30          YES      S355JR          A325M                             AISC-360-05/10        HE        690          HE          700           355           490              660              830              372            4       5  MHE0176  557.72036   superior  viga primero   viga central       viga central        viga central  viga inferior  cantonera primero  cantonera central  cantonera central  cantonera inferior    inferior
2        219.78000          0.0000          0.0000  105    0  240  25  40  40.0   90.0  110.0  150.0  110.0    0.0    0    0    0   0    0    0    0  12   10    0    22  HEA220  HEB500         MLE    20           NO      S355JR           10.9                             AISC-360-05/10        HE        210          HE          500           355           490              900             1000              500            1       2  MOE6213  170.00000   superior  viga primero  viga inferior  cantonera central            inferior       no_usado           no_usado           no_usado           no_usado            no_usado    no_usado
3        591.07500          0.0000          0.0000  140    0  320  25  50  50.0  130.0  130.0  195.0  110.0  130.0    0    0    0   0    0    0    0  15   15    0    30  HEA340  HEB340         MHE    27           NO      S355JR           10.9  EN 1993-1-8 - SP RK EN 1993-1-8:2005/2011        HE        330          HE          340           355           490              900             1000              500            2       2  MHE2248  265.00000   superior  viga primero  viga inferior  cantonera primero  cantonera inferior       inferior           no_usado           no_usado           no_usado            no_usado    no_usado
4         54.82000         97.1300          0.0000   90    0  220  15  40  39.0   85.0   60.0   85.0    0.0    0.0    0    0    0   0    0    0    0  10   10    0    22  HEA160  HEA320         MLE    20           NO      S355JR           10.9                             AISC-360-05/10        HE        152          HE          310           355           490              900             1000              500            0       2  MLE6001    0.00000   superior  viga primero  viga inferior           inferior            no_usado       no_usado           no_usado           no_usado           no_usado            no_usado    no_usado

In [ ]:
def añadir_transiciones_p(df, max_p=10):
    """
    Para cada separación p_i crea una transición:

        p1_transition = tornillo_1 -> tornillo_2
        p2_transition = tornillo_2 -> tornillo_3
        ...

    Las separaciones inexistentes reciben UNUSED.
    """
    resultado = df.copy()

    for i in range(1, max_p + 1):
        col_p = f"p{i}"
        col_superior = f"tornillo_{i}"
        col_inferior = f"tornillo_{i + 1}"
        col_transition = f"p{i}_transition"

        existe_p = (
            pd.to_numeric(
                resultado[col_p],
                errors="coerce",
            )
            .fillna(0.0)
            .gt(0.0)
        )

        tornillo_superior = (
            resultado[col_superior]
            .fillna("no_usado")
            .astype(str)
        )

        tornillo_inferior = (
            resultado[col_inferior]
            .fillna("no_usado")
            .astype(str)
        )

        resultado[col_transition] = (
            tornillo_superior
            + "__"
            + tornillo_inferior
        )

        resultado.loc[
            ~existe_p,
            col_transition,
        ] = "UNUSED"

    return resultado

In [ ]:
df = añadir_transiciones_p(
    df,
    max_p=10
)

In [ ]:
df.head()

   Capacity_Moment  Capacity_Shear  Capacity_Axial    g  tws   Bp  tp   e     d     p1     p2     p3     p4     p5   p6   p7   p8  p9  p10  p11  p12  ts  tbs  tst  Hole    BEAM  COLUMN DrawingCode  Bolt SlipCritical grado_acero clase_tornillo                                   standard BEAM_type  BEAM_d_mm COLUMN_type  COLUMN_d_mm  fy_acero_mpa  fu_acero_mpa  fy_tornillo_mpa  fu_tornillo_mpa  fv_tornillo_mpa  n_cantonera  n_alma  Unicode         Lh tornillo_1    tornillo_2     tornillo_3         tornillo_4          tornillo_5     tornillo_6         tornillo_7         tornillo_8         tornillo_9         tornillo_10 tornillo_11           p1_transition                p2_transition                     p3_transition                          p4_transition                 p5_transition                     p6_transition                         p7_transition                         p8_transition                          p9_transition                p10_transition
0        298.57275          0.0000          0.0000  140    0  320  30  50  60.0  145.0  130.0  145.0    0.0    0.0    0    0    0   0    0    0    0  20    0    0    33  HEB300  HEB700         MLE    30           NO      S355JR           10.9  EN 1993-1-8 - SP RK EN 1993-1-8:2005/2011        HE        300          HE          700           355           490              900             1000              500            0       2  MLE2364    0.00000   superior  viga primero  viga inferior           inferior            no_usado       no_usado           no_usado           no_usado           no_usado            no_usado    no_usado  superior__viga primero  viga primero__viga inferior           viga inferior__inferior                                 UNUSED                        UNUSED                            UNUSED                                UNUSED                                UNUSED                                 UNUSED                        UNUSED
1       1348.03440       1065.5325        832.2975  155    0  300  30  50  65.0  155.0   85.0  140.0  140.0  140.0  160  135  135  85  200    0    0  15   15   15    33  HEA700  HEB700         MHE    30          YES      S355JR          A325M                             AISC-360-05/10        HE        690          HE          700           355           490              660              830              372            4       5  MHE0176  557.72036   superior  viga primero   viga central       viga central        viga central  viga inferior  cantonera primero  cantonera central  cantonera central  cantonera inferior    inferior  superior__viga primero   viga primero__viga central        viga central__viga central             viga central__viga central   viga central__viga inferior  viga inferior__cantonera primero  cantonera primero__cantonera central  cantonera central__cantonera central  cantonera central__cantonera inferior  cantonera inferior__inferior
2        219.78000          0.0000          0.0000  105    0  240  25  40  40.0   90.0  110.0  150.0  110.0    0.0    0    0    0   0    0    0    0  12   10    0    22  HEA220  HEB500         MLE    20           NO      S355JR           10.9                             AISC-360-05/10        HE        210          HE          500           355           490              900             1000              500            1       2  MOE6213  170.00000   superior  viga primero  viga inferior  cantonera central            inferior       no_usado           no_usado           no_usado           no_usado            no_usado    no_usado  superior__viga primero  viga primero__viga inferior  viga inferior__cantonera central            cantonera central__inferior                        UNUSED                            UNUSED                                UNUSED                                UNUSED                                 UNUSED                        UNUSED
3        591.07500          0.0000          0.0000  140    0  320  25  50  50.0  130.0  130.0  195.0  110.0  130.0    0    0    0   0    0    0    0  15   15    0    30  HEA340  HEB340         MHE    27           NO      S355JR           10.9  EN 1993-1-8 - SP RK EN 1993-1-8:2005/2011        HE        330          HE          340           355           490              900             1000              500            2       2  MHE2248  265.00000   superior  viga primero  viga inferior  cantonera primero  cantonera inferior       inferior           no_usado           no_usado           no_usado            no_usado    no_usado  superior__viga primero  viga primero__viga inferior  viga inferior__cantonera primero  cantonera primero__cantonera inferior  cantonera inferior__inferior                            UNUSED                                UNUSED                                UNUSED                                 UNUSED                        UNUSED
4         54.82000         97.1300          0.0000   90    0  220  15  40  39.0   85.0   60.0   85.0    0.0    0.0    0    0    0   0    0    0    0  10   10    0    22  HEA160  HEA320         MLE    20           NO      S355JR           10.9                             AISC-360-05/10        HE        152          HE          310           355           490              900             1000              500            0       2  MLE6001    0.00000   superior  viga primero  viga inferior           inferior            no_usado       no_usado           no_usado           no_usado           no_usado            no_usado    no_usado  superior__viga primero  viga primero__viga inferior           viga inferior__inferior                                 UNUSED                        UNUSED                            UNUSED                                UNUSED                                UNUSED                                 UNUSED                        UNUSED

In [ ]:
def validar_clasificacion_tornillos(df, max_p=10):
    resultados = []

    for indice, fila in df.iterrows():
        n_p_esperadas = (
            int(fila["n_alma"])
            + int(fila["n_cantonera"])
            + 1
        )

        p_activas = sum(
            pd.notna(fila[f"p{i}"])
            and float(fila[f"p{i}"]) > 0
            for i in range(1, max_p + 1)
        )

        transiciones_activas = sum(
            fila[f"p{i}_transition"] != "UNUSED"
            for i in range(1, max_p + 1)
        )

        resultados.append({
            "indice": indice,
            "p_esperadas": n_p_esperadas,
            "p_activas": p_activas,
            "transiciones_activas": transiciones_activas,
            "conteo_p_correcto": p_activas == n_p_esperadas,
            "conteo_transiciones_correcto": (
                transiciones_activas == n_p_esperadas
            ),
        })

    validacion = pd.DataFrame(resultados).set_index("indice")

    validacion["valido"] = (
        validacion["conteo_p_correcto"]
        & validacion["conteo_transiciones_correcto"]
    )

    return validacion

In [ ]:
validacion = validar_clasificacion_tornillos(df)

print(validacion["valido"].value_counts())
print(validacion.loc[~validacion["valido"]])

valido
True    3198
Name: count, dtype: int64
Empty DataFrame
Columns: [p_esperadas, p_activas, transiciones_activas, conteo_p_correcto, conteo_transiciones_correcto, valido]
Index: []

In [ ]:
def crear_dataset_separaciones(df, max_p=10):
    registros = []

    for i in range(1, max_p + 1):
        col_p = f"p{i}"
        col_transition = f"p{i}_transition"

        columnas = [
            col_p,
            col_transition,
            "Bolt",
            "BEAM_d_mm",
            "n_alma",
            "n_cantonera",
        ]

        parte = df[columnas].copy()

        parte = parte.rename(
            columns={
                col_p: "separacion_mm",
                col_transition: "transicion",
            }
        )

        parte["numero_p"] = i

        registros.append(parte)

    separaciones = pd.concat(
        registros,
        ignore_index=True,
    )

    separaciones["separacion_mm"] = pd.to_numeric(
        separaciones["separacion_mm"],
        errors="coerce",
    ).fillna(0.0)

    separaciones["Bolt"] = (
        separaciones["Bolt"]
        .astype(str)
        .str.replace("M", "", regex=False)
    )

    separaciones["Bolt"] = pd.to_numeric(
        separaciones["Bolt"],
        errors="coerce",
    )

    separaciones = separaciones.loc[
        separaciones["separacion_mm"].gt(0.0)
        & separaciones["transicion"].ne("UNUSED")
    ].reset_index(drop=True)

    return separaciones

In [ ]:
separaciones = crear_dataset_separaciones(df)

resumen_separaciones = (
    separaciones
    .groupby(
        ["transicion", "Bolt"],
        dropna=False,
    )["separacion_mm"]
    .agg(
        numero_casos="size",
        minimo="min",
        percentil_05=lambda x: x.quantile(0.05),
        percentil_10=lambda x: x.quantile(0.10),
        mediana="median",
        media="mean",
        maximo="max",
    )
    .reset_index()
    .sort_values(
        ["transicion", "Bolt"]
    )
)

In [ ]:
resumen_separaciones["grupo_suficiente"] = (
    resumen_separaciones["numero_casos"] >= 20
)

In [84]:
df[df["Lh"] < 1]

      Capacity_Moment  Capacity_Shear  Capacity_Axial    g  tws   Bp  tp   e     d     p1     p2     p3     p4   p5  p6  p7  p8  p9  p10  p11  p12  ts  tbs  tst  Hole    BEAM  COLUMN DrawingCode  Bolt SlipCritical grado_acero clase_tornillo                                   standard BEAM_type  BEAM_d_mm COLUMN_type  COLUMN_d_mm  fy_acero_mpa  fu_acero_mpa  fy_tornillo_mpa  fu_tornillo_mpa  fv_tornillo_mpa  n_cantonera  n_alma  Unicode   Lh tornillo_1    tornillo_2     tornillo_3     tornillo_4 tornillo_5 tornillo_6 tornillo_7 tornillo_8 tornillo_9 tornillo_10 tornillo_11           p1_transition                p2_transition                p3_transition            p4_transition p5_transition p6_transition p7_transition p8_transition p9_transition p10_transition
0          298.572750           0.000          0.0000  140    0  320  30  50  60.0  145.0  130.0  145.0    0.0  0.0   0   0   0   0    0    0    0  20    0    0    33  HEB300  HEB700         MLE    30           NO      S355JR           10.9  EN 1993-1-8 - SP RK EN 1993-1-8:2005/2011        HE        300          HE          700           355           490              900             1000              500            0       2  MLE2364  0.0   superior  viga primero  viga inferior       inferior   no_usado   no_usado   no_usado   no_usado   no_usado    no_usado    no_usado  superior__viga primero  viga primero__viga inferior      viga inferior__inferior                   UNUSED        UNUSED        UNUSED        UNUSED        UNUSED        UNUSED         UNUSED
4           54.820000          97.130          0.0000   90    0  220  15  40  39.0   85.0   60.0   85.0    0.0  0.0   0   0   0   0    0    0    0  10   10    0    22  HEA160  HEA320         MLE    20           NO      S355JR           10.9                             AISC-360-05/10        HE        152          HE          310           355           490              900             1000              500            0       2  MLE6001  0.0   superior  viga primero  viga inferior       inferior   no_usado   no_usado   no_usado   no_usado   no_usado    no_usado    no_usado  superior__viga primero  viga primero__viga inferior      viga inferior__inferior                   UNUSED        UNUSED        UNUSED        UNUSED        UNUSED        UNUSED         UNUSED
5          158.599800           0.000          0.0000  140    0  260  20  50  50.0  115.0  100.0  115.0    0.0  0.0   0   0   0   0    0    0    0  12    0    0    30  HEA240  HEB700         MLE    27           NO      S355JR           10.9  EN 1993-1-8 - SP RK EN 1993-1-8:2005/2011        HE        230          HE          700           355           490              900             1000              500            0       2  MLE2161  0.0   superior  viga primero  viga inferior       inferior   no_usado   no_usado   no_usado   no_usado   no_usado    no_usado    no_usado  superior__viga primero  viga primero__viga inferior      viga inferior__inferior                   UNUSED        UNUSED        UNUSED        UNUSED        UNUSED        UNUSED         UNUSED
8          309.787200         575.100        631.9710  150    0  300  30  50  60.0  145.0  230.0  145.0    0.0  0.0   0   0   0   0    0    0    0  10    0   10    33  HEB400  HEB400         MLE    30          YES      S355JR          A325M                             AISC-360-05/10        HE        400          HE          400           355           490              660              830              372            0       2  MLE0210  0.0   superior  viga primero  viga inferior       inferior   no_usado   no_usado   no_usado   no_usado   no_usado    no_usado    no_usado  superior__viga primero  viga primero__viga inferior      viga inferior__inferior                   UNUSED        UNUSED        UNUSED        UNUSED        UNUSED        UNUSED         UNUSED
9          105.415830         158.472        124.9245  120    0  180  20  40  50.0  110.0  120.0  110.0    0.0  0.0   0   0   0   0    0    0    0  10    0   10    27  IPE240  HEB240         MLE    24          YES      S355JR          A325M                             AISC-360-05/10       IPE        240          HE          240           355           490              660              830              372            0       2  MLE0287  0.0   superior  viga primero  viga inferior       inferior   no_usado   no_usado   no_usado   no_usado   no_usado    no_usado    no_usado  superior__viga primero  viga primero__viga inferior      viga inferior__inferior                   UNUSED        UNUSED        UNUSED        UNUSED        UNUSED        UNUSED         UNUSED
...               ...             ...             ...  ...  ...  ...  ..  ..   ...    ...    ...    ...    ...  ...  ..  ..  ..  ..  ...  ...  ...  ..  ...  ...   ...     ...     ...         ...   ...          ...         ...            ...                                        ...       ...        ...         ...          ...           ...           ...              ...              ...              ...          ...     ...      ...  ...        ...           ...            ...            ...        ...        ...        ...        ...        ...         ...         ...                     ...                          ...                          ...                      ...           ...           ...           ...           ...           ...            ...
3184        99.899663         156.555        205.4385  130    0  240  20  40  50.0  110.0   90.0  110.0    0.0  0.0   0   0   0   0    0    0    0  10    0   10    27  HEA220  HEA500         MLE    24          YES      S355JR          A325M                             AISC-360-05/10        HE        210          HE          490           355           490              660              830              372            0       2  MLE0407  0.0   superior  viga primero  viga inferior       inferior   no_usado   no_usado   no_usado   no_usado   no_usado    no_usado    no_usado  superior__viga primero  viga primero__viga inferior      viga inferior__inferior                   UNUSED        UNUSED        UNUSED        UNUSED        UNUSED        UNUSED         UNUSED
3190        50.901142          97.128        123.9660  125    0  180  15  40  41.5   90.0   55.0   90.0    0.0  0.0   0   0   0   0    0    0    0  10    0   10    22  HEA160  HEB450         MLE    20          YES      S355JR          A325M                             AISC-360-05/10        HE        152          HE          450           355           490              660              830              372            0       2  MLE0018  0.0   superior  viga primero  viga inferior       inferior   no_usado   no_usado   no_usado   no_usado   no_usado    no_usado    no_usado  superior__viga primero  viga primero__viga inferior      viga inferior__inferior                   UNUSED        UNUSED        UNUSED        UNUSED        UNUSED        UNUSED         UNUSED
3192       396.707175         366.360        269.9775  145    0  225  30  50  65.0  145.0  120.0  120.0  145.0  0.0   0   0   0   0    0    0    0  10    0   10    33  IPE400  HEB600         MLE    30          YES      S355JR          A325M                             AISC-360-05/10       IPE        400          HE          600           355           490              660              830              372            0       3  MLE0341  0.0   superior  viga primero   viga central  viga inferior   inferior   no_usado   no_usado   no_usado   no_usado    no_usado    no_usado  superior__viga primero   viga primero__viga central  viga central__viga inferior  viga inferior__inferior        UNUSED        UNUSED        UNUSED        UNUSED        UNUSED         UNUSED
3193        26.730000          60.710          0.0000   95    0  140  15  35  33.0   90.0   90.0    0.0    0.0  0.0   0   0   0   0    0    0    0  10   10    0    18  HEA120  HEA600         MLE    16           NO      S355JR           10.9                             AISC-360-05/10        HE        114          HE          590           355           490              900             1000              500            0       1  MLE6123  0.0   superior  viga central       inferior       no_usado   no_usado   no_usado   no_usado   no_usado   no_usado    no_usado    no_usado  superior__viga central       viga central__inferior                       UNUSED                   UNUSED        UNUSED        UNUSED        UNUSED        UNUSED        UNUSED         UNUSED
3194       393.940000         306.720          0.0000  120    0  190  20  35  35.0   80.0  240.0   80.0    0.0  0.0   0   0   0   0    0    0    0  12   12    0    22  IPE360  HEB700         MLE    20           NO      S355JR           10.9                             AISC-360-05/10       IPE        360          HE          700           355           490              900             1000              500            0       2  MLE6414  0.0   superior  viga primero  viga inferior       inferior   no_usado   no_usado   no_usado   no_usado   no_usado    no_usado    no_usado  superior__viga primero  viga primero__viga inferior      viga inferior__inferior                   UNUSED        UNUSED        UNUSED        UNUSED        UNUSED        UNUSED         UNUSED

[1467 rows x 67 columns]

In [68]:
resumen_separaciones.head()

                              transicion  Bolt  numero_casos  minimo  percentil_05  percentil_10  mediana       media  maximo  grupo_suficiente
0   cantonera central__cantonera central    27            21   120.0         120.0         120.0    120.0  143.571429   175.0              True
1   cantonera central__cantonera central    30            14   135.0         135.0         135.0    137.5  141.071429   165.0             False
2  cantonera central__cantonera inferior    16             9    45.0          45.0          45.0     45.0   45.000000    45.0             False
3  cantonera central__cantonera inferior    20            20    55.0          55.0          55.0     55.0   55.000000    55.0              True
4  cantonera central__cantonera inferior    22             1    65.0          65.0          65.0     65.0   65.000000    65.0             False

In [69]:
df.to_parquet(Path().cwd() / "model_store" / "global_dataset.parquet")

In [70]:
df.to_excel(Path().cwd() / "model_store" / "global_dataset.lsxl")