In [78]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path

# PATHS

In [79]:
dir = Path.cwd().parent / "data"
data_excel_path = dir / "CONEXIONES_MOMENTO_ATORNILLADAS_CHAPA_FRONTAL.xlsx"
tekla_excel_path = dir / "Prontuario Tekla19.xlsx"

# CARGA DE DATOS

In [80]:
data = pd.read_excel(data_excel_path, sheet_name="Sheet1")

In [81]:
data.head(20)

,Unicode,BEAM,COLUMN,Capacity_Moment_Percentage,Capacity_Moment,Capacity_Shear_Percentage,Capacity_Shear,Capacity_Axial_Percentage,Capacity_Axial,Pr_Porcen,...,National_Annex,p0,tso,Lst,SpecialMomentFrames,MzEd_PanelZone,Vgra,Havg,Yieldmethod,Acero_Estructural_Perfil
0,JBE6000,IPE300,HEA260,121.0,242.94,0,0.0,0,0.0,50,...,-,0.0,0.0,0.0,0.0,-,-,-,1.0,S355JR
1,JBE6001,HEA180,HEA300,121.0,125.60,0,0.0,0,0.0,50,...,-,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
2,JBE6002,IPE300,HEA320,121.0,242.94,0,0.0,0,0.0,50,...,-,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
3,JBE6003,HEA200,HEA280,121.0,166.04,0,0.0,0,0.0,50,...,-,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
4,JBE6004,HEA240,HEA300,121.0,287.86,0,0.0,0,0.0,50,...,-,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
5,JBE6005,IPE330,HEA320,121.0,310.94,0,0.0,0,0.0,50,...,-,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
6,JBE6006,IPE300,HEA240,121.0,242.94,0,0.0,0,0.0,50,...,-,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
7,JBE6007,IPE400,HEA280,121.0,505.28,0,0.0,0,0.0,50,...,-,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
8,JBE6008,IPE360,HEA320,121.0,393.94,0,0.0,0,0.0,50,...,-,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
9,JBE6009,IPE360,HEA300,121.0,393.94,0,0.0,0,0.0,50,...,-,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
10,JBE6010,IPE300,HEA280,121.0,242.94,0,0.0,0,0.0,50,...,-,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
11,JBE6011,IPE330,HEA240,121.0,310.94,0,0.0,0,0.0,50,...,-,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
12,JBE6012,IPE330,HEA260,121.0,310.94,0,0.0,0,0.0,50,...,-,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
13,JBE6013,IPE330,HEA300,121.0,310.94,0,0.0,0,0.0,50,...,-,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
14,JBE6014,IPE300,HEA300,121.0,242.94,0,0.0,0,0.0,50,...,-,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
15,JBE6015,IPE360,HEA340,121.0,393.94,0,0.0,0,0.0,50,...,-,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
16,JBE6016,IPE360,HEA400,121.0,393.94,0,0.0,0,0.0,50,...,-,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
17,JBE6017,HEA260,HEA300,121.0,355.59,0,0.0,0,0.0,50,...,-,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
18,JBE6018,IPE360,HEA260,121.0,393.94,0,0.0,0,0.0,50,...,-,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
19,JBE6019,HEA300,HEA500,121.0,534.66,0,0.0,0,0.0,50,...,-,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN

# DESCRIPCIÓN DE VARIABLES

- UNICODE: Identificador global de la unión
- BEAM: Estandar de viga
- COLUMN: Estandar de columna
- Capacity_Moment_Percentage: Porcentaje de momento
- Capacity_Moment: Momento
- Capacity_Shear_Percentage: Porcentaje de capacidad de fractura
- Capacity_Shear: Capacidad de fractura
- Capacity_Axial_Percentage: porcentaje de capacidad axial
- Capacity_Axial: Capacidad axial
- Pr_Porcen: 
- DrawingCode: 
- g: Distancia entre los centros de los tornillos
- tws: Grosor chapa columna
- Lws: Alto chapa columna
- Bws: Ancho chapa columna
- Bp: Ancho chapa tornillos
- Lp: Alto chapa tornillos
- tp: Grosor chapa tornillos
- Lh: Altura viga-
- e: Distancia borde chapa-primer tornillo
- d: Distancia tornillo-ala viga
- pfo: Todo nulls (descarte directo)
- pX: Distancia entre tornillo x y x+1
- ts: Grosor rigidizdor columna
- tbs: Grosor rigidizador viga
- tst: Grosor rigidizador columna-viga (union viga-columna)
- thw: 
- thf:
- wX:
- Bolt: Estandar grosor tornillos
- Hole: Agujero tornillos
- SlipCritical: Necesidad de 
- Normativas: Normativa
- AceroEstructural: Tipo de acero utilizado
- ElectrodoSoldadura: Tipo de soldadura
- EstandarTornillos: Estandar Tornillos
- Ordinary_Moment_Frames: 
- Calculation_Tool: Herramienta de cálculo utilizado
- Source: Región
- Designation: Designación
- rib_thk:
- Representation_Angle:
- BoltConnectionTypeSelection:
- National_Annex: Anexo nacional (excepciones en designaciones)
- p0:
- tso:
- Lst:
- SpecialMomentFrames:
- MzEd_PanelZone:
- Vgra: 
- Havg:
- Yieldmethod:
- Acero_Estructural_Perfil:

Veamos los tipos de las clases y sus valores:

In [82]:
for index, row in data.dtypes.items():
    print(f"{index}: {row}")

Unicode: str
BEAM: str
COLUMN: str
Capacity_Moment_Percentage: float64
Capacity_Moment: float64
Capacity_Shear_Percentage: int64
Capacity_Shear: float64
Capacity_Axial_Percentage: int64
Capacity_Axial: float64
Pr_Porcen: int64
DrawingCode: str
g: int64
tws: int64
Lws: int64
Bws: int64
Bp: int64
Lp: int64
tp: int64
Lh: float64
e: int64
d: float64
pfo: float64
p1: float64
p2: float64
p3: float64
p4: float64
p5: float64
p6: int64
p7: int64
p8: int64
p9: int64
p10: int64
p11: int64
p12: int64
ts: int64
tbs: int64
tst: int64
thw: float64
thf: float64
w1: int64
w2: int64
w3: object
w4: object
w5: object
w6: object
Bolt: str
Hole: int64
SlipCritical: str
Normativas: str
AceroEstructural: str
ElectrodoSoldadura: str
EstandarTornillos: object
Ordinary_Moment_Frames: bool
Calculation_Tool: str
Source: str
Designation: str
rib_thk: int64
Representation_Angle: int64
BoltConnectionTypeSelection: int64
National_Annex: str
p0: float64
tso: float64
Lst: float64
SpecialMomentFrames: float64
MzEd_PanelZone: object
Vgra: object
Havg: object
Yieldmethod: float64
Acero_Estructural_Perfil: str

Vemos que algunas wX son de tipo Object, debido a que los 0 son -.

In [83]:
data.replace("-", 0, inplace=True)
data[["w3", "w4", "w5", "w6"]] = data[["w3", "w4", "w5", "w6"]].astype(np.int64)

In [84]:
for index, row in data.dtypes.items():
    print(f"{index}: {row}")

Unicode: str
BEAM: str
COLUMN: str
Capacity_Moment_Percentage: float64
Capacity_Moment: float64
Capacity_Shear_Percentage: int64
Capacity_Shear: float64
Capacity_Axial_Percentage: int64
Capacity_Axial: float64
Pr_Porcen: int64
DrawingCode: str
g: int64
tws: int64
Lws: int64
Bws: int64
Bp: int64
Lp: int64
tp: int64
Lh: float64
e: int64
d: float64
pfo: float64
p1: float64
p2: float64
p3: float64
p4: float64
p5: float64
p6: int64
p7: int64
p8: int64
p9: int64
p10: int64
p11: int64
p12: int64
ts: int64
tbs: int64
tst: int64
thw: float64
thf: float64
w1: int64
w2: int64
w3: int64
w4: int64
w5: int64
w6: int64
Bolt: str
Hole: int64
SlipCritical: str
Normativas: str
AceroEstructural: str
ElectrodoSoldadura: str
EstandarTornillos: object
Ordinary_Moment_Frames: bool
Calculation_Tool: object
Source: str
Designation: str
rib_thk: int64
Representation_Angle: int64
BoltConnectionTypeSelection: int64
National_Annex: object
p0: float64
tso: float64
Lst: float64
SpecialMomentFrames: float64
MzEd_PanelZone: object
Vgra: object
Havg: object
Yieldmethod: float64
Acero_Estructural_Perfil: str

Separamos por tipo de columna

In [85]:
numerical_columns = data.select_dtypes(include=[np.number]).columns.tolist()
categorical_columns = data.select_dtypes(include=['object', "str", "bool"]).columns.tolist()

In [86]:
numerical_df = data[numerical_columns]
categorical_df = data[categorical_columns]

Vamos a analizar las columnas por su tipo de dato.

## COLUMNAS NUMÉRICAS

In [87]:
numerical_df.head()

,Capacity_Moment_Percentage,Capacity_Moment,Capacity_Shear_Percentage,Capacity_Shear,Capacity_Axial_Percentage,Capacity_Axial,Pr_Porcen,g,tws,Lws,...,w6,Hole,rib_thk,Representation_Angle,BoltConnectionTypeSelection,p0,tso,Lst,SpecialMomentFrames,Yieldmethod
0,121.0,242.94,0,0.0,0,0.0,50,110,0,0,...,6,22,0,0,0,0.0,0.0,0.0,0.0,1.0
1,121.0,125.60,0,0.0,0,0.0,50,110,0,0,...,6,18,0,0,0,0.0,0.0,0.0,0.0,NaN
2,121.0,242.94,0,0.0,0,0.0,50,110,0,0,...,6,22,0,0,0,0.0,0.0,0.0,0.0,NaN
3,121.0,166.04,0,0.0,0,0.0,50,110,0,0,...,6,18,0,0,0,0.0,0.0,0.0,0.0,NaN
4,121.0,287.86,0,0.0,0,0.0,50,120,0,0,...,7,22,0,0,0,0.0,0.0,0.0,0.0,NaN

In [88]:
numerical_df.columns

Index(['Capacity_Moment_Percentage', 'Capacity_Moment',
       'Capacity_Shear_Percentage', 'Capacity_Shear',
       'Capacity_Axial_Percentage', 'Capacity_Axial', 'Pr_Porcen', 'g', 'tws',
       'Lws', 'Bws', 'Bp', 'Lp', 'tp', 'Lh', 'e', 'd', 'pfo', 'p1', 'p2', 'p3',
       'p4', 'p5', 'p6', 'p7', 'p8', 'p9', 'p10', 'p11', 'p12', 'ts', 'tbs',
       'tst', 'thw', 'thf', 'w1', 'w2', 'w3', 'w4', 'w5', 'w6', 'Hole',
       'rib_thk', 'Representation_Angle', 'BoltConnectionTypeSelection', 'p0',
       'tso', 'Lst', 'SpecialMomentFrames', 'Yieldmethod'],
      dtype='str')

## CAPACIDADES Y PORCENTAJES

Estas variables indican las cargas, pero son datos redundantes entre sí, por lo que nos quedamos solo con no porcentajes.

In [89]:
# numerical_df.drop(columns=['Capacity_Moment', 'Capacity_Shear', 'Capacity_Axial'], inplace=True)

## VALORES NULOS, IGUALES O A 0

Vemos que la columna "Pr_Porcen" tiene siempre el valor 50, por lo que podemos eliminarla

In [90]:
describe = numerical_df.describe().transpose()

Veamos si alguna fila tiene todos los valores a 0:

In [91]:
for row in describe.iterrows():
    if row[1]["mean"] == 0:
        print(f"Row {row[0]} values are 0")

Row rib_thk values are 0
Row Representation_Angle values are 0
Row BoltConnectionTypeSelection values are 0

In [92]:
numerical_df.Representation_Angle.value_counts()

Representation_Angle
0    4767
Name: count, dtype: int64

In [93]:
numerical_df.BoltConnectionTypeSelection.value_counts()

BoltConnectionTypeSelection
0    4767
Name: count, dtype: int64

In [94]:
numerical_df.rib_thk.value_counts()

rib_thk
0    4767
Name: count, dtype: int64

Vemos que "Representation_Angle", "rib_thk" y "BoltConnectionTypeSelection" tienen todos los valores a 0, por lo que no serán relevantes para el modelo.

In [95]:
numerical_df.isna().sum()

Capacity_Moment_Percentage        0
Capacity_Moment                   0
Capacity_Shear_Percentage         0
Capacity_Shear                    0
Capacity_Axial_Percentage         0
Capacity_Axial                    0
Pr_Porcen                         0
g                                 0
tws                               0
Lws                               0
Bws                               0
Bp                                0
Lp                                0
tp                                0
Lh                                0
e                                 0
d                                 0
pfo                            4767
p1                                0
p2                                0
p3                                0
p4                                0
p5                                0
p6                                0
p7                                0
p8                                0
p9                                0
p10                               0
p11                               0
p12                               0
ts                                0
tbs                               0
tst                               0
thw                               0
thf                               0
w1                                0
w2                                0
w3                                0
w4                                0
w5                                0
w6                                0
Hole                              0
rib_thk                           0
Representation_Angle              0
BoltConnectionTypeSelection       0
p0                             3490
tso                            3490
Lst                            3490
SpecialMomentFrames            3490
Yieldmethod                    4397
dtype: int64

Vemos que pfo tiene todos sus valores a Na, por lo que la descartaremos.

In [96]:
numerical_df.drop(columns=["Pr_Porcen", "Representation_Angle", "rib_thk", "BoltConnectionTypeSelection", "pfo"], inplace=True)
numerical_df.head()

,Capacity_Moment_Percentage,Capacity_Moment,Capacity_Shear_Percentage,Capacity_Shear,Capacity_Axial_Percentage,Capacity_Axial,g,tws,Lws,Bws,...,w3,w4,w5,w6,Hole,p0,tso,Lst,SpecialMomentFrames,Yieldmethod
0,121.0,242.94,0,0.0,0,0.0,110,0,0,0,...,0,0,6,6,22,0.0,0.0,0.0,0.0,1.0
1,121.0,125.60,0,0.0,0,0.0,110,0,0,0,...,0,0,6,6,18,0.0,0.0,0.0,0.0,NaN
2,121.0,242.94,0,0.0,0,0.0,110,0,0,0,...,0,0,6,6,22,0.0,0.0,0.0,0.0,NaN
3,121.0,166.04,0,0.0,0,0.0,110,0,0,0,...,0,0,6,6,18,0.0,0.0,0.0,0.0,NaN
4,121.0,287.86,0,0.0,0,0.0,120,0,0,0,...,0,0,7,7,22,0.0,0.0,0.0,0.0,NaN

## CHAPA DE LA COLUMNA

Siguiendo indicaciones, podemos eliminar ancho y largo de la plancha que se pone en la columna (si aplica), ya que solo nos interesa su grosor

In [97]:
numerical_df.drop(columns=["Lws", "Bws"], inplace=True)

Comentar que si no tiene esta chapa, el valor será 0. Se determinará un mínimo para el grosor.

## CANTONERA y SOLDADURA

Se deduce de las filas de tornillos.

Sabemos que las variables wX y thw se refieren a propiedades de soldado, que no vamos a utilizar, por lo que podemos eliminarlas

Hecho esto, eliminamos las medidas:

In [98]:
numerical_df.drop(columns=["thw", "thf", "w1", "w2", "w3", "w4", "w5", "w6"], inplace=True)

## RIGIDIZADORES

Los rigidizadores tienen medidas en función de la columna y viga y, en principio, siempre aparecene, por lo que lo relacionado con ello se elimina

In [99]:
numerical_df.drop(columns=["tso", "Lst"], inplace=True)

In [100]:
numerical_df.columns

Index(['Capacity_Moment_Percentage', 'Capacity_Moment',
       'Capacity_Shear_Percentage', 'Capacity_Shear',
       'Capacity_Axial_Percentage', 'Capacity_Axial', 'g', 'tws', 'Bp', 'Lp',
       'tp', 'Lh', 'e', 'd', 'p1', 'p2', 'p3', 'p4', 'p5', 'p6', 'p7', 'p8',
       'p9', 'p10', 'p11', 'p12', 'ts', 'tbs', 'tst', 'Hole', 'p0',
       'SpecialMomentFrames', 'Yieldmethod'],
      dtype='str')

# QUITAR SPECIAL

## COLUMNAS CATEGÓRICAS

In [101]:
categorical_df.columns

Index(['Unicode', 'BEAM', 'COLUMN', 'DrawingCode', 'Bolt', 'SlipCritical',
       'Normativas', 'AceroEstructural', 'ElectrodoSoldadura',
       'EstandarTornillos', 'Ordinary_Moment_Frames', 'Calculation_Tool',
       'Source', 'Designation', 'National_Annex', 'MzEd_PanelZone', 'Vgra',
       'Havg', 'Acero_Estructural_Perfil'],
      dtype='str')

Veamos un poco las categorías

## NORMATIVA (PARA LAS MEDIDAS)

Quien va a identificar el estandar va a ser la combinación Normativas-National_Annex

In [102]:
categorical_df["National_Annex"] = categorical_df["National_Annex"].replace(0, "", inplace=True)

C:\Users\jabal\AppData\Local\Temp\ipykernel_4388\1378253261.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  categorical_df["National_Annex"] = categorical_df["National_Annex"].replace(0, "", inplace=True)

In [103]:
categorical_df["National_Annex"].value_counts()

National_Annex
                               3548
SP RK EN 1993-1-8:2005/2011    1219
Name: count, dtype: int64

In [104]:
categorical_df["standard"] = (
    categorical_df["Normativas"].fillna("").astype(str)
    + categorical_df["National_Annex"].map(lambda x: f" - {x}" if x else "")
)

In [105]:
categorical_df[categorical_df["National_Annex"] != ""].head()

,Unicode,BEAM,COLUMN,DrawingCode,Bolt,SlipCritical,Normativas,AceroEstructural,ElectrodoSoldadura,EstandarTornillos,Ordinary_Moment_Frames,Calculation_Tool,Source,Designation,National_Annex,MzEd_PanelZone,Vgra,Havg,Acero_Estructural_Perfil,standard
535,MHE2000,HEA160,HEA160,MHE,M20,NO,EN 1993-1-8,S355JR,E480,10.9,False,Hojas de Excel,European,Tekla19,SP RK EN 1993-1-8:2005/2011,NaN,NaN,NaN,NaN,EN 1993-1-8 - SP RK EN 1993-1-8:2005/2011
536,MHE2001,HEA160,HEA180,MHE,M20,NO,EN 1993-1-8,S355JR,E480,10.9,False,Hojas de Excel,European,Tekla19,SP RK EN 1993-1-8:2005/2011,NaN,NaN,NaN,NaN,EN 1993-1-8 - SP RK EN 1993-1-8:2005/2011
537,MHE2002,HEA160,HEA200,MHE,M20,NO,EN 1993-1-8,S355JR,E480,10.9,False,Hojas de Excel,European,Tekla19,SP RK EN 1993-1-8:2005/2011,NaN,NaN,NaN,NaN,EN 1993-1-8 - SP RK EN 1993-1-8:2005/2011
538,MHE2003,HEA160,HEA220,MHE,M20,NO,EN 1993-1-8,S355JR,E480,10.9,False,Hojas de Excel,European,Tekla19,SP RK EN 1993-1-8:2005/2011,NaN,NaN,NaN,NaN,EN 1993-1-8 - SP RK EN 1993-1-8:2005/2011
539,MHE2004,HEA160,HEA240,MHE,M20,NO,EN 1993-1-8,S355JR,E480,10.9,False,Hojas de Excel,European,Tekla19,SP RK EN 1993-1-8:2005/2011,NaN,NaN,NaN,NaN,EN 1993-1-8 - SP RK EN 1993-1-8:2005/2011

In [106]:
#categorical_df.drop(columns=["Normativas", "National_Annex"], inplace=True)

categorical_df.head()

,Unicode,BEAM,COLUMN,DrawingCode,Bolt,SlipCritical,Normativas,AceroEstructural,ElectrodoSoldadura,EstandarTornillos,Ordinary_Moment_Frames,Calculation_Tool,Source,Designation,National_Annex,MzEd_PanelZone,Vgra,Havg,Acero_Estructural_Perfil,standard
0,JBE6000,IPE300,HEA260,MOE,M20,NO,AISC-360-05/10,S355JR,E480,10.9,True,Hojas de Excel,European,Tekla19,,0,0,0,S355JR,AISC-360-05/10
1,JBE6001,HEA180,HEA300,MOE,M16,NO,AISC-360-05/10,S355JR,E480,10.9,True,Hojas de Excel,European,Tekla19,,NaN,NaN,NaN,NaN,AISC-360-05/10
2,JBE6002,IPE300,HEA320,MOE,M20,NO,AISC-360-05/10,S355JR,E480,10.9,True,Hojas de Excel,European,Tekla19,,NaN,NaN,NaN,NaN,AISC-360-05/10
3,JBE6003,HEA200,HEA280,MOE,M16,NO,AISC-360-05/10,S355JR,E480,10.9,True,Hojas de Excel,European,Tekla19,,NaN,NaN,NaN,NaN,AISC-360-05/10
4,JBE6004,HEA240,HEA300,MOE,M20,NO,AISC-360-05/10,S355JR,E480,10.9,True,Hojas de Excel,European,Tekla19,,NaN,NaN,NaN,NaN,AISC-360-05/10

Con esto, junto a al código de columna o viga sabremos las medidas de estas.

## SOLDADURAS

Como hemos hecho en las variables numéricas, eliminamos todas las columnas relacionadas con las soldaduras

In [107]:
categorical_df.drop(columns=["ElectrodoSoldadura"], inplace=True)

## OTRAS VARIABLES A ELIMINAR

La herramienta de cálculo es irrelevante, por lo que la eliminamos.

Todas las designaciones son "Tekla19", por lo que la eliminamos.

In [108]:
categorical_df.drop(columns=["Calculation_Tool", "Designation", 
'MzEd_PanelZone', 'Vgra', 'Havg', 'Ordinary_Moment_Frames', 'Acero_Estructural_Perfil'], inplace=True)

In [109]:
categorical_df.columns

Index(['Unicode', 'BEAM', 'COLUMN', 'DrawingCode', 'Bolt', 'SlipCritical',
       'Normativas', 'AceroEstructural', 'EstandarTornillos', 'Source',
       'National_Annex', 'standard'],
      dtype='str')

In [110]:
numerical_df.drop(columns=["Yieldmethod"], inplace=True)

# DATAFRAME FINAL

In [111]:
df_final = pd.concat([numerical_df, categorical_df], axis=1)

df_final.head()

,Capacity_Moment_Percentage,Capacity_Moment,Capacity_Shear_Percentage,Capacity_Shear,Capacity_Axial_Percentage,Capacity_Axial,g,tws,Bp,Lp,...,COLUMN,DrawingCode,Bolt,SlipCritical,Normativas,AceroEstructural,EstandarTornillos,Source,National_Annex,standard
0,121.0,242.94,0,0.0,0,0.0,110,0,190,705,...,HEA260,MOE,M20,NO,AISC-360-05/10,S355JR,10.9,European,,AISC-360-05/10
1,121.0,125.60,0,0.0,0,0.0,110,0,200,466,...,HEA300,MOE,M16,NO,AISC-360-05/10,S355JR,10.9,European,,AISC-360-05/10
2,121.0,242.94,0,0.0,0,0.0,110,0,190,705,...,HEA320,MOE,M20,NO,AISC-360-05/10,S355JR,10.9,European,,AISC-360-05/10
3,121.0,166.04,0,0.0,0,0.0,110,0,220,565,...,HEA280,MOE,M16,NO,AISC-360-05/10,S355JR,10.9,European,,AISC-360-05/10
4,121.0,287.86,0,0.0,0,0.0,120,0,240,600,...,HEA300,MOE,M20,NO,AISC-360-05/10,S355JR,10.9,European,,AISC-360-05/10

Vamos a poner el unicode como identificador de las filas, que son únicas dentro de nuestro sistema.

In [112]:
# df_final.set_index("Unicode", inplace=True)

# df_final.head()

In [113]:
df_final.columns

Index(['Capacity_Moment_Percentage', 'Capacity_Moment',
       'Capacity_Shear_Percentage', 'Capacity_Shear',
       'Capacity_Axial_Percentage', 'Capacity_Axial', 'g', 'tws', 'Bp', 'Lp',
       'tp', 'Lh', 'e', 'd', 'p1', 'p2', 'p3', 'p4', 'p5', 'p6', 'p7', 'p8',
       'p9', 'p10', 'p11', 'p12', 'ts', 'tbs', 'tst', 'Hole', 'p0',
       'SpecialMomentFrames', 'Unicode', 'BEAM', 'COLUMN', 'DrawingCode',
       'Bolt', 'SlipCritical', 'Normativas', 'AceroEstructural',
       'EstandarTornillos', 'Source', 'National_Annex', 'standard'],
      dtype='str')

# QUITAR FILAS SPECIALMOMENTFRAMES VERDADERO

In [114]:
df_final.shape

(4767, 44)

In [115]:
df_final_c = df_final[df_final["SpecialMomentFrames"] != 1]

In [116]:
df_final_c.shape

(4722, 44)

In [117]:
(df_final_c["p0"] > 0).sum()

np.int64(0)

In [118]:
df_final = df_final_c.drop(columns=["p0", "SpecialMomentFrames"])

# AÑADIR DATOS DE TEKLA

In [119]:
xls = pd.ExcelFile(dir / "Prontuario Tekla19.xlsx")
eu = pd.read_excel(xls, 'Tekla19 europeo')
cad = pd.read_excel(xls, 'Tekla19 canadiense')
resto = pd.read_csv(dir / "tekla_faltante.csv")

In [120]:
df_union = pd.concat([eu, cad, resto])
df_union = df_union[["tekla_nomenclature_1", "type", "d_mm", 
        "bf_mm", "tw_mm", "tf_mm", "r1_mm", "wely_mm", "w_kgm"
        ]]

In [121]:
df_union.dtypes

tekla_nomenclature_1        str
type                        str
d_mm                    float64
bf_mm                   float64
tw_mm                   float64
tf_mm                   float64
r1_mm                   float64
wely_mm                 float64
w_kgm                   float64
dtype: object

In [122]:
faltan_BEAM = set(df_final["BEAM"].unique()) - set(df_union["tekla_nomenclature_1"].unique())
faltan_COLUMN = set(df_final["COLUMN"].unique()) - set(df_union["tekla_nomenclature_1"].unique())

faltan_BEAM | faltan_COLUMN

set()

In [123]:
union_BEAM = (df_union.set_index('tekla_nomenclature_1')
    .add_prefix('BEAM_')
    .reset_index()
)

union_COLUMN = (df_union.set_index('tekla_nomenclature_1')
    .add_prefix('COLUMN_')
    .reset_index()
)
union_BEAM

,tekla_nomenclature_1,BEAM_type,BEAM_d_mm,BEAM_bf_mm,BEAM_tw_mm,BEAM_tf_mm,BEAM_r1_mm,BEAM_wely_mm,BEAM_w_kgm
0,HEA100,HE,96.0,100.0,5.0,8.0,12.0,72.80,16.700001
1,HEA1000,HE,990.0,300.0,16.5,31.0,30.0,11190.00,272.000000
2,HEA120,HE,114.0,120.0,5.0,8.0,12.0,106.30,19.900000
3,HEA140,HE,133.0,140.0,5.5,8.5,12.0,155.40,24.700001
4,HEA160,HE,152.0,160.0,6.0,9.0,15.0,220.10,30.400000
...,...,...,...,...,...,...,...,...,...
402,HI900-60-70*300,HI,1040.0,300.0,60.0,70.0,0.0,26041.54,753.600000
403,HI900060070*300,HI,1040.0,300.0,60.0,70.0,0.0,26041.54,753.600000
404,HI920-30-65*350,HI,1050.0,350.0,30.0,65.0,0.0,24760.09,573.800000
405,HI920-30-65*500,HI,1050.0,500.0,30.0,65.0,0.0,33782.40,726.900000
406,IPE180,IPE,180.0,91.0,5.3,8.0,9.0,146.00,18.800000

In [124]:
df_final.shape

(4722, 42)

In [125]:
df_merge1 = pd.merge(df_final, union_BEAM, left_on="BEAM", right_on="tekla_nomenclature_1").drop(columns=["tekla_nomenclature_1"])
df_merge2 = pd.merge(df_merge1, union_COLUMN, left_on="COLUMN", right_on="tekla_nomenclature_1").drop(columns=["tekla_nomenclature_1"])
df_merge2

,Capacity_Moment_Percentage,Capacity_Moment,Capacity_Shear_Percentage,Capacity_Shear,Capacity_Axial_Percentage,Capacity_Axial,g,tws,Bp,Lp,...,BEAM_wely_mm,BEAM_w_kgm,COLUMN_type,COLUMN_d_mm,COLUMN_bf_mm,COLUMN_tw_mm,COLUMN_tf_mm,COLUMN_r1_mm,COLUMN_wely_mm,COLUMN_w_kgm
0,121.0,242.94,0,0.0,0,0.0,110,0,190,705,...,557.0,42.200000,HE,250.0,260.0,7.5,12.5,24.0,836.4,68.199997
1,121.0,125.60,0,0.0,0,0.0,110,0,200,466,...,293.6,35.500000,HE,290.0,300.0,8.5,14.0,27.0,1260.0,88.300000
2,121.0,242.94,0,0.0,0,0.0,110,0,190,705,...,557.0,42.200000,HE,310.0,300.0,9.0,15.5,27.0,1479.0,97.599998
3,121.0,166.04,0,0.0,0,0.0,110,0,220,565,...,388.6,42.299999,HE,270.0,280.0,8.0,13.0,24.0,1013.0,76.400002
4,121.0,287.86,0,0.0,0,0.0,120,0,240,600,...,675.1,60.299999,HE,290.0,300.0,8.5,14.0,27.0,1260.0,88.300000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4717,121.0,534.66,0,0.0,0,0.0,120,0,305,695,...,1260.0,88.300000,HE,620.0,305.0,21.0,40.0,27.0,7660.0,285.000000
4718,121.0,1037.23,0,0.0,0,0.0,140,0,305,849,...,2400.0,142.000000,HE,620.0,305.0,21.0,40.0,27.0,7660.0,285.000000
4719,121.0,505.28,0,0.0,0,0.0,110,0,200,880,...,1160.0,66.300000,HE,240.0,240.0,10.0,17.0,21.0,938.3,83.199997
4720,121.0,722.55,0,0.0,0,0.0,135,0,300,815,...,1678.0,117.000000,HE,350.0,300.0,10.0,17.5,27.0,1891.0,112.000000
4721,121.0,722.55,0,0.0,0,0.0,135,0,300,730,...,1678.0,117.000000,HE,440.0,300.0,11.5,21.0,27.0,2896.0,140.000000

In [126]:
df_merge2.drop(columns=["BEAM_r1_mm", "BEAM_wely_mm", "BEAM_w_kgm","COLUMN_r1_mm", "COLUMN_wely_mm", "COLUMN_w_kgm"],
                inplace=True)

# AÑADIR RESISTENCIAS ACERO Y TORNILLOS

In [127]:
df_aceros = pd.DataFrame([
    {
        "grado_acero": "S275JR",
        "fy_acero_mpa": 275.0,  # Límite elástico (MPa)
        "fu_acero_mpa": 430.0   # Resistencia a tracción (MPa)
    },
    {
        "grado_acero": "S355JR",
        "fy_acero_mpa": 355.0,
        "fu_acero_mpa": 490.0
    }
])

df_tornillos = pd.DataFrame([
    {
        "clase_tornillo": "8.8",
        "fy_tornillo_mpa": 640.0,  # Límite elástico (MPa) - Corregido
        "fu_tornillo_mpa": 800.0,  # Resistencia a tracción (MPa)
        "fv_tornillo_mpa": 480.0   # Resistencia a cortante (MPa)
    },
    {
        "clase_tornillo": "10.9",
        "fy_tornillo_mpa": 900.0,
        "fu_tornillo_mpa": 1000.0,
        "fv_tornillo_mpa": 500.0
    },
    {
        "clase_tornillo": "A325M",
        "fy_tornillo_mpa": 660.0,
        "fu_tornillo_mpa": 830.0,
        "fv_tornillo_mpa": 372.0
    }
])

In [128]:
df_merge2.shape

(4722, 52)

In [129]:
df_final2 = pd.merge(df_merge2, df_aceros, left_on="AceroEstructural", right_on="grado_acero")
df_final2.shape

(4722, 55)

In [130]:
df_final2['EstandarTornillos'] = df_final2['EstandarTornillos'].replace({ 'ASTM A325': "A325M"}).astype(str)

In [131]:
df_final3 = pd.merge(df_final2, df_tornillos, left_on="EstandarTornillos", right_on="clase_tornillo")
df_final3.shape

(4722, 59)

In [132]:
df_final3.drop(columns=["grado_acero", "clase_tornillo"], inplace=True)

In [133]:
df_final3.columns

Index(['Capacity_Moment_Percentage', 'Capacity_Moment',
       'Capacity_Shear_Percentage', 'Capacity_Shear',
       'Capacity_Axial_Percentage', 'Capacity_Axial', 'g', 'tws', 'Bp', 'Lp',
       'tp', 'Lh', 'e', 'd', 'p1', 'p2', 'p3', 'p4', 'p5', 'p6', 'p7', 'p8',
       'p9', 'p10', 'p11', 'p12', 'ts', 'tbs', 'tst', 'Hole', 'Unicode',
       'BEAM', 'COLUMN', 'DrawingCode', 'Bolt', 'SlipCritical', 'Normativas',
       'AceroEstructural', 'EstandarTornillos', 'Source', 'National_Annex',
       'standard', 'BEAM_type', 'BEAM_d_mm', 'BEAM_bf_mm', 'BEAM_tw_mm',
       'BEAM_tf_mm', 'COLUMN_type', 'COLUMN_d_mm', 'COLUMN_bf_mm',
       'COLUMN_tw_mm', 'COLUMN_tf_mm', 'fy_acero_mpa', 'fu_acero_mpa',
       'fy_tornillo_mpa', 'fu_tornillo_mpa', 'fv_tornillo_mpa'],
      dtype='str')

## DISTANCIAS

In [134]:
# de int a float
int_a_float = ['p6',
"p7",
'p8',
'p9',
'p10',
'p11',
'p12']

for col in int_a_float:
    df_final3[col] = df_final3[col].astype(float)

In [135]:
import numpy as np
import pandas as pd


def transformar_topologia_y_cotas(df):
    """Transforma pasos relativos (p_i) en cotas absolutas desde el borde

    superior de la chapa (Y_i = e + sum(p_k)) y clasifica filas por zona
    viga.
    """
    p_cols = [f'p{i}' for i in range(1, 13)]

    def procesar_fila(row):
        pasos = [
            row[col] for col in p_cols if pd.notna(row[col]) and row[col] > 0
        ]
        n_filas = len(pasos) + 1 if pd.notna(row.get('e')) else 0

        res = {
            'n_sup': 0,
            'n_alma': 0,
            'n_cantonera': 0,
            'n_inf': 0,
            'num_filas': n_filas,
        }

        # Inicializamos 12 cotas Y1..Y12 (correspondientes al tornillo final de cada paso p1..p12)
        for i in range(1, 13):
            res[f'Y{i}'] = 0.0

        if n_filas < 2:
            return pd.Series(res)

        # 1. Cotas Absolutas (Origen Y=0 en Borde Superior de la Chapa)
        e = row['e']
        Y_coords = [e]  # Fila 1 está en cota 'e'

        # Y1 = e + p1, Y2 = e + p1 + p2...
        y_acum = e
        for p in pasos:
            y_acum += p
            Y_coords.append(y_acum)

        # Guardar en Y1..Y12 (Y_coords tiene len = n_filas)
        for idx, y_val in enumerate(Y_coords[1:], start=1):
            res[f'Y{idx}'] = y_val

        # 2. Fronteras físicas de la viga
        d = row.get('d', 0)
        h_beam = row['BEAM_d_mm']

        y_ala_sup = e + d
        y_ala_inf = e + d + h_beam

        # 3. Clasificación topológica por zonas
        n_debajo = 0
        for y_val in Y_coords:
            if y_val < y_ala_sup:
                res['n_sup'] += 1  # Tornillos por encima de la viga
            elif y_val <= y_ala_inf:
                res['n_alma'] += 1  # Tornillos entre las alas
            else:
                n_debajo += 1  # Tornillos por debajo de la viga

        # 4. Desglose cantonera / fuera
        if n_debajo > 0:
            res['n_inf'] = 1
            res['n_cantonera'] = n_debajo - 1
        else:
            res['n_inf'] = 0
            res['n_cantonera'] = 0

        return pd.Series(res)

    df_transformado = df.apply(procesar_fila, axis=1)
    return pd.concat([df, df_transformado], axis=1)


# ==============================================================================
# FUNCIÓN INVERSA PARA RECUPERAR LOS PASOS p_i DE TALLER
# ==============================================================================
def convertir_cotas_a_pasos(df_prediccion):
    """Convierte cotas absolutas Y1..Y12 y borde 'e' de vuelta a pasos relativos

    p1..p12.
    """
    df_res = df_prediccion.copy()

    # p1 = Y1 - e
    if 'Y1' in df_res.columns and 'e' in df_res.columns:
        mask_y1 = df_res['Y1'] > 0
        df_res.loc[mask_y1, 'p1'] = (
            df_res.loc[mask_y1, 'Y1'] - df_res.loc[mask_y1, 'e']
        )
        df_res.loc[~mask_y1, 'p1'] = 0.0

    # p_i = Y_i - Y_{i-1} para i >= 2
    for i in range(2, 13):
        col_actual = f'Y{i}'
        col_anterior = f'Y{i-1}'
        col_paso = f'p{i}'

        if col_actual in df_res.columns and col_anterior in df_res.columns:
            mask_existe = df_res[col_actual] > 0
            df_res.loc[mask_existe, col_paso] = (
                df_res.loc[mask_existe, col_actual]
                - df_res.loc[mask_existe, col_anterior]
            )
            df_res.loc[~mask_existe, col_paso] = 0.0

    return df_res

df_resultado = transformar_topologia_y_cotas(df_final3)

In [136]:
df_resultado.columns

Index(['Capacity_Moment_Percentage', 'Capacity_Moment',
       'Capacity_Shear_Percentage', 'Capacity_Shear',
       'Capacity_Axial_Percentage', 'Capacity_Axial', 'g', 'tws', 'Bp', 'Lp',
       'tp', 'Lh', 'e', 'd', 'p1', 'p2', 'p3', 'p4', 'p5', 'p6', 'p7', 'p8',
       'p9', 'p10', 'p11', 'p12', 'ts', 'tbs', 'tst', 'Hole', 'Unicode',
       'BEAM', 'COLUMN', 'DrawingCode', 'Bolt', 'SlipCritical', 'Normativas',
       'AceroEstructural', 'EstandarTornillos', 'Source', 'National_Annex',
       'standard', 'BEAM_type', 'BEAM_d_mm', 'BEAM_bf_mm', 'BEAM_tw_mm',
       'BEAM_tf_mm', 'COLUMN_type', 'COLUMN_d_mm', 'COLUMN_bf_mm',
       'COLUMN_tw_mm', 'COLUMN_tf_mm', 'fy_acero_mpa', 'fu_acero_mpa',
       'fy_tornillo_mpa', 'fu_tornillo_mpa', 'fv_tornillo_mpa', 'n_sup',
       'n_alma', 'n_cantonera', 'n_inf', 'num_filas', 'Y1', 'Y2', 'Y3', 'Y4',
       'Y5', 'Y6', 'Y7', 'Y8', 'Y9', 'Y10', 'Y11', 'Y12'],
      dtype='str')

In [137]:
df_resultado.drop(columns=['n_sup', 'n_inf', 'num_filas', 'Y1', 'Y2', 'Y3', 'Y4', 'Y5', 'Y6', 'Y7', 'Y8',
       'Y9', 'Y10', 'Y11', 'Y12'], inplace=True)

cols_drop = [
    'BEAM_type', 'COLUMN_type'
]

df_resultado.drop(columns=cols_drop, inplace=True)

# REVISAR TIPOS

In [138]:
for index, row in df_resultado.dtypes.items():
    print(f"{index}: {row}")

Capacity_Moment_Percentage: float64
Capacity_Moment: float64
Capacity_Shear_Percentage: int64
Capacity_Shear: float64
Capacity_Axial_Percentage: int64
Capacity_Axial: float64
g: int64
tws: int64
Bp: int64
Lp: int64
tp: int64
Lh: float64
e: int64
d: float64
p1: float64
p2: float64
p3: float64
p4: float64
p5: float64
p6: float64
p7: float64
p8: float64
p9: float64
p10: float64
p11: float64
p12: float64
ts: int64
tbs: int64
tst: int64
Hole: int64
Unicode: str
BEAM: str
COLUMN: str
DrawingCode: str
Bolt: str
SlipCritical: str
Normativas: str
AceroEstructural: str
EstandarTornillos: str
Source: str
National_Annex: object
standard: str
BEAM_d_mm: float64
BEAM_bf_mm: float64
BEAM_tw_mm: float64
BEAM_tf_mm: float64
COLUMN_d_mm: float64
COLUMN_bf_mm: float64
COLUMN_tw_mm: float64
COLUMN_tf_mm: float64
fy_acero_mpa: float64
fu_acero_mpa: float64
fy_tornillo_mpa: float64
fu_tornillo_mpa: float64
fv_tornillo_mpa: float64
n_alma: float64
n_cantonera: float64

In [139]:
df_final3 = df_resultado

In [140]:
df_final3["Bolt"] = df_final3["Bolt"].str.strip().str.replace("M", "").astype(int)

In [141]:
df_final3["SlipCritical"] = (df_final3["SlipCritical"] == 'YES')

In [142]:
for index, row in df_final3.dtypes.items():
    print(f"{index}: {row}")

Capacity_Moment_Percentage: float64
Capacity_Moment: float64
Capacity_Shear_Percentage: int64
Capacity_Shear: float64
Capacity_Axial_Percentage: int64
Capacity_Axial: float64
g: int64
tws: int64
Bp: int64
Lp: int64
tp: int64
Lh: float64
e: int64
d: float64
p1: float64
p2: float64
p3: float64
p4: float64
p5: float64
p6: float64
p7: float64
p8: float64
p9: float64
p10: float64
p11: float64
p12: float64
ts: int64
tbs: int64
tst: int64
Hole: int64
Unicode: str
BEAM: str
COLUMN: str
DrawingCode: str
Bolt: int64
SlipCritical: bool
Normativas: str
AceroEstructural: str
EstandarTornillos: str
Source: str
National_Annex: object
standard: str
BEAM_d_mm: float64
BEAM_bf_mm: float64
BEAM_tw_mm: float64
BEAM_tf_mm: float64
COLUMN_d_mm: float64
COLUMN_bf_mm: float64
COLUMN_tw_mm: float64
COLUMN_tf_mm: float64
fy_acero_mpa: float64
fu_acero_mpa: float64
fy_tornillo_mpa: float64
fu_tornillo_mpa: float64
fv_tornillo_mpa: float64
n_alma: float64
n_cantonera: float64

In [143]:
df_final3.isna().sum().sum()

np.int64(0)

# QUITAR LOS DISEÑOS QUE DIFIEREN EN CANTONERA

In [144]:
def eliminar_duplicados_con_cantonera(df: pd.DataFrame, load_bin: float = 5.0) -> pd.DataFrame:
    """Elimina diseños con cantonera cuando existe una alternativa equivalente sin ella."""
    if load_bin <= 0:
        raise ValueError("load_bin debe ser mayor que cero")

    df_work = df.copy()
    group_parts = {}

    for column in ["BEAM", "COLUMN", "AceroEstructural", "EstandarTornillos", "standard"]:
        if column in df_work.columns:
            group_parts[column] = df_work[column].astype("string").fillna("<NA>")

    for column in [
        "Capacity_Moment_Percentage",
        "Capacity_Shear_Percentage",
        "Capacity_Axial_Percentage",
    ]:
        if column in df_work.columns:
            values = pd.to_numeric(df_work[column], errors="coerce")
            group_parts[column] = (
                np.floor(values / load_bin)
                .astype("Int64")
                .astype("string")
                .fillna("<NA>")
            )

    if group_parts:
        group_key = pd.concat(group_parts, axis=1)
    else:
        group_key = pd.Series(0, index=df_work.index, name="_group_key")

    def positive_column(column: str) -> pd.Series:
        if column not in df_work.columns:
            return pd.Series(False, index=df_work.index)
        return pd.to_numeric(df_work[column], errors="coerce").fillna(0).gt(0)

    has_cantonera = positive_column("n_cantonera") | positive_column("Lh")

    if group_parts:
        has_option_without_cantonera = (
            (~has_cantonera)
            .groupby([group_key[column] for column in group_key.columns], dropna=False, sort=False)
            .transform("any")
        )
    else:
        has_option_without_cantonera = pd.Series(
            (~has_cantonera).any(), index=df_work.index
        )

    keep = (~has_cantonera) | ~has_option_without_cantonera
    df_filtered = df_work.loc[keep].copy()

    print("[+] Limpieza completada:")
    print(f"    - Filas iniciales : {len(df_work)}")
    print(f"    - Filas eliminadas: {len(df_work) - len(df_filtered)} (diseños duplicados con cantonera)")
    print(f"    - Filas finales   : {len(df_filtered)}")

    return df_filtered

eliminar_duplicados_con_cantonera(df_final3)

[+] Limpieza completada:
    - Filas iniciales : 4722
    - Filas eliminadas: 52 (diseños duplicados con cantonera)
    - Filas finales   : 4670

,Capacity_Moment_Percentage,Capacity_Moment,Capacity_Shear_Percentage,Capacity_Shear,Capacity_Axial_Percentage,Capacity_Axial,g,tws,Bp,Lp,...,COLUMN_bf_mm,COLUMN_tw_mm,COLUMN_tf_mm,fy_acero_mpa,fu_acero_mpa,fy_tornillo_mpa,fu_tornillo_mpa,fv_tornillo_mpa,n_alma,n_cantonera
0,121.0,242.94,0,0.0,0,0.0,110,0,190,705,...,260.0,7.5,12.5,355.0,490.0,900.0,1000.0,500.0,2.0,2.0
1,121.0,125.60,0,0.0,0,0.0,110,0,200,466,...,300.0,8.5,14.0,355.0,490.0,900.0,1000.0,500.0,3.0,1.0
2,121.0,242.94,0,0.0,0,0.0,110,0,190,705,...,300.0,9.0,15.5,355.0,490.0,900.0,1000.0,500.0,2.0,2.0
3,121.0,166.04,0,0.0,0,0.0,110,0,220,565,...,280.0,8.0,13.0,355.0,490.0,900.0,1000.0,500.0,2.0,2.0
4,121.0,287.86,0,0.0,0,0.0,120,0,240,600,...,300.0,8.5,14.0,355.0,490.0,900.0,1000.0,500.0,2.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4717,121.0,534.66,0,0.0,0,0.0,120,0,305,695,...,305.0,21.0,40.0,355.0,490.0,900.0,1000.0,500.0,3.0,2.0
4718,121.0,1037.23,0,0.0,0,0.0,140,0,305,849,...,305.0,21.0,40.0,355.0,490.0,900.0,1000.0,500.0,3.0,2.0
4719,121.0,505.28,0,0.0,0,0.0,110,0,200,880,...,240.0,10.0,17.0,355.0,490.0,900.0,1000.0,500.0,3.0,3.0
4720,121.0,722.55,0,0.0,0,0.0,135,0,300,815,...,300.0,10.0,17.5,355.0,490.0,900.0,1000.0,500.0,2.0,2.0
4721,121.0,722.55,0,0.0,0,0.0,135,0,300,730,...,300.0,11.5,21.0,355.0,490.0,900.0,1000.0,500.0,2.0,2.0

# TRAIN, TEST SPLIT

In [145]:
df_resultado.loc[df_resultado["Lh"]<0,"Lh"] = 0

In [146]:
df_resultado.columns

Index(['Capacity_Moment_Percentage', 'Capacity_Moment',
       'Capacity_Shear_Percentage', 'Capacity_Shear',
       'Capacity_Axial_Percentage', 'Capacity_Axial', 'g', 'tws', 'Bp', 'Lp',
       'tp', 'Lh', 'e', 'd', 'p1', 'p2', 'p3', 'p4', 'p5', 'p6', 'p7', 'p8',
       'p9', 'p10', 'p11', 'p12', 'ts', 'tbs', 'tst', 'Hole', 'Unicode',
       'BEAM', 'COLUMN', 'DrawingCode', 'Bolt', 'SlipCritical', 'Normativas',
       'AceroEstructural', 'EstandarTornillos', 'Source', 'National_Annex',
       'standard', 'BEAM_d_mm', 'BEAM_bf_mm', 'BEAM_tw_mm', 'BEAM_tf_mm',
       'COLUMN_d_mm', 'COLUMN_bf_mm', 'COLUMN_tw_mm', 'COLUMN_tf_mm',
       'fy_acero_mpa', 'fu_acero_mpa', 'fy_tornillo_mpa', 'fu_tornillo_mpa',
       'fv_tornillo_mpa', 'n_alma', 'n_cantonera'],
      dtype='str')

In [147]:
df_resultado.to_csv(dir / "data_final.csv", sep=";", index=False)

In [ ]:
df_train, df_test = train_test_split(df_resultado, test_size=0.2, random_state=2)

In [ ]:
df_train.shape, df_test.shape

In [ ]:
df_train.columns

In [ ]:
df_train.to_parquet(dir / "train_final.parquet")
df_test.to_parquet(dir / "test_final.parquet")

In [ ]:
import pyarrow
print(pyarrow.__version__)

In [ ]:
df = pd.read_parquet("data" / "train.parquet")