In [445]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
import re

In [446]:
pd.set_option("display.max_columns", None)  # Show all columns
pd.set_option("display.width", 1000)

# PATHS

In [447]:
dir = Path.cwd().parent / "V4" / "data"
data_excel_path = dir / "CONEXIONES_MOMENTO_ATORNILLADAS_CHAPA_FRONTAL.xlsx"
tekla_excel_path = dir / "Prontuario Tekla19.xlsx"

# CARGA DE DATOS

In [448]:
data = pd.read_excel(data_excel_path, sheet_name="Sheet1")

In [449]:
data.head(20)

    Unicode    BEAM  COLUMN  Capacity_Moment_Percentage  Capacity_Moment  Capacity_Shear_Percentage  Capacity_Shear  Capacity_Axial_Percentage  Capacity_Axial  Pr_Porcen DrawingCode    g  tws  Lws  Bws   Bp   Lp  tp     Lh   e     d  pfo     p1     p2     p3         p4        p5  p6  p7  p8  p9  p10  p11  p12  ts  tbs  tst   thw   thf  w1  w2 w3 w4 w5 w6 Bolt  Hole SlipCritical      Normativas AceroEstructural ElectrodoSoldadura EstandarTornillos  Ordinary_Moment_Frames Calculation_Tool    Source Designation  rib_thk  Representation_Angle  BoltConnectionTypeSelection National_Annex   p0  tso  Lst  SpecialMomentFrames MzEd_PanelZone Vgra Havg  Yieldmethod Acero_Estructural_Perfil
0   JBE6000  IPE300  HEA260                       121.0           242.94                          0             0.0                          0             0.0         50         MOE  110    0    0    0  190  705  20  245.0  40  40.0  NaN   90.7  198.6   90.7  140.64470  104.3553   0   0   0   0    0    0    0  12   10    0  10.0  10.0   0   6  0  0  6  6  M20    22           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19        0                     0                            0              -  0.0  0.0  0.0                  0.0              -    -    -          1.0                   S355JR
1   JBE6001  HEA180  HEA300                       121.0           125.60                          0             0.0                          0             0.0         50         MOE  110    0    0    0  200  466  20  135.0  35  40.0  NaN   89.5   45.0   50.0   45.00000  155.0000   0   0   0   0    0    0    0  10   10    0  10.0  10.0   0   5  0  0  6  6  M16    18           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19        0                     0                            0              -  0.0  0.0  0.0                  0.0            NaN  NaN  NaN          NaN                      NaN
2   JBE6002  IPE300  HEA320                       121.0           242.94                          0             0.0                          0             0.0         50         MOE  110    0    0    0  190  705  20  245.0  40  40.0  NaN   90.7  198.6   90.7  140.64470  104.3553   0   0   0   0    0    0    0  12   10    0  10.0  10.0   0   6  0  0  6  6  M20    22           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19        0                     0                            0              -  0.0  0.0  0.0                  0.0            NaN  NaN  NaN          NaN                      NaN
3   JBE6003  HEA200  HEA280                       121.0           166.04                          0             0.0                          0             0.0         50         MOE  110    0    0    0  220  565  20  215.0  35  40.0  NaN   90.0   90.0   90.0  111.45300  103.5470   0   0   0   0    0    0    0  10   10    0  10.0  10.0   0   5  0  0  6  6  M16    18           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19        0                     0                            0              -  0.0  0.0  0.0                  0.0            NaN  NaN  NaN          NaN                      NaN
4   JBE6004  HEA240  HEA300                       121.0           287.86                          0             0.0                          0             0.0         50         MOE  120    0    0    0  240  600  25  210.0  40  40.0  NaN   92.0  126.0   92.0  104.14360  105.8564   0   0   0   0    0    0    0  12   10    0  10.0  10.0   0   6  0  0  7  7  M20    22           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19        0                     0                            0              -  0.0  0.0  0.0                  0.0            NaN  NaN  NaN          NaN                      NaN
5   JBE6005  IPE330  HEA320                       121.0           310.94                          0             0.0                          0             0.0         50         MOE  110    0    0    0  190  780  20  250.0  40  50.0  NaN  111.5  207.0  111.5  121.72090  128.2791   0   0   0   0    0    0    0  12   10    0  10.0  10.0   0   6  0  0  6  6  M20    22           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19        0                     0                            0              -  0.0  0.0  0.0                  0.0            NaN  NaN  NaN          NaN                      NaN
6   JBE6006  IPE300  HEA240                       121.0           242.94                          0             0.0                          0             0.0         50         MOE  110    0    0    0  190  705  20  245.0  40  40.0  NaN   90.7  198.6   90.7  140.64470  104.3553   0   0   0   0    0    0    0  12   10    0  10.0  10.0   0   6  0  0  6  6  M20    22           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19        0                     0                            0              -  0.0  0.0  0.0                  0.0            NaN  NaN  NaN          NaN                      NaN
7   JBE6007  IPE400  HEA280                       121.0           505.28                          0             0.0                          0             0.0         50         MOE  120    8  890  330  220  890  20  250.0  40  60.0  NaN  133.5  253.0  133.5   96.41154  153.5885   0   0   0   0    0    0    0  15   10    0  10.0  12.0   0   7  0  8  6  6  M22    24           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19        0                     0                            0              -  0.0  0.0  0.0                  0.0            NaN  NaN  NaN          NaN                      NaN
8   JBE6008  IPE360  HEA320                       121.0           393.94                          0             0.0                          0             0.0         50        MOE1  130    0    0    0  240  815  20  215.0  40  60.0  NaN  132.7  214.6  132.7   62.33530  152.6647   0   0   0   0    0    0    0  15   10    0  10.0  12.0   0   6  0  0  6  6  M20    22           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19        0                     0                            0              -  0.0  0.0  0.0                  0.0            NaN  NaN  NaN          NaN                      NaN
9   JBE6009  IPE360  HEA300                       121.0           393.94                          0             0.0                          0             0.0         50         MOE  130    0    0    0  240  815  20  215.0  40  60.0  NaN  132.7  214.6  132.7   62.33530  152.6647   0   0   0   0    0    0    0  15   10    0  10.0  12.0   0   6  0  0  6  6  M20    22           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19        0                     0                            0              -  0.0  0.0  0.0                  0.0            NaN  NaN  NaN          NaN                      NaN
10  JBE6010  IPE300  HEA280                       121.0           242.94                          0             0.0                          0             0.0         50         MOE  110    0    0    0  190  705  20  245.0  40  40.0  NaN   90.7  198.6   90.7  140.64470  104.3553   0   0   0   0    0    0    0  12   10    0  10.0  10.0   0   6  0  0  6  6  M20    22           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19        0                     0                            0              -  0.0  0.0  0.0                  0.0            NaN  NaN  NaN          NaN                      NaN
11  JBE6011  IPE330  HEA240                       121.0           310.94                          0             0.0                          0             0.0         50         MOE  110    0    0    0  190  780  20  250.0  40  50.0  NaN  111.5  207.0  111.5  121.72090  128.2791   0   0   0   0    0    0    0  12   10    0  10.0  10.0   0   6  0  0  6  6  M20    22           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19        0                     0                            0              -  0.0  0.0  0.0                  0.0            NaN  NaN  NaN          NaN                      NaN
12  JBE6012  IPE330  HEA260                       121.0           310.94                          0             0.0                          0             0.0         50         MOE  110    0    0    0  190  780  20  250.0  40  50.0  NaN  111.5  207.0  111.5  121.72090  128.2791   0   0   0   0    0    0    0  12   10    0  10.0  10.0   0   6  0  0  6  6  M20    22           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19        0                     0                            0              -  0.0  0.0  0.0                  0.0            NaN  NaN  NaN          NaN                      NaN
13  JBE6013  IPE330  HEA300                       121.0           310.94                          0             0.0                          0             0.0         50         MOE  110    0    0    0  190  780  20  250.0  40  50.0  NaN  111.5  207.0  111.5  121.72090  128.2791   0   0   0   0    0    0    0  12   10    0  10.0  10.0   0   6  0  0  6  6  M20    22           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19        0                     0                            0              -  0.0  0.0  0.0                  0.0            NaN  NaN  NaN          NaN                      NaN
14  JBE6014  IPE300  HEA300                       121.0           242.94                          0             0.0                          0             0.0         50         MOE  110    0    0    0  190  705  20  245.0  40  40.0  NaN   90.7  198.6   90.7  140.64470  104.3553   0   0   0   0    0    0    0  12   10    0  10.0  10.0   0   6  0  0  6  6  M20    22           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19        0                     0                            0              -  0.0  0.0  0.0                  0.0            NaN  NaN  NaN          NaN                      NaN
15  JBE6015  IPE360  HEA340                       121.0           393.94                          0             0.0                          0             0.0         50         MOE  130    0    0    0  240  815  20  215.0  40  60.0  NaN  132.7  214.6  132.7   62.33530  152.6647   0   0   0   0    0    0    0  15   10    0  10.0  12.0   0   6  0  0  6  6  M20    22           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19        0                     0                            0              -  0.0  0.0  0.0                  0.0            NaN  NaN  NaN          NaN                      NaN
16  JBE6016  IPE360  HEA400                       121.0           393.94                          0             0.0                          0             0.0         50        MOE1  130    0    0    0  240  815  20  215.0  40  60.0  NaN  132.7  214.6  132.7   62.33530  152.6647   0   0   0   0    0    0    0  15   10    0  10.0  12.0   0   6  0  0  6  6  M20    22           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19        0                     0                            0              -  0.0  0.0  0.0                  0.0            NaN  NaN  NaN          NaN                      NaN
17  JBE6017  HEA260  HEA300                       121.0           355.59                          0             0.0                          0             0.0         50         MOE  120    0    0    0  260  635  25  225.0  40  40.0  NaN   92.5  145.0   92.5  118.56620  106.4338   0   0   0   0    0    0    0  15   10    0  10.0  12.0   0   6  0  0  7  7  M20    22           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19        0                     0                            0              -  0.0  0.0  0.0                  0.0            NaN  NaN  NaN          NaN                      NaN
18  JBE6018  IPE360  HEA260                       121.0           393.94                          0             0.0                          0             0.0         50         MOE  130    0    0    0  240  815  20  215.0  40  60.0  NaN  132.7  214.6  132.7   62.33530  152.6647   0   0   0   0    0    0    0  15   10    0  10.0  12.0   0   6  0  0  6  6  M20    22           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19        0                     0                            0              -  0.0  0.0  0.0                  0.0            NaN  NaN  NaN          NaN                      NaN
19  JBE6019  HEA300  HEA500                       121.0           534.66                          0             0.0                          0             0.0         50        MOE1  140    0    0    0  300  790  25  260.0  40  60.0  NaN  134.0  142.0  134.0  105.83420  154.1658   0   0   0   0    0    0    0  15   10    0  10.0  12.0   0   7  0  0  8  8  M22    24           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19        0                     0                            0              -  0.0  0.0  0.0                  0.0            NaN  NaN  NaN          NaN                      NaN

# DESCRIPCIÓN DE VARIABLES

- UNICODE: Identificador global de la unión
- BEAM: Estandar de viga
- COLUMN: Estandar de columna
- Capacity_Moment_Percentage: Porcentaje de momento
- Capacity_Moment: Momento
- Capacity_Shear_Percentage: Porcentaje de capacidad de fractura
- Capacity_Shear: Capacidad de fractura
- Capacity_Axial_Percentage: porcentaje de capacidad axial
- Capacity_Axial: Capacidad axial
- Pr_Porcen: 
- DrawingCode: 
- g: Distancia entre los centros de los tornillos
- tws: Grosor chapa columna
- Lws: Alto chapa columna
- Bws: Ancho chapa columna
- Bp: Ancho chapa tornillos
- Lp: Alto chapa tornillos
- tp: Grosor chapa tornillos
- Lh: Altura viga-
- e: Distancia borde chapa-primer tornillo
- d: Distancia tornillo-ala viga
- pfo: Todo nulls (descarte directo)
- pX: Distancia entre tornillo x y x+1
- ts: Grosor rigidizdor columna
- tbs: Grosor rigidizador viga
- tst: Grosor rigidizador columna-viga (union viga-columna)
- thw: 
- thf:
- wX:
- Bolt: Estandar grosor tornillos
- Hole: Agujero tornillos
- SlipCritical: Necesidad de 
- Normativas: Normativa
- AceroEstructural: Tipo de acero utilizado
- ElectrodoSoldadura: Tipo de soldadura
- EstandarTornillos: Estandar Tornillos
- Ordinary_Moment_Frames: 
- Calculation_Tool: Herramienta de cálculo utilizado
- Source: Región
- Designation: Designación
- rib_thk:
- Representation_Angle:
- BoltConnectionTypeSelection:
- National_Annex: Anexo nacional (excepciones en designaciones)
- p0:
- tso:
- Lst:
- SpecialMomentFrames:
- MzEd_PanelZone:
- Vgra: 
- Havg:
- Yieldmethod:
- Acero_Estructural_Perfil:

Veamos los tipos de las clases y sus valores:

In [450]:
for index, row in data.dtypes.items():
    print(f"{index}: {row}")

Unicode: str
BEAM: str
COLUMN: str
Capacity_Moment_Percentage: float64
Capacity_Moment: float64
Capacity_Shear_Percentage: int64
Capacity_Shear: float64
Capacity_Axial_Percentage: int64
Capacity_Axial: float64
Pr_Porcen: int64
DrawingCode: str
g: int64
tws: int64
Lws: int64
Bws: int64
Bp: int64
Lp: int64
tp: int64
Lh: float64
e: int64
d: float64
pfo: float64
p1: float64
p2: float64
p3: float64
p4: float64
p5: float64
p6: int64
p7: int64
p8: int64
p9: int64
p10: int64
p11: int64
p12: int64
ts: int64
tbs: int64
tst: int64
thw: float64
thf: float64
w1: int64
w2: int64
w3: object
w4: object
w5: object
w6: object
Bolt: str
Hole: int64
SlipCritical: str
Normativas: str
AceroEstructural: str
ElectrodoSoldadura: str
EstandarTornillos: object
Ordinary_Moment_Frames: bool
Calculation_Tool: str
Source: str
Designation: str
rib_thk: int64
Representation_Angle: int64
BoltConnectionTypeSelection: int64
National_Annex: str
p0: float64
tso: float64
Lst: float64
SpecialMomentFrames: float64
MzEd_PanelZone: object
Vgra: object
Havg: object
Yieldmethod: float64
Acero_Estructural_Perfil: str

Vemos que algunas wX son de tipo Object, debido a que los 0 son -.

Separamos por tipo de columna

In [451]:
numerical_columns = data.select_dtypes(include=[np.number]).columns.tolist()
categorical_columns = data.select_dtypes(
    include=["object", "str", "bool"]
).columns.tolist()

In [452]:
numerical_df = data[numerical_columns]
categorical_df = data[categorical_columns]

Vamos a analizar las columnas por su tipo de dato.

## COLUMNAS NUMÉRICAS

In [453]:
numerical_df.head()

   Capacity_Moment_Percentage  Capacity_Moment  Capacity_Shear_Percentage  Capacity_Shear  Capacity_Axial_Percentage  Capacity_Axial  Pr_Porcen    g  tws  Lws  Bws   Bp   Lp  tp     Lh   e     d  pfo    p1     p2    p3        p4        p5  p6  p7  p8  p9  p10  p11  p12  ts  tbs  tst   thw   thf  w1  w2  Hole  rib_thk  Representation_Angle  BoltConnectionTypeSelection   p0  tso  Lst  SpecialMomentFrames  Yieldmethod
0                       121.0           242.94                          0             0.0                          0             0.0         50  110    0    0    0  190  705  20  245.0  40  40.0  NaN  90.7  198.6  90.7  140.6447  104.3553   0   0   0   0    0    0    0  12   10    0  10.0  10.0   0   6    22        0                     0                            0  0.0  0.0  0.0                  0.0          1.0
1                       121.0           125.60                          0             0.0                          0             0.0         50  110    0    0    0  200  466  20  135.0  35  40.0  NaN  89.5   45.0  50.0   45.0000  155.0000   0   0   0   0    0    0    0  10   10    0  10.0  10.0   0   5    18        0                     0                            0  0.0  0.0  0.0                  0.0          NaN
2                       121.0           242.94                          0             0.0                          0             0.0         50  110    0    0    0  190  705  20  245.0  40  40.0  NaN  90.7  198.6  90.7  140.6447  104.3553   0   0   0   0    0    0    0  12   10    0  10.0  10.0   0   6    22        0                     0                            0  0.0  0.0  0.0                  0.0          NaN
3                       121.0           166.04                          0             0.0                          0             0.0         50  110    0    0    0  220  565  20  215.0  35  40.0  NaN  90.0   90.0  90.0  111.4530  103.5470   0   0   0   0    0    0    0  10   10    0  10.0  10.0   0   5    18        0                     0                            0  0.0  0.0  0.0                  0.0          NaN
4                       121.0           287.86                          0             0.0                          0             0.0         50  120    0    0    0  240  600  25  210.0  40  40.0  NaN  92.0  126.0  92.0  104.1436  105.8564   0   0   0   0    0    0    0  12   10    0  10.0  10.0   0   6    22        0                     0                            0  0.0  0.0  0.0                  0.0          NaN

In [454]:
numerical_df.columns

Index(['Capacity_Moment_Percentage', 'Capacity_Moment', 'Capacity_Shear_Percentage', 'Capacity_Shear', 'Capacity_Axial_Percentage', 'Capacity_Axial', 'Pr_Porcen', 'g', 'tws', 'Lws', 'Bws', 'Bp', 'Lp', 'tp', 'Lh', 'e', 'd', 'pfo', 'p1', 'p2', 'p3', 'p4', 'p5', 'p6', 'p7', 'p8', 'p9', 'p10', 'p11', 'p12', 'ts', 'tbs', 'tst', 'thw', 'thf', 'w1', 'w2', 'Hole', 'rib_thk', 'Representation_Angle', 'BoltConnectionTypeSelection', 'p0', 'tso', 'Lst', 'SpecialMomentFrames', 'Yieldmethod'], dtype='str')

## CAPACIDADES Y PORCENTAJES

Estas variables indican las cargas. Se conservan **solo los porcentajes** (convertidos a ratio 0-1+): son adimensionales y es lo que Excel puede enviar; los valores absolutos se descartan más abajo.

In [455]:
# numerical_df.drop(columns=['Capacity_Moment', 'Capacity_Shear', 'Capacity_Axial'], inplace=True)

## VALORES NULOS, IGUALES O A 0

Vemos que la columna "Pr_Porcen" tiene siempre el valor 50, por lo que podemos eliminarla

In [456]:
describe = numerical_df.describe().transpose()

Veamos si alguna fila tiene todos los valores a 0:

In [457]:
for row in describe.iterrows():
    if row[1]["mean"] == 0:
        print(f"Row {row[0]} values are 0")

Row rib_thk values are 0
Row Representation_Angle values are 0
Row BoltConnectionTypeSelection values are 0

In [458]:
numerical_df.Representation_Angle.value_counts()

Representation_Angle
0    4767
Name: count, dtype: int64

In [459]:
numerical_df.BoltConnectionTypeSelection.value_counts()

BoltConnectionTypeSelection
0    4767
Name: count, dtype: int64

In [460]:
numerical_df.rib_thk.value_counts()

rib_thk
0    4767
Name: count, dtype: int64

Vemos que "Representation_Angle", "rib_thk" y "BoltConnectionTypeSelection" tienen todos los valores a 0, por lo que no serán relevantes para el modelo.

In [461]:
numerical_df.isna().sum()

Capacity_Moment_Percentage        0
Capacity_Moment                   0
Capacity_Shear_Percentage         0
Capacity_Shear                    0
Capacity_Axial_Percentage         0
Capacity_Axial                    0
Pr_Porcen                         0
g                                 0
tws                               0
Lws                               0
Bws                               0
Bp                                0
Lp                                0
tp                                0
Lh                                0
e                                 0
d                                 0
pfo                            4767
p1                                0
p2                                0
p3                                0
p4                                0
p5                                0
p6                                0
p7                                0
p8                                0
p9                                0
p10                               0
p11                               0
p12                               0
ts                                0
tbs                               0
tst                               0
thw                               0
thf                               0
w1                                0
w2                                0
Hole                              0
rib_thk                           0
Representation_Angle              0
BoltConnectionTypeSelection       0
p0                             3490
tso                            3490
Lst                            3490
SpecialMomentFrames            3490
Yieldmethod                    4397
dtype: int64

Vemos que pfo tiene todos sus valores a Na, por lo que la descartaremos.

In [462]:
numerical_df.drop(
    columns=[
        "Pr_Porcen",
        "Representation_Angle",
        "rib_thk",
        "BoltConnectionTypeSelection",
        "pfo",
    ],
    inplace=True,
)
numerical_df.head()

   Capacity_Moment_Percentage  Capacity_Moment  Capacity_Shear_Percentage  Capacity_Shear  Capacity_Axial_Percentage  Capacity_Axial    g  tws  Lws  Bws   Bp   Lp  tp     Lh   e     d    p1     p2    p3        p4        p5  p6  p7  p8  p9  p10  p11  p12  ts  tbs  tst   thw   thf  w1  w2  Hole   p0  tso  Lst  SpecialMomentFrames  Yieldmethod
0                       121.0           242.94                          0             0.0                          0             0.0  110    0    0    0  190  705  20  245.0  40  40.0  90.7  198.6  90.7  140.6447  104.3553   0   0   0   0    0    0    0  12   10    0  10.0  10.0   0   6    22  0.0  0.0  0.0                  0.0          1.0
1                       121.0           125.60                          0             0.0                          0             0.0  110    0    0    0  200  466  20  135.0  35  40.0  89.5   45.0  50.0   45.0000  155.0000   0   0   0   0    0    0    0  10   10    0  10.0  10.0   0   5    18  0.0  0.0  0.0                  0.0          NaN
2                       121.0           242.94                          0             0.0                          0             0.0  110    0    0    0  190  705  20  245.0  40  40.0  90.7  198.6  90.7  140.6447  104.3553   0   0   0   0    0    0    0  12   10    0  10.0  10.0   0   6    22  0.0  0.0  0.0                  0.0          NaN
3                       121.0           166.04                          0             0.0                          0             0.0  110    0    0    0  220  565  20  215.0  35  40.0  90.0   90.0  90.0  111.4530  103.5470   0   0   0   0    0    0    0  10   10    0  10.0  10.0   0   5    18  0.0  0.0  0.0                  0.0          NaN
4                       121.0           287.86                          0             0.0                          0             0.0  120    0    0    0  240  600  25  210.0  40  40.0  92.0  126.0  92.0  104.1436  105.8564   0   0   0   0    0    0    0  12   10    0  10.0  10.0   0   6    22  0.0  0.0  0.0                  0.0          NaN

## CHAPA DE LA COLUMNA

Siguiendo indicaciones, podemos eliminar ancho y largo de la plancha que se pone en la columna (si aplica), ya que solo nos interesa su grosor

In [463]:
numerical_df.drop(columns=["Lws", "Bws"], inplace=True)

Comentar que si no tiene esta chapa, el valor será 0. Se determinará un mínimo para el grosor.

## CANTONERA y SOLDADURA

Se deduce de las filas de tornillos.

Sabemos que las variables wX y thw se refieren a propiedades de soldado, que no vamos a utilizar, por lo que podemos eliminarlas

Hecho esto, eliminamos las medidas:

In [464]:
numerical_df.drop(columns=["thw", "thf", "w1", "w2"], inplace=True)

## RIGIDIZADORES

Los rigidizadores tienen medidas en función de la columna y viga y, en principio, siempre aparecene, por lo que lo relacionado con ello se elimina

In [465]:
numerical_df.drop(columns=["tso", "Lst"], inplace=True)

In [466]:
numerical_df.columns

Index(['Capacity_Moment_Percentage', 'Capacity_Moment', 'Capacity_Shear_Percentage', 'Capacity_Shear', 'Capacity_Axial_Percentage', 'Capacity_Axial', 'g', 'tws', 'Bp', 'Lp', 'tp', 'Lh', 'e', 'd', 'p1', 'p2', 'p3', 'p4', 'p5', 'p6', 'p7', 'p8', 'p9', 'p10', 'p11', 'p12', 'ts', 'tbs', 'tst', 'Hole', 'p0', 'SpecialMomentFrames', 'Yieldmethod'], dtype='str')

# QUITAR SPECIAL

## COLUMNAS CATEGÓRICAS

In [467]:
categorical_df.columns

Index(['Unicode', 'BEAM', 'COLUMN', 'DrawingCode', 'w3', 'w4', 'w5', 'w6', 'Bolt', 'SlipCritical', 'Normativas', 'AceroEstructural', 'ElectrodoSoldadura', 'EstandarTornillos', 'Ordinary_Moment_Frames', 'Calculation_Tool', 'Source', 'Designation', 'National_Annex', 'MzEd_PanelZone', 'Vgra', 'Havg', 'Acero_Estructural_Perfil'], dtype='str')

Veamos un poco las categorías

## NORMATIVA (PARA LAS MEDIDAS)

Quien va a identificar el estandar va a ser la combinación Normativas-National_Annex

In [468]:
categorical_df["National_Annex"] = (
    categorical_df["National_Annex"].replace(0, "-").fillna("-")
)
categorical_df["standard"] = categorical_df["Normativas"].fillna("").astype(
    str
) + categorical_df["National_Annex"].map(lambda x: f" - {x}" if x and x != "-" else "")

In [469]:
categorical_df[categorical_df["National_Annex"] != ""].head()

   Unicode    BEAM  COLUMN DrawingCode w3 w4 w5 w6 Bolt SlipCritical      Normativas AceroEstructural ElectrodoSoldadura EstandarTornillos  Ordinary_Moment_Frames Calculation_Tool    Source Designation National_Annex MzEd_PanelZone Vgra Havg Acero_Estructural_Perfil        standard
0  JBE6000  IPE300  HEA260         MOE  0  0  6  6  M20           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19              -              -    -    -                   S355JR  AISC-360-05/10
1  JBE6001  HEA180  HEA300         MOE  0  0  6  6  M16           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19              -            NaN  NaN  NaN                      NaN  AISC-360-05/10
2  JBE6002  IPE300  HEA320         MOE  0  0  6  6  M20           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19              -            NaN  NaN  NaN                      NaN  AISC-360-05/10
3  JBE6003  HEA200  HEA280         MOE  0  0  6  6  M16           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19              -            NaN  NaN  NaN                      NaN  AISC-360-05/10
4  JBE6004  HEA240  HEA300         MOE  0  0  7  7  M20           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19              -            NaN  NaN  NaN                      NaN  AISC-360-05/10

In [470]:
# categorical_df.drop(columns=["Normativas", "National_Annex"], inplace=True)

categorical_df.head()

   Unicode    BEAM  COLUMN DrawingCode w3 w4 w5 w6 Bolt SlipCritical      Normativas AceroEstructural ElectrodoSoldadura EstandarTornillos  Ordinary_Moment_Frames Calculation_Tool    Source Designation National_Annex MzEd_PanelZone Vgra Havg Acero_Estructural_Perfil        standard
0  JBE6000  IPE300  HEA260         MOE  0  0  6  6  M20           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19              -              -    -    -                   S355JR  AISC-360-05/10
1  JBE6001  HEA180  HEA300         MOE  0  0  6  6  M16           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19              -            NaN  NaN  NaN                      NaN  AISC-360-05/10
2  JBE6002  IPE300  HEA320         MOE  0  0  6  6  M20           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19              -            NaN  NaN  NaN                      NaN  AISC-360-05/10
3  JBE6003  HEA200  HEA280         MOE  0  0  6  6  M16           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19              -            NaN  NaN  NaN                      NaN  AISC-360-05/10
4  JBE6004  HEA240  HEA300         MOE  0  0  7  7  M20           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19              -            NaN  NaN  NaN                      NaN  AISC-360-05/10

Con esto, junto a al código de columna o viga sabremos las medidas de estas.

## SOLDADURAS

Como hemos hecho en las variables numéricas, eliminamos todas las columnas relacionadas con las soldaduras

In [471]:
categorical_df.drop(
    columns=["ElectrodoSoldadura", "w3", "w4", "w5", "w6"], inplace=True
)

## OTRAS VARIABLES A ELIMINAR

La herramienta de cálculo es irrelevante, por lo que la eliminamos.

Todas las designaciones son "Tekla19", por lo que la eliminamos.

In [472]:
categorical_df.drop(
    columns=[
        "Calculation_Tool",
        "Designation",
        "MzEd_PanelZone",
        "Vgra",
        "Havg",
        "Ordinary_Moment_Frames",
        "Acero_Estructural_Perfil",
    ],
    inplace=True,
)

In [473]:
categorical_df.columns

Index(['Unicode', 'BEAM', 'COLUMN', 'DrawingCode', 'Bolt', 'SlipCritical', 'Normativas', 'AceroEstructural', 'EstandarTornillos', 'Source', 'National_Annex', 'standard'], dtype='str')

In [474]:
numerical_df.drop(columns=["Yieldmethod"], inplace=True)

# DATAFRAME FINAL

In [475]:
df_final = pd.concat([numerical_df, categorical_df], axis=1)

df_final.head()

   Capacity_Moment_Percentage  Capacity_Moment  Capacity_Shear_Percentage  Capacity_Shear  Capacity_Axial_Percentage  Capacity_Axial    g  tws   Bp   Lp  tp     Lh   e     d    p1     p2    p3        p4        p5  p6  p7  p8  p9  p10  p11  p12  ts  tbs  tst  Hole   p0  SpecialMomentFrames  Unicode    BEAM  COLUMN DrawingCode Bolt SlipCritical      Normativas AceroEstructural EstandarTornillos    Source National_Annex        standard
0                       121.0           242.94                          0             0.0                          0             0.0  110    0  190  705  20  245.0  40  40.0  90.7  198.6  90.7  140.6447  104.3553   0   0   0   0    0    0    0  12   10    0    22  0.0                  0.0  JBE6000  IPE300  HEA260         MOE  M20           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10
1                       121.0           125.60                          0             0.0                          0             0.0  110    0  200  466  20  135.0  35  40.0  89.5   45.0  50.0   45.0000  155.0000   0   0   0   0    0    0    0  10   10    0    18  0.0                  0.0  JBE6001  HEA180  HEA300         MOE  M16           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10
2                       121.0           242.94                          0             0.0                          0             0.0  110    0  190  705  20  245.0  40  40.0  90.7  198.6  90.7  140.6447  104.3553   0   0   0   0    0    0    0  12   10    0    22  0.0                  0.0  JBE6002  IPE300  HEA320         MOE  M20           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10
3                       121.0           166.04                          0             0.0                          0             0.0  110    0  220  565  20  215.0  35  40.0  90.0   90.0  90.0  111.4530  103.5470   0   0   0   0    0    0    0  10   10    0    18  0.0                  0.0  JBE6003  HEA200  HEA280         MOE  M16           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10
4                       121.0           287.86                          0             0.0                          0             0.0  120    0  240  600  25  210.0  40  40.0  92.0  126.0  92.0  104.1436  105.8564   0   0   0   0    0    0    0  12   10    0    22  0.0                  0.0  JBE6004  HEA240  HEA300         MOE  M20           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10

Vamos a poner el unicode como identificador de las filas, que son únicas dentro de nuestro sistema.

In [476]:
# El Unicode se conserva COMO COLUMNA (antes se ponía de índice y los merge posteriores lo perdían).
assert df_final["Unicode"].is_unique, "Unicode duplicado"
df_final = df_final.rename(columns={"Unicode": "UNICODE"})

In [477]:
df_final.columns

Index(['Capacity_Moment_Percentage', 'Capacity_Moment', 'Capacity_Shear_Percentage', 'Capacity_Shear', 'Capacity_Axial_Percentage', 'Capacity_Axial', 'g', 'tws', 'Bp', 'Lp', 'tp', 'Lh', 'e', 'd', 'p1', 'p2', 'p3', 'p4', 'p5', 'p6', 'p7', 'p8', 'p9', 'p10', 'p11', 'p12', 'ts', 'tbs', 'tst', 'Hole', 'p0', 'SpecialMomentFrames', 'UNICODE', 'BEAM', 'COLUMN', 'DrawingCode', 'Bolt', 'SlipCritical', 'Normativas', 'AceroEstructural', 'EstandarTornillos', 'Source', 'National_Annex', 'standard'], dtype='str')

# QUITAR FILAS SPECIALMOMENTFRAMES VERDADERO

In [478]:
df_final.shape

(4767, 44)

In [479]:
df_final_c = df_final[df_final["SpecialMomentFrames"] != 1]

In [480]:
df_final_c.shape

(4722, 44)

In [481]:
(df_final_c["p0"] > 0).sum()

np.int64(0)

In [482]:
df_final = df_final_c.drop(columns=["p0", "SpecialMomentFrames"])

# AÑADIR DATOS DE TEKLA

In [483]:
excel_path = dir / "Prontuario Tekla19 1.xlsx"

with pd.ExcelFile(excel_path) as xls:
    eu = pd.read_excel(xls, sheet_name="Tekla19 europeo")
    cad = pd.read_excel(xls, sheet_name="Tekla19 canadiense")

resto = pd.read_csv(dir / "tekla_faltante.csv")

In [484]:
df_union = pd.concat([eu, cad, resto])
df_union = df_union[
    [
        "tekla_nomenclature_1",
        "type",
        "d_mm",
        "bf_mm",
        "tw_mm",
        "tf_mm",
        "r1_mm",
        "wely_mm",
        "w_kgm",
    ]
].drop_duplicates()
# Un perfil duplicado con medidas distintas multiplicaría filas en el merge sin avisar.
dup = df_union[df_union["tekla_nomenclature_1"].duplicated(keep=False)]
assert dup.empty, (
    f"Perfiles duplicados con medidas distintas:\n{dup.sort_values('tekla_nomenclature_1')}"
)

In [485]:
df_union.dtypes

tekla_nomenclature_1        str
type                        str
d_mm                    float64
bf_mm                   float64
tw_mm                   float64
tf_mm                   float64
r1_mm                   float64
wely_mm                 float64
w_kgm                   float64
dtype: object

In [486]:
faltan_BEAM = set(df_final["BEAM"].unique()) - set(
    df_union["tekla_nomenclature_1"].unique()
)
faltan_COLUMN = set(df_final["COLUMN"].unique()) - set(
    df_union["tekla_nomenclature_1"].unique()
)

faltan_BEAM | faltan_COLUMN

set()

In [487]:
union_BEAM = (
    df_union.set_index("tekla_nomenclature_1").add_prefix("BEAM_").reset_index()
)

union_COLUMN = (
    df_union.set_index("tekla_nomenclature_1").add_prefix("COLUMN_").reset_index()
)
union_BEAM

    tekla_nomenclature_1 BEAM_type  BEAM_d_mm  BEAM_bf_mm  BEAM_tw_mm  BEAM_tf_mm  BEAM_r1_mm  BEAM_wely_mm  BEAM_w_kgm
0                 HEA100        HE       96.0       100.0         5.0         8.0        12.0         72.80   16.700001
1                HEA1000        HE      990.0       300.0        16.5        31.0        30.0      11190.00  272.000000
2                 HEA120        HE      114.0       120.0         5.0         8.0        12.0        106.30   19.900000
3                 HEA140        HE      133.0       140.0         5.5         8.5        12.0        155.40   24.700001
4                 HEA160        HE      152.0       160.0         6.0         9.0        15.0        220.10   30.400000
..                   ...       ...        ...         ...         ...         ...         ...           ...         ...
402      HI900-60-70*300        HI     1040.0       300.0        60.0        70.0         0.0      26041.54  753.600000
403      HI900060070*300        HI     1040.0       300.0        60.0        70.0         0.0      26041.54  753.600000
404      HI920-30-65*350        HI     1050.0       350.0        30.0        65.0         0.0      24760.09  573.800000
405      HI920-30-65*500        HI     1050.0       500.0        30.0        65.0         0.0      33782.40  726.900000
406               IPE180       IPE      180.0        91.0         5.3         8.0         9.0        146.00   18.800000

[407 rows x 9 columns]

In [488]:
df_final.shape

(4722, 42)

In [489]:
n0 = len(df_final)
df_merge1 = pd.merge(
    df_final,
    union_BEAM,
    left_on="BEAM",
    right_on="tekla_nomenclature_1",
    how="left",
    validate="m:1",
).drop(columns=["tekla_nomenclature_1"])
df_merge2 = pd.merge(
    df_merge1,
    union_COLUMN,
    left_on="COLUMN",
    right_on="tekla_nomenclature_1",
    how="left",
    validate="m:1",
).drop(columns=["tekla_nomenclature_1"])
assert len(df_merge2) == n0, "el merge ha cambiado el nº de filas"
sin_perfil = df_merge2[["BEAM_d_mm", "COLUMN_d_mm"]].isna().any(axis=1)
print(f"Uniones sin dimensiones de perfil (se eliminan): {int(sin_perfil.sum())}")
df_merge2 = df_merge2[~sin_perfil].reset_index(drop=True)
df_merge2.shape

Uniones sin dimensiones de perfil (se eliminan): 0

(4722, 58)

In [490]:
df_merge2.drop(
    columns=[
        "BEAM_r1_mm",
        "BEAM_wely_mm",
        "BEAM_w_kgm",
        "COLUMN_r1_mm",
        "COLUMN_wely_mm",
        "COLUMN_w_kgm",
    ],
    inplace=True,
)

# AÑADIR RESISTENCIAS ACERO Y TORNILLOS

In [491]:
df_aceros = pd.DataFrame(
    [
        {
            "grado_acero": "S275JR",
            "fy_acero_mpa": 275.0,  # Límite elástico (MPa)
            "fu_acero_mpa": 430.0,  # Resistencia a tracción (MPa)
        },
        {"grado_acero": "S355JR", "fy_acero_mpa": 355.0, "fu_acero_mpa": 490.0},
    ]
)

df_tornillos = pd.DataFrame(
    [
        {
            "clase_tornillo": "8.8",
            "fy_tornillo_mpa": 640.0,  # Límite elástico (MPa) - Corregido
            "fu_tornillo_mpa": 800.0,  # Resistencia a tracción (MPa)
            "fv_tornillo_mpa": 480.0,  # Resistencia a cortante (MPa)
        },
        {
            "clase_tornillo": "10.9",
            "fy_tornillo_mpa": 900.0,
            "fu_tornillo_mpa": 1000.0,
            "fv_tornillo_mpa": 500.0,
        },
        {
            "clase_tornillo": "A325M",
            "fy_tornillo_mpa": 660.0,
            "fu_tornillo_mpa": 830.0,
            "fv_tornillo_mpa": 372.0,
        },
    ]
)

In [492]:
df_merge2.shape

(4722, 52)

In [493]:
df_final2 = pd.merge(
    df_merge2,
    df_aceros,
    left_on="AceroEstructural",
    right_on="grado_acero",
    how="left",
    validate="m:1",
)
desconocido = df_final2["fy_acero_mpa"].isna()
print(
    f"Aceros no reconocidos (se eliminan): {int(desconocido.sum())}  {df_final2.loc[desconocido, 'AceroEstructural'].unique()[:5]}"
)
df_final2 = df_final2[~desconocido].reset_index(drop=True)
df_final2.shape

Aceros no reconocidos (se eliminan): 0  <ArrowStringArray>
[]
Length: 0, dtype: str

(4722, 55)

In [494]:
df_final2["EstandarTornillos"] = (
    df_final2["EstandarTornillos"].replace({"ASTM A325": "A325M"}).astype(str)
)

In [495]:
df_final3 = pd.merge(
    df_final2,
    df_tornillos,
    left_on="EstandarTornillos",
    right_on="clase_tornillo",
    how="left",
    validate="m:1",
)
desconocido = df_final3["fy_tornillo_mpa"].isna()
print(
    f"Tornillos no reconocidos (se eliminan): {int(desconocido.sum())}  {df_final3.loc[desconocido, 'EstandarTornillos'].unique()[:5]}"
)
df_final3 = df_final3[~desconocido].reset_index(drop=True)
df_final3.shape

Tornillos no reconocidos (se eliminan): 0  <ArrowStringArray>
[]
Length: 0, dtype: str

(4722, 59)

In [496]:
# Se conservan grado_acero y clase_tornillo (nombres que usa el servidor); los duplicados originales sobran.
df_final3.drop(columns=["AceroEstructural", "EstandarTornillos"], inplace=True)

In [497]:
df_final3.columns

Index(['Capacity_Moment_Percentage', 'Capacity_Moment', 'Capacity_Shear_Percentage', 'Capacity_Shear', 'Capacity_Axial_Percentage', 'Capacity_Axial', 'g', 'tws', 'Bp', 'Lp', 'tp', 'Lh', 'e', 'd', 'p1', 'p2', 'p3', 'p4', 'p5', 'p6', 'p7', 'p8', 'p9', 'p10', 'p11', 'p12', 'ts', 'tbs', 'tst', 'Hole', 'UNICODE', 'BEAM', 'COLUMN', 'DrawingCode', 'Bolt', 'SlipCritical', 'Normativas', 'Source', 'National_Annex', 'standard', 'BEAM_type', 'BEAM_d_mm', 'BEAM_bf_mm', 'BEAM_tw_mm', 'BEAM_tf_mm', 'COLUMN_type', 'COLUMN_d_mm', 'COLUMN_bf_mm', 'COLUMN_tw_mm', 'COLUMN_tf_mm', 'grado_acero', 'fy_acero_mpa', 'fu_acero_mpa', 'clase_tornillo', 'fy_tornillo_mpa', 'fu_tornillo_mpa', 'fv_tornillo_mpa'], dtype='str')

In [498]:
df = df_final3
df.head()

   Capacity_Moment_Percentage  Capacity_Moment  Capacity_Shear_Percentage  Capacity_Shear  Capacity_Axial_Percentage  Capacity_Axial    g  tws   Bp   Lp  tp     Lh   e     d    p1     p2    p3        p4        p5  p6  p7  p8  p9  p10  p11  p12  ts  tbs  tst  Hole  UNICODE    BEAM  COLUMN DrawingCode Bolt SlipCritical      Normativas    Source National_Annex        standard BEAM_type  BEAM_d_mm  BEAM_bf_mm  BEAM_tw_mm  BEAM_tf_mm COLUMN_type  COLUMN_d_mm  COLUMN_bf_mm  COLUMN_tw_mm  COLUMN_tf_mm grado_acero  fy_acero_mpa  fu_acero_mpa clase_tornillo  fy_tornillo_mpa  fu_tornillo_mpa  fv_tornillo_mpa
0                       121.0           242.94                          0             0.0                          0             0.0  110    0  190  705  20  245.0  40  40.0  90.7  198.6  90.7  140.6447  104.3553   0   0   0   0    0    0    0  12   10    0    22  JBE6000  IPE300  HEA260         MOE  M20           NO  AISC-360-05/10  European              -  AISC-360-05/10       IPE      300.0       150.0         7.1        10.7          HE        250.0         260.0           7.5          12.5      S355JR         355.0         490.0           10.9            900.0           1000.0            500.0
1                       121.0           125.60                          0             0.0                          0             0.0  110    0  200  466  20  135.0  35  40.0  89.5   45.0  50.0   45.0000  155.0000   0   0   0   0    0    0    0  10   10    0    18  JBE6001  HEA180  HEA300         MOE  M16           NO  AISC-360-05/10  European              -  AISC-360-05/10        HE      171.0       180.0         6.0         9.5          HE        290.0         300.0           8.5          14.0      S355JR         355.0         490.0           10.9            900.0           1000.0            500.0
2                       121.0           242.94                          0             0.0                          0             0.0  110    0  190  705  20  245.0  40  40.0  90.7  198.6  90.7  140.6447  104.3553   0   0   0   0    0    0    0  12   10    0    22  JBE6002  IPE300  HEA320         MOE  M20           NO  AISC-360-05/10  European              -  AISC-360-05/10       IPE      300.0       150.0         7.1        10.7          HE        310.0         300.0           9.0          15.5      S355JR         355.0         490.0           10.9            900.0           1000.0            500.0
3                       121.0           166.04                          0             0.0                          0             0.0  110    0  220  565  20  215.0  35  40.0  90.0   90.0  90.0  111.4530  103.5470   0   0   0   0    0    0    0  10   10    0    18  JBE6003  HEA200  HEA280         MOE  M16           NO  AISC-360-05/10  European              -  AISC-360-05/10        HE      190.0       200.0         6.5        10.0          HE        270.0         280.0           8.0          13.0      S355JR         355.0         490.0           10.9            900.0           1000.0            500.0
4                       121.0           287.86                          0             0.0                          0             0.0  120    0  240  600  25  210.0  40  40.0  92.0  126.0  92.0  104.1436  105.8564   0   0   0   0    0    0    0  12   10    0    22  JBE6004  HEA240  HEA300         MOE  M20           NO  AISC-360-05/10  European              -  AISC-360-05/10        HE      230.0       240.0         7.5        12.0          HE        290.0         300.0           8.5          14.0      S355JR         355.0         490.0           10.9            900.0           1000.0            500.0

## DISTANCIAS

In [499]:
# de int a float
int_a_float = ["p6", "p7", "p8", "p9", "p10", "p11", "p12"]

for col in int_a_float:
    df_final3[col] = df_final3[col].astype(float)

## FILAS DE TORNILLOS POR ZONA
Todas las zonas se definen con **las mismas caras de las alas** (antes se mezclaban cara exterior, cara interior y eje del ala):

| zona | condición (posición `y` de la fila, mm desde el borde superior) |
|---|---|
| sobre el ala | `y < e + d` (siempre 1 fila: la de la cota `e`, a distancia `d` del ala) |
| **alma** | entre las caras **interiores** de las alas: `e+d+tf ≤ y ≤ e+d+h−tf` |
| **cantonera** | bajo la cara exterior del ala inferior (`y > e+d+h`), **sin contar la última fila** |
| bajo el último ala | la última fila (siempre 1) |

Una fila dentro del espesor de un ala sería una colisión: se detecta y se avisa.

In [500]:
import warnings

p_cols = [f"p{i}" for i in range(1, 13)]
df[p_cols] = (
    df[p_cols].fillna(0.0).astype(float)
)  # p ausente = fila inactiva (esto sí es legítimo)

# Validación: antes los nulos se rellenaban con 0 en silencio y eso corrompía la geometría.
req = ["e", "d", "g", "BEAM_d_mm", "BEAM_tf_mm", "BEAM_tw_mm"]
bad_req = df[req].isna().any(axis=1) | (df[req] <= 0).any(axis=1)
assert not bad_req.any(), (
    f"{int(bad_req.sum())} filas con e/d/g/dimensiones de viga ausentes o <= 0"
)
assert not (np.diff((df[p_cols] > 0).values.astype(int), axis=1) > 0).any(), (
    "filas con p activas no consecutivas"
)


def calcular_geometria(df, tol=0.5):
    """Posiciones de las filas (mm) y su zona. Todo en arrays alineados con las filas de df."""
    e = df["e"].values.astype(float)
    active = (df[p_cols] > 0).values
    exists = np.column_stack(
        [np.ones(len(df), bool), active]
    )  # fila 1 (cota e) + p activas
    y = np.column_stack([e, e[:, None] + df[p_cols].cumsum(axis=1).values])
    y = np.where(exists, y, np.nan)
    top_out = e + df["d"].values  # cara exterior del ala superior
    top_in = top_out + df["BEAM_tf_mm"].values  # cara interior del ala superior
    bot_out = top_out + df["BEAM_d_mm"].values  # cara exterior del ala inferior
    bot_in = bot_out - df["BEAM_tf_mm"].values  # cara interior del ala inferior
    col = lambda v: v[:, None]
    sobre = exists & (y < col(top_out) - tol)
    alma = exists & (y >= col(top_in) - tol) & (y <= col(bot_in) + tol)
    en_ala = exists & ~sobre & ~alma & (y <= col(bot_out) + tol)
    bajo = exists & (y > col(bot_out) + tol)
    y_ult = np.nanmax(y, axis=1)
    return dict(
        y=y,
        exists=exists,
        D=y_ult,
        top_out=top_out,
        top_in=top_in,
        bot_out=bot_out,
        bot_in=bot_in,
        sobre=sobre,
        alma=alma,
        en_ala=en_ala,
        bajo=bajo,
        y_ult=y_ult,
        n_filas=exists.sum(axis=1),
        n_alma=alma.sum(axis=1),
        n_cant=np.maximum(bajo.sum(axis=1) - 1, 0),
    )


geo = calcular_geometria(df)
has_Lh = (df["Lh"].fillna(0) > 0).values
checks = pd.DataFrame(
    {
        "exactamente 1 fila sobre el ala superior": geo["sobre"].sum(axis=1) == 1,
        "ninguna fila dentro del espesor de un ala": geo["en_ala"].sum(axis=1) == 0,
        "filas = alma + cantonera + 2": geo["n_alma"] + geo["n_cant"] + 2
        == geo["n_filas"],
        "hay filas de cantonera  <=>  Lh > 0": (geo["n_cant"] > 0) == has_Lh,
    },
    index=df.index,
)
print("Filas que incumplen cada comprobación:")
print((~checks).sum().to_string())
inconsistentes = ~checks.all(axis=1)
print(f"\nUniones incoherentes: {int(inconsistentes.sum())} de {len(df)}")
df.loc[
    inconsistentes, ["UNICODE", "e", "d", "Lh", "BEAM_d_mm", "BEAM_tf_mm"] + p_cols[:6]
]

Filas que incumplen cada comprobación:
exactamente 1 fila sobre el ala superior      0
ninguna fila dentro del espesor de un ala     7
filas = alma + cantonera + 2                  7
hay filas de cantonera  <=>  Lh > 0          30

Uniones incoherentes: 36 de 4722

      UNICODE   e          d            Lh  BEAM_d_mm  BEAM_tf_mm     p1     p2     p3     p4     p5     p6
2999  MLE4016  50  31.000000  3.336000e+02      314.0        11.1  120.0   55.0  170.0  185.0   55.0   90.0
3000  MLE4017  50  31.000000  3.336000e+02      314.0        11.1  120.0   55.0  170.0  185.0   55.0   90.0
3001  MLE4018  50  31.000000  3.336000e+02      314.0        11.1  110.0   55.0  170.0  185.0   55.0   90.0
3002  MLE4019  50  31.000000  3.336000e+02      314.0        11.1  110.0   55.0  170.0  185.0   55.0   90.0
3031  MLE4048  55  32.500000  4.864000e+02      410.0        14.3  115.0   55.0  260.0  265.0   55.0   90.0
3032  MLE4049  55  32.500000  4.864000e+02      410.0        14.3  115.0   55.0  260.0  265.0   55.0   90.0
3071  MLE4088  55  43.500000 -2.146826e+09      689.0        20.6  105.0   75.0  240.0  240.0  110.0  175.0
3072  MLE4089  55  43.500000 -2.146826e+09      689.0        20.6  105.0   75.0  240.0  240.0  110.0  175.0
3073  MLE4090  55  43.500000 -2.146826e+09      689.0        20.6  105.0   75.0  240.0  240.0  110.0  175.0
3074  MLE4091  55  43.500000 -2.146826e+09      689.0        20.6  105.0   75.0  240.0  240.0  110.0  175.0
3075  MLE4092  65  43.500000 -2.146826e+09      689.0        20.6  105.0   75.0  240.0  240.0  110.0  175.0
3076  MLE4093  65  43.500000 -2.146826e+09      689.0        20.6  105.0   75.0  240.0  240.0  110.0  175.0
3105  MLE4122  65  43.883377  1.656000e+02      311.0        15.9   90.0  255.0  110.0    0.0    0.0    0.0
3583  MLE6375  40  37.500000  7.500000e+01      190.0        10.0   85.0   95.0   85.0    0.0    0.0    0.0
3584  MLE6376  40  39.000000  7.200000e+01      160.0        13.0   89.0   60.0   85.0    0.0    0.0    0.0
3585  MLE6377  40  55.000000  4.000000e+01      300.0        19.0  120.0  155.0  125.0    0.0    0.0    0.0
3586  MLE6378  40  45.000000  6.000000e+01      220.0        16.0  105.0  100.0  105.0    0.0    0.0    0.0
3587  MLE6379  40  45.000000  6.000000e+01      220.0        16.0  105.0  100.0  105.0    0.0    0.0    0.0
3588  MLE6380  40  45.000000  6.000000e+01      440.0        21.0  110.0  155.0  155.0  110.0    0.0    0.0
3589  MLE6381  35  37.000000  6.600000e+01      171.0         9.5   85.0   75.0   85.0    0.0    0.0    0.0
3590  MLE6382  40  45.000000  6.000000e+01      270.0        13.0  100.0  140.0  115.0    0.0    0.0    0.0
3591  MLE6383  35  35.000000  7.000000e+01      180.0         8.0   75.0  100.0   75.0    0.0    0.0    0.0
3592  MLE6384  35  35.000000  7.000000e+01      180.0         8.0   75.0  100.0   75.0    0.0    0.0    0.0
3593  MLE6385  35  47.500000  4.500000e+01      250.0        12.5  105.0  135.0  105.0    0.0    0.0    0.0
3594  MLE6386  40  40.000000  7.000000e+01      230.0        12.0   90.0   65.0   65.0   90.0    0.0    0.0
3595  MLE6387  40  45.000000  6.000000e+01      290.0        14.0  105.0   85.0   85.0  105.0    0.0    0.0
3598  MLE6390  40  37.500000  7.500000e+01      190.0        10.0   85.0   95.0   85.0    0.0    0.0    0.0
3600  MLE6392  40  37.500000  7.500000e+01      190.0        10.0   85.0   95.0   85.0    0.0    0.0    0.0
3601  MLE6393  35  35.000000  7.000000e+01      180.0         8.0   75.0  100.0   75.0    0.0    0.0    0.0
3602  MLE6394  40  40.000000  7.000000e+01      180.0        14.0   90.0   75.0   95.0    0.0    0.0    0.0
3605  MLE6397  40  40.000000  7.000000e+01      230.0        12.0   90.0   65.0   65.0   90.0    0.0    0.0
3606  MLE6398  40  40.000000  7.000000e+01      230.0        12.0   90.0   65.0   65.0   90.0    0.0    0.0
3610  MLE6402  40  37.500000  7.500000e+01      190.0        10.0   85.0   95.0   85.0    0.0    0.0    0.0
3614  MLE6406  40  40.000000  7.000000e+01      230.0        12.0   90.0   65.0   65.0   90.0    0.0    0.0
3616  MLE6408  40  40.000000  7.000000e+01      230.0        12.0   90.0   65.0   65.0   90.0    0.0    0.0
3620  MLE6412  40  45.000000  6.000000e+01      270.0        13.0  100.0  140.0  115.0    0.0    0.0    0.0

In [501]:
df.loc[inconsistentes, ["UNICODE"]]

      UNICODE
2999  MLE4016
3000  MLE4017
3001  MLE4018
3002  MLE4019
3031  MLE4048
3032  MLE4049
3071  MLE4088
3072  MLE4089
3073  MLE4090
3074  MLE4091
3075  MLE4092
3076  MLE4093
3105  MLE4122
3583  MLE6375
3584  MLE6376
3585  MLE6377
3586  MLE6378
3587  MLE6379
3588  MLE6380
3589  MLE6381
3590  MLE6382
3591  MLE6383
3592  MLE6384
3593  MLE6385
3594  MLE6386
3595  MLE6387
3598  MLE6390
3600  MLE6392
3601  MLE6393
3602  MLE6394
3605  MLE6397
3606  MLE6398
3610  MLE6402
3614  MLE6406
3616  MLE6408
3620  MLE6412

In [502]:
# Las uniones incoherentes (p. ej. Lh > 0 sin filas de cantonera, o una fila dentro del ala) contradicen la
# geometría y confunden al modelo. Pon False para conservarlas y revisarlas a mano.
DROP_INCOHERENTES = True
if DROP_INCOHERENTES and inconsistentes.any():
    print(f"Se eliminan {int(inconsistentes.sum())} uniones incoherentes")
    df = df[~inconsistentes.values].reset_index(drop=True)
    geo = calcular_geometria(df)

df["n_filas_alma"] = geo["n_alma"]  # filas en el alma de la viga
df["n_filas_cantonera"] = geo["n_cant"]  # filas en la cantonera (0 si no hay Lh)
D_total = geo["D"]  # posición de la última fila (mm)

# Posición de cada fila como fracción de D_total (0 = fila inexistente). Vuelta a mm: D = e / row_1_pct.
row_pct = pd.DataFrame(
    np.where(geo["exists"], geo["y"] / D_total[:, None], 0.0),
    index=df.index,
    columns=[f"row_{i}_pct" for i in range(1, 14)],
)
df = pd.concat([df, row_pct], axis=1)
print(df[["n_filas_alma", "n_filas_cantonera"]].value_counts().sort_index().head(12))

Se eliminan 36 uniones incoherentes
n_filas_alma  n_filas_cantonera
1             0                      41
              1                       6
2             0                    1300
              1                     563
              2                     864
3             0                     722
              1                       1
              2                     600
              3                     253
4             0                      74
              3                     133
              4                      37
Name: count, dtype: int64

## HUECO DE TRABAJO DE LOS TORNILLOS
No hay tabla de espacio libre para la herramienta, así que **no se impone una regla externa**: se mide lo que ya cumplen los diseños y se deja que el modelo coloque los tornillos.
Hueco = distancia del eje de la fila de tornillos a la cara de la pieza más próxima (mm); su cociente por el diámetro `db` es adimensional.

| columna | distancia medida |
|---|---|
| `d` (ya existente) | fila 1 ↔ cara exterior del ala superior |
| `hueco_alma_sup` | primera fila del alma ↔ cara interior del ala superior |
| `hueco_alma_inf` | última fila del alma ↔ cara interior del ala inferior |
| `hueco_cant_sup` | primera fila de la cantonera ↔ cara exterior del ala inferior (0 si no hay cantonera) |
| `hueco_alma_lat` | `(g − tw)/2`: eje del tornillo ↔ cara del alma, en horizontal |
| `hueco_min_ratio` | mínimo de los huecos a las alas/alma (incluida `d`) dividido por `db` |
| `paso_min_ratio` | menor separación entre filas consecutivas dividida por `db` |

No se calculan huecos que dependan de `Lh` (último ala de la cantonera): en ~19 % de las uniones con cantonera la última fila no queda donde `Lh` la situaría, así que esa medida no es fiable.
Los umbrales son **solo informativos** (se miden en los datos, no vienen de una norma); solo se descartan las uniones sin hueco físico (`< 0.5·db`).

In [503]:
HUECO_MIN_RATIO = 1.5  # solo para informar: (distancia eje-cara) / db que cumple la inmensa mayoría de los diseños
HUECO_DESCARTAR_BAJO = 0.5  # uniones con algún hueco < 0.5*db no tienen sitio físico para la herramienta: se descartan

db = df["Bolt"].astype(str).str.extract(r"(\d+)")[0].astype(float).values
y = geo["y"]
es_ultima = y >= geo["y_ult"][:, None] - 1e-9
cant = geo["bajo"] & ~es_ultima
tiene_cant = cant.any(axis=1)


def borde(zona, cual):
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        ys = np.where(zona, y, np.nan)
        return np.nanmin(ys, axis=1) if cual == "primera" else np.nanmax(ys, axis=1)


df["hueco_alma_sup"] = borde(geo["alma"], "primera") - geo["top_in"]
df["hueco_alma_inf"] = geo["bot_in"] - borde(geo["alma"], "ultima")
df["hueco_cant_sup"] = np.where(
    tiene_cant, borde(cant, "primera") - geo["bot_out"], 0.0
)
df["hueco_alma_lat"] = (df["g"] - df["BEAM_tw_mm"]) / 2.0

nombres = ["d", "hueco_alma_sup", "hueco_alma_inf", "hueco_cant_sup", "hueco_alma_lat"]
gaps = df[nombres].to_numpy(float).copy()
gaps[~tiene_cant, 3] = np.nan  # sin cantonera ese hueco no existe
df["hueco_min_ratio"] = np.nanmin(gaps, axis=1) / db
with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    df["paso_min_ratio"] = (
        np.nanmin(np.diff(y, axis=1), axis=1) / db
    )  # separación mínima entre filas consecutivas
quien = pd.Series(
    np.array(nombres)[np.nanargmin(gaps / db[:, None], axis=1)], index=df.index
)

print("Hueco / db por tipo (cuantiles):")
print(
    (pd.DataFrame(gaps / db[:, None], columns=nombres).quantile([0.01, 0.05, 0.5]))
    .round(2)
    .T.to_string()
)
bajo_min = df["hueco_min_ratio"] < HUECO_MIN_RATIO
print(
    f"\nUniones con algún hueco < {HUECO_MIN_RATIO}*db: {int(bajo_min.sum())} ({bajo_min.mean():.1%}) | < 0 (colisión): {int((df['hueco_min_ratio'] < 0).sum())}"
)
print("Dónde está el hueco mínimo en esas uniones:")
print(quien[bajo_min].value_counts().to_string())
print(
    f"\nPaso mínimo entre filas / db: cuantiles 1%, 5%, 50% = {df['paso_min_ratio'].quantile([0.01, 0.05, 0.5]).round(2).tolist()}  (mínimo {df['paso_min_ratio'].min():.2f})"
)

Hueco / db por tipo (cuantiles):
                0.01  0.05  0.50
d               1.67  1.73  2.00
hueco_alma_sup  1.34  1.75  2.10
hueco_alma_inf  1.40  1.87  2.20
hueco_cant_sup  1.25  1.67  2.96
hueco_alma_lat  1.85  2.06  2.40

Uniones con algún hueco < 1.5*db: 165 (3.5%) | < 0 (colisión): 0
Dónde está el hueco mínimo en esas uniones:
hueco_alma_sup    69
hueco_alma_inf    49
hueco_cant_sup    47

Paso mínimo entre filas / db: cuantiles 1%, 5%, 50% = [2.73, 2.75, 3.75]  (mínimo 2.36)

In [504]:
descartar = df["hueco_min_ratio"] < HUECO_DESCARTAR_BAJO
print(
    f"Se eliminan {int(descartar.sum())} uniones sin hueco físico para la herramienta (< {HUECO_DESCARTAR_BAJO}*db)"
)
df = df[~descartar].reset_index(drop=True)
df.shape

Se eliminan 21 uniones sin hueco físico para la herramienta (< 0.5*db)

(4665, 78)

## POSICIÓN DE LAS ALAS, CLASIFICACIÓN DE TORNILLOS Y `Bolt` SIN "M"
Se calcula tras eliminar las uniones sin hueco (se recalcula `geo`, porque ya no coincide con las filas de `df`).

**Distancia de las alas** (borde superior de la chapa → centro del ala, en % de `D`, igual que `row_i_pct`): `ala_sup_pct`, `ala_inf_pct` y `ala_cant_pct` (0 si no hay cantonera).

**Posición de cada tornillo** (`bolt_i_pos`, de arriba a abajo; `ninguno` si la fila no existe):

| etiqueta | significado |
|---|---|
| `superior` / `inferior` | primera fila (sobre el ala superior) / última fila de la chapa |
| `viga_*` | filas del alma de la viga |
| `cantonera_*` | filas de la cantonera |

Sufijos dentro de `viga_` y `cantonera_`: `primero`, `ultimo`, `centro` (zona de 1 fila o central de una zona impar), `centro_sup` / `centro_inf` (las 2 centrales de una zona par), `intermedio_sup` / `intermedio_inf` (el resto).

In [505]:
# Tras el paso anterior se eliminaron uniones: se recalcula la geometría para que sus filas coincidan con df.
geo = calcular_geometria(df)
D_total = geo["D"]
tf = df["BEAM_tf_mm"].values
Lh_mm = df["Lh"].fillna(0).values.astype(float)
tiene_cant = geo["n_cant"] > 0
es_ultima = geo["y"] >= D_total[:, None] - 1e-9
cant = geo["bajo"] & ~es_ultima

# --- 1) Distancia borde superior de la chapa -> centro de cada ala, en % de D (igual que row_i_pct) ---
df["ala_sup_pct"] = (geo["top_out"] + tf / 2) / D_total
df["ala_inf_pct"] = (geo["bot_out"] - tf / 2) / D_total
# SUPUESTO: Lh va de la cara exterior del ala inferior de la viga a la cara exterior del ala de la cantonera,
# y ese ala tiene el espesor del ala de la viga. Si no es así, solo hay que cambiar la línea siguiente.
df["ala_cant_pct"] = np.where(
    tiene_cant, (geo["bot_out"] + Lh_mm - tf / 2) / D_total, 0.0
)

# Comprobación: el centro del ala de la cantonera debe quedar entre la última fila de la cantonera y la última fila.
with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    y_ult_cant = np.nanmax(np.where(cant, geo["y"], np.nan), axis=1)
c_mm = df["ala_cant_pct"].values * D_total
ok = (c_mm > y_ult_cant) & (c_mm < D_total)
print(
    f"Ala de cantonera entre su última fila y la final: {ok[tiene_cant].mean():.1%} de {int(tiene_cant.sum())} uniones con cantonera"
)
print(
    df[["ala_sup_pct", "ala_inf_pct", "ala_cant_pct"]].describe().round(3).T.to_string()
)


# --- 2) Clasificación de cada tornillo según su posición ---
def etiquetas_zona(n):
    # etiquetas de las n filas de una zona (viga o cantonera), de arriba a abajo
    if n == 1:
        return ["centro"]
    out = []
    for k in range(n):
        if k == 0:
            out.append("primero")
        elif k == n - 1:
            out.append("ultimo")
        elif n % 2 == 1 and k == n // 2:
            out.append("centro")
        elif n % 2 == 0 and k == n // 2 - 1:
            out.append("centro_sup")
        elif n % 2 == 0 and k == n // 2:
            out.append("centro_inf")
        else:
            out.append("intermedio_sup" if k < n / 2 else "intermedio_inf")
    return out


N_ROWS = 13
pos = np.full((len(df), N_ROWS), "ninguno", dtype=object)
n_alma, n_cant = geo["n_alma"], geo["n_cant"]
for a, c in set(zip(n_alma, n_cant)):
    # orden vertical: 1 fila sobre el ala, filas del alma, filas de la cantonera, fila final
    seq = (
        ["superior"]
        + ["viga_" + l for l in etiquetas_zona(a)]
        + ["cantonera_" + l for l in etiquetas_zona(c)]
        + ["inferior"]
    )
    assert len(seq) == 2 + a + c <= N_ROWS
    pos[(n_alma == a) & (n_cant == c), : len(seq)] = seq

pos_cols = [f"bolt_{i}_pos" for i in range(1, N_ROWS + 1)]
df = pd.concat([df, pd.DataFrame(pos, columns=pos_cols, index=df.index)], axis=1)
print(pd.Series(pos[pos != "ninguno"]).value_counts().to_string())


# --- 3) Bolt sin la "M" (M20 -> 20, diámetro en mm). Si algún valor no tiene número, falla aquí. ---
df["Bolt"] = df["Bolt"].astype(str).str.extract(r"(\d+)")[0].astype(int)
print(df["Bolt"].value_counts().sort_index().to_string())

Ala de cantonera entre su última fila y la final: 95.2% de 2503 uniones con cantonera
               count   mean    std    min    25%    50%    75%    max
ala_sup_pct   4665.0  0.194  0.062  0.071  0.151  0.188  0.242  0.336
ala_inf_pct   4665.0  0.705  0.151  0.493  0.564  0.582  0.864  0.974
ala_cant_pct  4665.0  0.494  0.461  0.000  0.000  0.888  0.918  1.466
superior                    4665
inferior                    4665
viga_primero                4618
viga_ultimo                 4618
cantonera_primero           1933
cantonera_ultimo            1933
viga_centro                 1695
cantonera_centro             963
viga_centro_sup              251
viga_centro_inf              251
viga_intermedio_sup           92
viga_intermedio_inf           92
cantonera_centro_sup          91
cantonera_centro_inf          91
cantonera_intermedio_sup      13
cantonera_intermedio_inf      13
Bolt
16     115
20    1376
22      44
24    1124
27     873
30    1126
36       7

## RATIOS ESTRUCTURALES Y CARGAS

In [506]:
# Ratios adimensionales viga/columna (las dimensiones absolutas BEAM_*_mm / COLUMN_*_mm se descartan en COLUMNAS FINALES).
# NO se añaden ratios con tp, Bp, e o d: son targets y filtrarían la respuesta.
df["r_d_beam_col"] = df["BEAM_d_mm"] / df["COLUMN_d_mm"]
df["r_bf_beam_col"] = df["BEAM_bf_mm"] / df["COLUMN_bf_mm"]
df["r_tw_beam_col"] = df["BEAM_tw_mm"] / df["COLUMN_tw_mm"]
df["r_tf_beam_col"] = df["BEAM_tf_mm"] / df["COLUMN_tf_mm"]

# Cargas: se conservan solo los porcentajes (0-1+); los valores absolutos se descartan.
df["ratio_moment"] = df["Capacity_Moment_Percentage"] / 100.0
df["ratio_shear"] = df["Capacity_Shear_Percentage"] / 100.0
df["ratio_axial"] = df["Capacity_Axial_Percentage"] / 100.0

# COLUMNAS FINALES
Se conservan solo las que usa el modelo o sirven para validarlo. Eliminadas y por qué:

| eliminadas | motivo |
|---|---|
| `p1..p12` | sustituidas por `row_i_pct` (+ `e` en mm) |
| `rows_in_top_extension`, `rows_in_bottom_extension`, `num_bolt_rows` | constantes (siempre 1) o redundantes con `n_filas_alma + n_filas_cantonera + 2` |
| `BEAM_*_mm`, `COLUMN_*_mm` | medidas absolutas de perfil: solo sirven para calcular ratios, posiciones y huecos; no entran al modelo |
| `bolt_i_label` (×13) | sustituidas por `bolt_i_pos` (clasificación por zona, ver arriba) |
| `Lp` | largo de la chapa: lo calcula Excel a partir de las filas (era un target encubierto) |
| `DrawingCode`, `Source`, `Normativas`, `National_Annex` | metadatos: no están disponibles al predecir o duplican `standard` |
| `fy/fu_acero`, `fy/fu/fv_tornillo` | función exacta de `grado_acero` y `clase_tornillo` |
| `Capacity_*` (absolutas y %) | sustituidas por `ratio_moment/shear/axial` |
| `AceroEstructural`, `EstandarTornillos` | duplicados de `grado_acero`, `clase_tornillo` |

In [508]:
ID = [
    "UNICODE",
    "BEAM",
    "COLUMN",
]  # identificadores (NO son entradas): split por pares, trazabilidad
ENTRADAS_CAT = ["BEAM_type", "COLUMN_type", "grado_acero", "clase_tornillo"]
# Las medidas absolutas BEAM_*_mm / COLUMN_*_mm se usan arriba para ratios y posiciones; aquí se descartan.
ENTRADAS_NUM = [
    "r_d_beam_col",
    "r_bf_beam_col",
    "r_tw_beam_col",
    "r_tf_beam_col",
    "ratio_moment",
    "ratio_shear",
    "ratio_axial",
]
TARGETS_CLS = ["standard", "Bolt", "SlipCritical", "n_filas_alma", "n_filas_cantonera"]
TARGETS_MM = ["g", "e", "d", "Bp", "tp", "tws", "ts", "tbs", "tst"]
TARGETS_POS = [f"row_{i}_pct" for i in range(1, 14)]
TARGETS_POS_ALAS = [
    "ala_sup_pct",
    "ala_inf_pct",
    "ala_cant_pct",
]  # centro de las alas, en % de D
TARGETS_POS_LABEL = [
    f"bolt_{i}_pos" for i in range(1, 14)
]  # clasificación de cada tornillo
DERIVADAS_Y_AUX = [
    "Hole",
    "Lh",
    "hueco_alma_sup",
    "hueco_alma_inf",
    "hueco_cant_sup",
    "hueco_alma_lat",
    "hueco_min_ratio",
    "paso_min_ratio",
]  # no son entradas; Hole se deriva de Bolt; Lh = largo de la cantonera (0 si no hay)
FINAL = (
    ID
    + ENTRADAS_CAT
    + ENTRADAS_NUM
    + TARGETS_CLS
    + TARGETS_MM
    + TARGETS_POS
    + TARGETS_POS_ALAS
    + TARGETS_POS_LABEL
    + DERIVADAS_Y_AUX
    + ["BEAM_d_mm"]
)
falta = [c for c in FINAL if c not in df.columns]
assert not falta, f"columnas finales ausentes: {falta}"
print("Eliminadas:", [c for c in df.columns if c not in FINAL])
df = df[FINAL].copy()

# Sin imputación silenciosa: si queda algún nulo en las columnas finales es un error de datos.
nulos = df.isna().sum()
assert nulos.sum() == 0, nulos[nulos > 0]
assert (df[["d", "e", "g"]] > 0).all().all()
print(df.shape)
df.head()

Eliminadas: ['Capacity_Moment_Percentage', 'Capacity_Moment', 'Capacity_Shear_Percentage', 'Capacity_Shear', 'Capacity_Axial_Percentage', 'Capacity_Axial', 'Lp', 'p1', 'p2', 'p3', 'p4', 'p5', 'p6', 'p7', 'p8', 'p9', 'p10', 'p11', 'p12', 'DrawingCode', 'Normativas', 'Source', 'National_Annex', 'BEAM_bf_mm', 'BEAM_tw_mm', 'BEAM_tf_mm', 'COLUMN_d_mm', 'COLUMN_bf_mm', 'COLUMN_tw_mm', 'COLUMN_tf_mm', 'fy_acero_mpa', 'fu_acero_mpa', 'fy_tornillo_mpa', 'fu_tornillo_mpa', 'fv_tornillo_mpa']
(4665, 66)

   UNICODE    BEAM  COLUMN BEAM_type COLUMN_type grado_acero clase_tornillo  r_d_beam_col  r_bf_beam_col  r_tw_beam_col  r_tf_beam_col  ratio_moment  ratio_shear  ratio_axial        standard  Bolt SlipCritical  n_filas_alma  n_filas_cantonera    g   e     d   Bp  tp  tws  ts  tbs  tst  row_1_pct  row_2_pct  row_3_pct  row_4_pct  row_5_pct  row_6_pct  row_7_pct  row_8_pct  row_9_pct  row_10_pct  row_11_pct  row_12_pct  row_13_pct  ala_sup_pct  ala_inf_pct  ala_cant_pct bolt_1_pos    bolt_2_pos   bolt_3_pos         bolt_4_pos        bolt_5_pos bolt_6_pos bolt_7_pos bolt_8_pos bolt_9_pos bolt_10_pos bolt_11_pos bolt_12_pos bolt_13_pos  Hole     Lh  hueco_alma_sup  hueco_alma_inf  hueco_cant_sup  hueco_alma_lat  hueco_min_ratio  paso_min_ratio  BEAM_d_mm
0  JBE6000  IPE300  HEA260       IPE          HE      S355JR           10.9      1.200000       0.576923       0.946667       0.856000          1.21          0.0          0.0  AISC-360-05/10    20           NO             2                  2  110  40  40.0  190  20    0  12   10    0   0.060150   0.196541   0.495188   0.631579   0.843075        1.0        0.0        0.0        0.0         0.0         0.0         0.0         0.0     0.128346     0.563383      0.931805   superior  viga_primero  viga_ultimo  cantonera_primero  cantonera_ultimo   inferior    ninguno    ninguno    ninguno     ninguno     ninguno     ninguno     ninguno    22  245.0            40.0            40.0            40.0           51.45           2.0000          4.5350      300.0
1  JBE6001  HEA180  HEA300        HE          HE      S355JR           10.9      0.589655       0.600000       0.705882       0.678571          1.21          0.0          0.0  AISC-360-05/10    16           NO             3                  1  110  35  40.0  200  20    0  10   10    0   0.083433   0.296782   0.404052   0.523242   0.630513        1.0        0.0        0.0        0.0         0.0         0.0         0.0         0.0     0.190107     0.575089      0.896901   superior  viga_primero  viga_centro        viga_ultimo  cantonera_centro   inferior    ninguno    ninguno    ninguno     ninguno     ninguno     ninguno     ninguno    18  135.0            40.0            17.0            18.5           52.00           1.0625          2.8125      171.0
2  JBE6002  IPE300  HEA320       IPE          HE      S355JR           10.9      0.967742       0.500000       0.788889       0.690323          1.21          0.0          0.0  AISC-360-05/10    20           NO             2                  2  110  40  40.0  190  20    0  12   10    0   0.060150   0.196541   0.495188   0.631579   0.843075        1.0        0.0        0.0        0.0         0.0         0.0         0.0         0.0     0.128346     0.563383      0.931805   superior  viga_primero  viga_ultimo  cantonera_primero  cantonera_ultimo   inferior    ninguno    ninguno    ninguno     ninguno     ninguno     ninguno     ninguno    22  245.0            40.0            40.0            40.0           51.45           2.0000          4.5350      300.0
3  JBE6003  HEA200  HEA280        HE          HE      S355JR           10.9      0.703704       0.714286       0.812500       0.769231          1.21          0.0          0.0  AISC-360-05/10    16           NO             2                  2  110  35  40.0  220  20    0  10   10    0   0.067308   0.240385   0.413462   0.586538   0.800871        1.0        0.0        0.0        0.0         0.0         0.0         0.0         0.0     0.153846     0.500000      0.913462   superior  viga_primero  viga_ultimo  cantonera_primero  cantonera_ultimo   inferior    ninguno    ninguno    ninguno     ninguno     ninguno     ninguno     ninguno    18  215.0            40.0            40.0            40.0           51.75           2.5000          5.6250      190.0
4  JBE6004  HEA240  HEA300        HE          HE      S355JR           10.9      0.793103       0.800000       0.882353       0.857143          1.21          0.0          0.0  AISC-360-05/10    20           NO             2                  2  120  40  40.0  240  25    0  12   10    0   0.071429   0.235714   0.460714   0.625000   0.810971        1.0        0.0        0.0        0.0         0.0         0.0         0.0         0.0     0.153571     0.542857      0.917857   superior  viga_primero  viga_ultimo  cantonera_primero  cantonera_ultimo   inferior    ninguno    ninguno    ninguno     ninguno     ninguno     ninguno     ninguno    22  210.0            40.0            40.0            40.0           56.25           2.0000          4.6000      230.0

# GUARDAR

In [509]:
df.to_parquet(
    Path().cwd().parent / "production" / "server" / "data" / "global_data.parquet",
    index=False,
)