In [103]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path

In [104]:
pd.set_option('display.max_columns', None)  # Show all columns
pd.set_option('display.width', 1000)

# PATHS

In [105]:
dir = Path.cwd().parent / "V4" / "data"
data_excel_path = dir / "CONEXIONES_MOMENTO_ATORNILLADAS_CHAPA_FRONTAL.xlsx"
tekla_excel_path = dir / "Prontuario Tekla19.xlsx"

# CARGA DE DATOS

In [106]:
data = pd.read_excel(data_excel_path, sheet_name="Sheet1")

In [107]:
data.head(20)

    Unicode    BEAM  COLUMN  Capacity_Moment_Percentage  Capacity_Moment  Capacity_Shear_Percentage  Capacity_Shear  Capacity_Axial_Percentage  Capacity_Axial  Pr_Porcen DrawingCode    g  tws  Lws  Bws   Bp   Lp  tp     Lh   e     d  pfo     p1     p2     p3         p4        p5  p6  p7  p8  p9  p10  p11  p12  ts  tbs  tst   thw   thf  w1  w2 w3 w4 w5 w6 Bolt  Hole SlipCritical      Normativas AceroEstructural ElectrodoSoldadura EstandarTornillos  Ordinary_Moment_Frames Calculation_Tool    Source Designation  rib_thk  Representation_Angle  BoltConnectionTypeSelection National_Annex   p0  tso  Lst  SpecialMomentFrames MzEd_PanelZone Vgra Havg  Yieldmethod Acero_Estructural_Perfil
0   JBE6000  IPE300  HEA260                       121.0           242.94                          0             0.0                          0             0.0         50         MOE  110    0    0    0  190  705  20  245.0  40  40.0  NaN   90.7  198.6   90.7  140.64470  104.3553   0   0   0   0    0    0    0  12   10    0  10.0  10.0   0   6  0  0  6  6  M20    22           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19        0                     0                            0              -  0.0  0.0  0.0                  0.0              -    -    -          1.0                   S355JR
1   JBE6001  HEA180  HEA300                       121.0           125.60                          0             0.0                          0             0.0         50         MOE  110    0    0    0  200  466  20  135.0  35  40.0  NaN   89.5   45.0   50.0   45.00000  155.0000   0   0   0   0    0    0    0  10   10    0  10.0  10.0   0   5  0  0  6  6  M16    18           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19        0                     0                            0              -  0.0  0.0  0.0                  0.0            NaN  NaN  NaN          NaN                      NaN
2   JBE6002  IPE300  HEA320                       121.0           242.94                          0             0.0                          0             0.0         50         MOE  110    0    0    0  190  705  20  245.0  40  40.0  NaN   90.7  198.6   90.7  140.64470  104.3553   0   0   0   0    0    0    0  12   10    0  10.0  10.0   0   6  0  0  6  6  M20    22           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19        0                     0                            0              -  0.0  0.0  0.0                  0.0            NaN  NaN  NaN          NaN                      NaN
3   JBE6003  HEA200  HEA280                       121.0           166.04                          0             0.0                          0             0.0         50         MOE  110    0    0    0  220  565  20  215.0  35  40.0  NaN   90.0   90.0   90.0  111.45300  103.5470   0   0   0   0    0    0    0  10   10    0  10.0  10.0   0   5  0  0  6  6  M16    18           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19        0                     0                            0              -  0.0  0.0  0.0                  0.0            NaN  NaN  NaN          NaN                      NaN
4   JBE6004  HEA240  HEA300                       121.0           287.86                          0             0.0                          0             0.0         50         MOE  120    0    0    0  240  600  25  210.0  40  40.0  NaN   92.0  126.0   92.0  104.14360  105.8564   0   0   0   0    0    0    0  12   10    0  10.0  10.0   0   6  0  0  7  7  M20    22           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19        0                     0                            0              -  0.0  0.0  0.0                  0.0            NaN  NaN  NaN          NaN                      NaN
5   JBE6005  IPE330  HEA320                       121.0           310.94                          0             0.0                          0             0.0         50         MOE  110    0    0    0  190  780  20  250.0  40  50.0  NaN  111.5  207.0  111.5  121.72090  128.2791   0   0   0   0    0    0    0  12   10    0  10.0  10.0   0   6  0  0  6  6  M20    22           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19        0                     0                            0              -  0.0  0.0  0.0                  0.0            NaN  NaN  NaN          NaN                      NaN
6   JBE6006  IPE300  HEA240                       121.0           242.94                          0             0.0                          0             0.0         50         MOE  110    0    0    0  190  705  20  245.0  40  40.0  NaN   90.7  198.6   90.7  140.64470  104.3553   0   0   0   0    0    0    0  12   10    0  10.0  10.0   0   6  0  0  6  6  M20    22           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19        0                     0                            0              -  0.0  0.0  0.0                  0.0            NaN  NaN  NaN          NaN                      NaN
7   JBE6007  IPE400  HEA280                       121.0           505.28                          0             0.0                          0             0.0         50         MOE  120    8  890  330  220  890  20  250.0  40  60.0  NaN  133.5  253.0  133.5   96.41154  153.5885   0   0   0   0    0    0    0  15   10    0  10.0  12.0   0   7  0  8  6  6  M22    24           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19        0                     0                            0              -  0.0  0.0  0.0                  0.0            NaN  NaN  NaN          NaN                      NaN
8   JBE6008  IPE360  HEA320                       121.0           393.94                          0             0.0                          0             0.0         50        MOE1  130    0    0    0  240  815  20  215.0  40  60.0  NaN  132.7  214.6  132.7   62.33530  152.6647   0   0   0   0    0    0    0  15   10    0  10.0  12.0   0   6  0  0  6  6  M20    22           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19        0                     0                            0              -  0.0  0.0  0.0                  0.0            NaN  NaN  NaN          NaN                      NaN
9   JBE6009  IPE360  HEA300                       121.0           393.94                          0             0.0                          0             0.0         50         MOE  130    0    0    0  240  815  20  215.0  40  60.0  NaN  132.7  214.6  132.7   62.33530  152.6647   0   0   0   0    0    0    0  15   10    0  10.0  12.0   0   6  0  0  6  6  M20    22           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19        0                     0                            0              -  0.0  0.0  0.0                  0.0            NaN  NaN  NaN          NaN                      NaN
10  JBE6010  IPE300  HEA280                       121.0           242.94                          0             0.0                          0             0.0         50         MOE  110    0    0    0  190  705  20  245.0  40  40.0  NaN   90.7  198.6   90.7  140.64470  104.3553   0   0   0   0    0    0    0  12   10    0  10.0  10.0   0   6  0  0  6  6  M20    22           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19        0                     0                            0              -  0.0  0.0  0.0                  0.0            NaN  NaN  NaN          NaN                      NaN
11  JBE6011  IPE330  HEA240                       121.0           310.94                          0             0.0                          0             0.0         50         MOE  110    0    0    0  190  780  20  250.0  40  50.0  NaN  111.5  207.0  111.5  121.72090  128.2791   0   0   0   0    0    0    0  12   10    0  10.0  10.0   0   6  0  0  6  6  M20    22           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19        0                     0                            0              -  0.0  0.0  0.0                  0.0            NaN  NaN  NaN          NaN                      NaN
12  JBE6012  IPE330  HEA260                       121.0           310.94                          0             0.0                          0             0.0         50         MOE  110    0    0    0  190  780  20  250.0  40  50.0  NaN  111.5  207.0  111.5  121.72090  128.2791   0   0   0   0    0    0    0  12   10    0  10.0  10.0   0   6  0  0  6  6  M20    22           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19        0                     0                            0              -  0.0  0.0  0.0                  0.0            NaN  NaN  NaN          NaN                      NaN
13  JBE6013  IPE330  HEA300                       121.0           310.94                          0             0.0                          0             0.0         50         MOE  110    0    0    0  190  780  20  250.0  40  50.0  NaN  111.5  207.0  111.5  121.72090  128.2791   0   0   0   0    0    0    0  12   10    0  10.0  10.0   0   6  0  0  6  6  M20    22           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19        0                     0                            0              -  0.0  0.0  0.0                  0.0            NaN  NaN  NaN          NaN                      NaN
14  JBE6014  IPE300  HEA300                       121.0           242.94                          0             0.0                          0             0.0         50         MOE  110    0    0    0  190  705  20  245.0  40  40.0  NaN   90.7  198.6   90.7  140.64470  104.3553   0   0   0   0    0    0    0  12   10    0  10.0  10.0   0   6  0  0  6  6  M20    22           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19        0                     0                            0              -  0.0  0.0  0.0                  0.0            NaN  NaN  NaN          NaN                      NaN
15  JBE6015  IPE360  HEA340                       121.0           393.94                          0             0.0                          0             0.0         50         MOE  130    0    0    0  240  815  20  215.0  40  60.0  NaN  132.7  214.6  132.7   62.33530  152.6647   0   0   0   0    0    0    0  15   10    0  10.0  12.0   0   6  0  0  6  6  M20    22           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19        0                     0                            0              -  0.0  0.0  0.0                  0.0            NaN  NaN  NaN          NaN                      NaN
16  JBE6016  IPE360  HEA400                       121.0           393.94                          0             0.0                          0             0.0         50        MOE1  130    0    0    0  240  815  20  215.0  40  60.0  NaN  132.7  214.6  132.7   62.33530  152.6647   0   0   0   0    0    0    0  15   10    0  10.0  12.0   0   6  0  0  6  6  M20    22           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19        0                     0                            0              -  0.0  0.0  0.0                  0.0            NaN  NaN  NaN          NaN                      NaN
17  JBE6017  HEA260  HEA300                       121.0           355.59                          0             0.0                          0             0.0         50         MOE  120    0    0    0  260  635  25  225.0  40  40.0  NaN   92.5  145.0   92.5  118.56620  106.4338   0   0   0   0    0    0    0  15   10    0  10.0  12.0   0   6  0  0  7  7  M20    22           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19        0                     0                            0              -  0.0  0.0  0.0                  0.0            NaN  NaN  NaN          NaN                      NaN
18  JBE6018  IPE360  HEA260                       121.0           393.94                          0             0.0                          0             0.0         50         MOE  130    0    0    0  240  815  20  215.0  40  60.0  NaN  132.7  214.6  132.7   62.33530  152.6647   0   0   0   0    0    0    0  15   10    0  10.0  12.0   0   6  0  0  6  6  M20    22           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19        0                     0                            0              -  0.0  0.0  0.0                  0.0            NaN  NaN  NaN          NaN                      NaN
19  JBE6019  HEA300  HEA500                       121.0           534.66                          0             0.0                          0             0.0         50        MOE1  140    0    0    0  300  790  25  260.0  40  60.0  NaN  134.0  142.0  134.0  105.83420  154.1658   0   0   0   0    0    0    0  15   10    0  10.0  12.0   0   7  0  0  8  8  M22    24           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19        0                     0                            0              -  0.0  0.0  0.0                  0.0            NaN  NaN  NaN          NaN                      NaN

# DESCRIPCIÓN DE VARIABLES

- UNICODE: Identificador global de la unión
- BEAM: Estandar de viga
- COLUMN: Estandar de columna
- Capacity_Moment_Percentage: Porcentaje de momento
- Capacity_Moment: Momento
- Capacity_Shear_Percentage: Porcentaje de capacidad de fractura
- Capacity_Shear: Capacidad de fractura
- Capacity_Axial_Percentage: porcentaje de capacidad axial
- Capacity_Axial: Capacidad axial
- Pr_Porcen: 
- DrawingCode: 
- g: Distancia entre los centros de los tornillos
- tws: Grosor chapa columna
- Lws: Alto chapa columna
- Bws: Ancho chapa columna
- Bp: Ancho chapa tornillos
- Lp: Alto chapa tornillos
- tp: Grosor chapa tornillos
- Lh: Altura viga-
- e: Distancia borde chapa-primer tornillo
- d: Distancia tornillo-ala viga
- pfo: Todo nulls (descarte directo)
- pX: Distancia entre tornillo x y x+1
- ts: Grosor rigidizdor columna
- tbs: Grosor rigidizador viga
- tst: Grosor rigidizador columna-viga (union viga-columna)
- thw: 
- thf:
- wX:
- Bolt: Estandar grosor tornillos
- Hole: Agujero tornillos
- SlipCritical: Necesidad de 
- Normativas: Normativa
- AceroEstructural: Tipo de acero utilizado
- ElectrodoSoldadura: Tipo de soldadura
- EstandarTornillos: Estandar Tornillos
- Ordinary_Moment_Frames: 
- Calculation_Tool: Herramienta de cálculo utilizado
- Source: Región
- Designation: Designación
- rib_thk:
- Representation_Angle:
- BoltConnectionTypeSelection:
- National_Annex: Anexo nacional (excepciones en designaciones)
- p0:
- tso:
- Lst:
- SpecialMomentFrames:
- MzEd_PanelZone:
- Vgra: 
- Havg:
- Yieldmethod:
- Acero_Estructural_Perfil:

Veamos los tipos de las clases y sus valores:

In [108]:
for index, row in data.dtypes.items():
    print(f"{index}: {row}")

Unicode: str
BEAM: str
COLUMN: str
Capacity_Moment_Percentage: float64
Capacity_Moment: float64
Capacity_Shear_Percentage: int64
Capacity_Shear: float64
Capacity_Axial_Percentage: int64
Capacity_Axial: float64
Pr_Porcen: int64
DrawingCode: str
g: int64
tws: int64
Lws: int64
Bws: int64
Bp: int64
Lp: int64
tp: int64
Lh: float64
e: int64
d: float64
pfo: float64
p1: float64
p2: float64
p3: float64
p4: float64
p5: float64
p6: int64
p7: int64
p8: int64
p9: int64
p10: int64
p11: int64
p12: int64
ts: int64
tbs: int64
tst: int64
thw: float64
thf: float64
w1: int64
w2: int64
w3: object
w4: object
w5: object
w6: object
Bolt: str
Hole: int64
SlipCritical: str
Normativas: str
AceroEstructural: str
ElectrodoSoldadura: str
EstandarTornillos: object
Ordinary_Moment_Frames: bool
Calculation_Tool: str
Source: str
Designation: str
rib_thk: int64
Representation_Angle: int64
BoltConnectionTypeSelection: int64
National_Annex: str
p0: float64
tso: float64
Lst: float64
SpecialMomentFrames: float64
MzEd_PanelZone: object
Vgra: object
Havg: object
Yieldmethod: float64
Acero_Estructural_Perfil: str

Vemos que algunas wX son de tipo Object, debido a que los 0 son -.

Separamos por tipo de columna

In [109]:
numerical_columns = data.select_dtypes(include=[np.number]).columns.tolist()
categorical_columns = data.select_dtypes(include=['object', "str", "bool"]).columns.tolist()

In [110]:
numerical_df = data[numerical_columns]
categorical_df = data[categorical_columns]

Vamos a analizar las columnas por su tipo de dato.

## COLUMNAS NUMÉRICAS

In [111]:
numerical_df.head()

   Capacity_Moment_Percentage  Capacity_Moment  Capacity_Shear_Percentage  Capacity_Shear  Capacity_Axial_Percentage  Capacity_Axial  Pr_Porcen    g  tws  Lws  Bws   Bp   Lp  tp     Lh   e     d  pfo    p1     p2    p3        p4        p5  p6  p7  p8  p9  p10  p11  p12  ts  tbs  tst   thw   thf  w1  w2  Hole  rib_thk  Representation_Angle  BoltConnectionTypeSelection   p0  tso  Lst  SpecialMomentFrames  Yieldmethod
0                       121.0           242.94                          0             0.0                          0             0.0         50  110    0    0    0  190  705  20  245.0  40  40.0  NaN  90.7  198.6  90.7  140.6447  104.3553   0   0   0   0    0    0    0  12   10    0  10.0  10.0   0   6    22        0                     0                            0  0.0  0.0  0.0                  0.0          1.0
1                       121.0           125.60                          0             0.0                          0             0.0         50  110    0    0    0  200  466  20  135.0  35  40.0  NaN  89.5   45.0  50.0   45.0000  155.0000   0   0   0   0    0    0    0  10   10    0  10.0  10.0   0   5    18        0                     0                            0  0.0  0.0  0.0                  0.0          NaN
2                       121.0           242.94                          0             0.0                          0             0.0         50  110    0    0    0  190  705  20  245.0  40  40.0  NaN  90.7  198.6  90.7  140.6447  104.3553   0   0   0   0    0    0    0  12   10    0  10.0  10.0   0   6    22        0                     0                            0  0.0  0.0  0.0                  0.0          NaN
3                       121.0           166.04                          0             0.0                          0             0.0         50  110    0    0    0  220  565  20  215.0  35  40.0  NaN  90.0   90.0  90.0  111.4530  103.5470   0   0   0   0    0    0    0  10   10    0  10.0  10.0   0   5    18        0                     0                            0  0.0  0.0  0.0                  0.0          NaN
4                       121.0           287.86                          0             0.0                          0             0.0         50  120    0    0    0  240  600  25  210.0  40  40.0  NaN  92.0  126.0  92.0  104.1436  105.8564   0   0   0   0    0    0    0  12   10    0  10.0  10.0   0   6    22        0                     0                            0  0.0  0.0  0.0                  0.0          NaN

In [112]:
numerical_df.columns

Index(['Capacity_Moment_Percentage', 'Capacity_Moment', 'Capacity_Shear_Percentage', 'Capacity_Shear', 'Capacity_Axial_Percentage', 'Capacity_Axial', 'Pr_Porcen', 'g', 'tws', 'Lws', 'Bws', 'Bp', 'Lp', 'tp', 'Lh', 'e', 'd', 'pfo', 'p1', 'p2', 'p3', 'p4', 'p5', 'p6', 'p7', 'p8', 'p9', 'p10', 'p11', 'p12', 'ts', 'tbs', 'tst', 'thw', 'thf', 'w1', 'w2', 'Hole', 'rib_thk', 'Representation_Angle', 'BoltConnectionTypeSelection', 'p0', 'tso', 'Lst', 'SpecialMomentFrames', 'Yieldmethod'], dtype='str')

## CAPACIDADES Y PORCENTAJES

Estas variables indican las cargas, pero son datos redundantes entre sí, por lo que nos quedamos solo con no porcentajes.

In [113]:
# numerical_df.drop(columns=['Capacity_Moment', 'Capacity_Shear', 'Capacity_Axial'], inplace=True)

## VALORES NULOS, IGUALES O A 0

Vemos que la columna "Pr_Porcen" tiene siempre el valor 50, por lo que podemos eliminarla

In [114]:
describe = numerical_df.describe().transpose()

Veamos si alguna fila tiene todos los valores a 0:

In [115]:
for row in describe.iterrows():
    if row[1]["mean"] == 0:
        print(f"Row {row[0]} values are 0")

Row rib_thk values are 0
Row Representation_Angle values are 0
Row BoltConnectionTypeSelection values are 0

In [116]:
numerical_df.Representation_Angle.value_counts()

Representation_Angle
0    4767
Name: count, dtype: int64

In [117]:
numerical_df.BoltConnectionTypeSelection.value_counts()

BoltConnectionTypeSelection
0    4767
Name: count, dtype: int64

In [118]:
numerical_df.rib_thk.value_counts()

rib_thk
0    4767
Name: count, dtype: int64

Vemos que "Representation_Angle", "rib_thk" y "BoltConnectionTypeSelection" tienen todos los valores a 0, por lo que no serán relevantes para el modelo.

In [119]:
numerical_df.isna().sum()

Capacity_Moment_Percentage        0
Capacity_Moment                   0
Capacity_Shear_Percentage         0
Capacity_Shear                    0
Capacity_Axial_Percentage         0
Capacity_Axial                    0
Pr_Porcen                         0
g                                 0
tws                               0
Lws                               0
Bws                               0
Bp                                0
Lp                                0
tp                                0
Lh                                0
e                                 0
d                                 0
pfo                            4767
p1                                0
p2                                0
p3                                0
p4                                0
p5                                0
p6                                0
p7                                0
p8                                0
p9                                0
p10                               0
p11                               0
p12                               0
ts                                0
tbs                               0
tst                               0
thw                               0
thf                               0
w1                                0
w2                                0
Hole                              0
rib_thk                           0
Representation_Angle              0
BoltConnectionTypeSelection       0
p0                             3490
tso                            3490
Lst                            3490
SpecialMomentFrames            3490
Yieldmethod                    4397
dtype: int64

Vemos que pfo tiene todos sus valores a Na, por lo que la descartaremos.

In [120]:
numerical_df.drop(columns=["Pr_Porcen", "Representation_Angle", "rib_thk", "BoltConnectionTypeSelection", "pfo"], inplace=True)
numerical_df.head()

   Capacity_Moment_Percentage  Capacity_Moment  Capacity_Shear_Percentage  Capacity_Shear  Capacity_Axial_Percentage  Capacity_Axial    g  tws  Lws  Bws   Bp   Lp  tp     Lh   e     d    p1     p2    p3        p4        p5  p6  p7  p8  p9  p10  p11  p12  ts  tbs  tst   thw   thf  w1  w2  Hole   p0  tso  Lst  SpecialMomentFrames  Yieldmethod
0                       121.0           242.94                          0             0.0                          0             0.0  110    0    0    0  190  705  20  245.0  40  40.0  90.7  198.6  90.7  140.6447  104.3553   0   0   0   0    0    0    0  12   10    0  10.0  10.0   0   6    22  0.0  0.0  0.0                  0.0          1.0
1                       121.0           125.60                          0             0.0                          0             0.0  110    0    0    0  200  466  20  135.0  35  40.0  89.5   45.0  50.0   45.0000  155.0000   0   0   0   0    0    0    0  10   10    0  10.0  10.0   0   5    18  0.0  0.0  0.0                  0.0          NaN
2                       121.0           242.94                          0             0.0                          0             0.0  110    0    0    0  190  705  20  245.0  40  40.0  90.7  198.6  90.7  140.6447  104.3553   0   0   0   0    0    0    0  12   10    0  10.0  10.0   0   6    22  0.0  0.0  0.0                  0.0          NaN
3                       121.0           166.04                          0             0.0                          0             0.0  110    0    0    0  220  565  20  215.0  35  40.0  90.0   90.0  90.0  111.4530  103.5470   0   0   0   0    0    0    0  10   10    0  10.0  10.0   0   5    18  0.0  0.0  0.0                  0.0          NaN
4                       121.0           287.86                          0             0.0                          0             0.0  120    0    0    0  240  600  25  210.0  40  40.0  92.0  126.0  92.0  104.1436  105.8564   0   0   0   0    0    0    0  12   10    0  10.0  10.0   0   6    22  0.0  0.0  0.0                  0.0          NaN

## CHAPA DE LA COLUMNA

Siguiendo indicaciones, podemos eliminar ancho y largo de la plancha que se pone en la columna (si aplica), ya que solo nos interesa su grosor

In [121]:
numerical_df.drop(columns=["Lws", "Bws"], inplace=True)

Comentar que si no tiene esta chapa, el valor será 0. Se determinará un mínimo para el grosor.

## CANTONERA y SOLDADURA

Se deduce de las filas de tornillos.

Sabemos que las variables wX y thw se refieren a propiedades de soldado, que no vamos a utilizar, por lo que podemos eliminarlas

Hecho esto, eliminamos las medidas:

In [122]:
numerical_df.drop(columns=["thw", "thf", "w1", "w2"], inplace=True)

## RIGIDIZADORES

Los rigidizadores tienen medidas en función de la columna y viga y, en principio, siempre aparecene, por lo que lo relacionado con ello se elimina

In [123]:
numerical_df.drop(columns=["tso", "Lst"], inplace=True)

In [124]:
numerical_df.columns

Index(['Capacity_Moment_Percentage', 'Capacity_Moment', 'Capacity_Shear_Percentage', 'Capacity_Shear', 'Capacity_Axial_Percentage', 'Capacity_Axial', 'g', 'tws', 'Bp', 'Lp', 'tp', 'Lh', 'e', 'd', 'p1', 'p2', 'p3', 'p4', 'p5', 'p6', 'p7', 'p8', 'p9', 'p10', 'p11', 'p12', 'ts', 'tbs', 'tst', 'Hole', 'p0', 'SpecialMomentFrames', 'Yieldmethod'], dtype='str')

# QUITAR SPECIAL

## COLUMNAS CATEGÓRICAS

In [125]:
categorical_df.columns

Index(['Unicode', 'BEAM', 'COLUMN', 'DrawingCode', 'w3', 'w4', 'w5', 'w6', 'Bolt', 'SlipCritical', 'Normativas', 'AceroEstructural', 'ElectrodoSoldadura', 'EstandarTornillos', 'Ordinary_Moment_Frames', 'Calculation_Tool', 'Source', 'Designation', 'National_Annex', 'MzEd_PanelZone', 'Vgra', 'Havg', 'Acero_Estructural_Perfil'], dtype='str')

Veamos un poco las categorías

## NORMATIVA (PARA LAS MEDIDAS)

Quien va a identificar el estandar va a ser la combinación Normativas-National_Annex

In [126]:
categorical_df["National_Annex"] = categorical_df["National_Annex"].replace(0, "", inplace=True)

C:\Users\aarbona\AppData\Local\Temp\ipykernel_2932\1378253261.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  categorical_df["National_Annex"] = categorical_df["National_Annex"].replace(0, "", inplace=True)

In [127]:
categorical_df["National_Annex"].value_counts()

National_Annex
-                              3548
SP RK EN 1993-1-8:2005/2011    1219
Name: count, dtype: int64

In [128]:
categorical_df["standard"] = (
    categorical_df["Normativas"].fillna("").astype(str)
    + categorical_df["National_Annex"].map(lambda x: f" - {x}" if x else "")
)

In [129]:
categorical_df[categorical_df["National_Annex"] != ""].head()

   Unicode    BEAM  COLUMN DrawingCode w3 w4 w5 w6 Bolt SlipCritical      Normativas AceroEstructural ElectrodoSoldadura EstandarTornillos  Ordinary_Moment_Frames Calculation_Tool    Source Designation National_Annex MzEd_PanelZone Vgra Havg Acero_Estructural_Perfil            standard
0  JBE6000  IPE300  HEA260         MOE  0  0  6  6  M20           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19              -              -    -    -                   S355JR  AISC-360-05/10 - -
1  JBE6001  HEA180  HEA300         MOE  0  0  6  6  M16           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19              -            NaN  NaN  NaN                      NaN  AISC-360-05/10 - -
2  JBE6002  IPE300  HEA320         MOE  0  0  6  6  M20           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19              -            NaN  NaN  NaN                      NaN  AISC-360-05/10 - -
3  JBE6003  HEA200  HEA280         MOE  0  0  6  6  M16           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19              -            NaN  NaN  NaN                      NaN  AISC-360-05/10 - -
4  JBE6004  HEA240  HEA300         MOE  0  0  7  7  M20           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19              -            NaN  NaN  NaN                      NaN  AISC-360-05/10 - -

In [130]:
#categorical_df.drop(columns=["Normativas", "National_Annex"], inplace=True)

categorical_df.head()

   Unicode    BEAM  COLUMN DrawingCode w3 w4 w5 w6 Bolt SlipCritical      Normativas AceroEstructural ElectrodoSoldadura EstandarTornillos  Ordinary_Moment_Frames Calculation_Tool    Source Designation National_Annex MzEd_PanelZone Vgra Havg Acero_Estructural_Perfil            standard
0  JBE6000  IPE300  HEA260         MOE  0  0  6  6  M20           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19              -              -    -    -                   S355JR  AISC-360-05/10 - -
1  JBE6001  HEA180  HEA300         MOE  0  0  6  6  M16           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19              -            NaN  NaN  NaN                      NaN  AISC-360-05/10 - -
2  JBE6002  IPE300  HEA320         MOE  0  0  6  6  M20           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19              -            NaN  NaN  NaN                      NaN  AISC-360-05/10 - -
3  JBE6003  HEA200  HEA280         MOE  0  0  6  6  M16           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19              -            NaN  NaN  NaN                      NaN  AISC-360-05/10 - -
4  JBE6004  HEA240  HEA300         MOE  0  0  7  7  M20           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19              -            NaN  NaN  NaN                      NaN  AISC-360-05/10 - -

Con esto, junto a al código de columna o viga sabremos las medidas de estas.

## SOLDADURAS

Como hemos hecho en las variables numéricas, eliminamos todas las columnas relacionadas con las soldaduras

In [131]:
categorical_df.drop(columns=["ElectrodoSoldadura", "w3", "w4", "w5", "w6"], inplace=True)

## OTRAS VARIABLES A ELIMINAR

La herramienta de cálculo es irrelevante, por lo que la eliminamos.

Todas las designaciones son "Tekla19", por lo que la eliminamos.

In [132]:
categorical_df.drop(columns=["Calculation_Tool", "Designation", 
'MzEd_PanelZone', 'Vgra', 'Havg', 'Ordinary_Moment_Frames', 'Acero_Estructural_Perfil'], inplace=True)

In [133]:
categorical_df.columns

Index(['Unicode', 'BEAM', 'COLUMN', 'DrawingCode', 'Bolt', 'SlipCritical', 'Normativas', 'AceroEstructural', 'EstandarTornillos', 'Source', 'National_Annex', 'standard'], dtype='str')

In [134]:
numerical_df.drop(columns=["Yieldmethod"], inplace=True)

# DATAFRAME FINAL

In [135]:
df_final = pd.concat([numerical_df, categorical_df], axis=1)

df_final.head()

   Capacity_Moment_Percentage  Capacity_Moment  Capacity_Shear_Percentage  Capacity_Shear  Capacity_Axial_Percentage  Capacity_Axial    g  tws   Bp   Lp  tp     Lh   e     d    p1     p2    p3        p4        p5  p6  p7  p8  p9  p10  p11  p12  ts  tbs  tst  Hole   p0  SpecialMomentFrames  Unicode    BEAM  COLUMN DrawingCode Bolt SlipCritical      Normativas AceroEstructural EstandarTornillos    Source National_Annex            standard
0                       121.0           242.94                          0             0.0                          0             0.0  110    0  190  705  20  245.0  40  40.0  90.7  198.6  90.7  140.6447  104.3553   0   0   0   0    0    0    0  12   10    0    22  0.0                  0.0  JBE6000  IPE300  HEA260         MOE  M20           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -
1                       121.0           125.60                          0             0.0                          0             0.0  110    0  200  466  20  135.0  35  40.0  89.5   45.0  50.0   45.0000  155.0000   0   0   0   0    0    0    0  10   10    0    18  0.0                  0.0  JBE6001  HEA180  HEA300         MOE  M16           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -
2                       121.0           242.94                          0             0.0                          0             0.0  110    0  190  705  20  245.0  40  40.0  90.7  198.6  90.7  140.6447  104.3553   0   0   0   0    0    0    0  12   10    0    22  0.0                  0.0  JBE6002  IPE300  HEA320         MOE  M20           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -
3                       121.0           166.04                          0             0.0                          0             0.0  110    0  220  565  20  215.0  35  40.0  90.0   90.0  90.0  111.4530  103.5470   0   0   0   0    0    0    0  10   10    0    18  0.0                  0.0  JBE6003  HEA200  HEA280         MOE  M16           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -
4                       121.0           287.86                          0             0.0                          0             0.0  120    0  240  600  25  210.0  40  40.0  92.0  126.0  92.0  104.1436  105.8564   0   0   0   0    0    0    0  12   10    0    22  0.0                  0.0  JBE6004  HEA240  HEA300         MOE  M20           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -

Vamos a poner el unicode como identificador de las filas, que son únicas dentro de nuestro sistema.

In [136]:
df_final.set_index("Unicode", inplace=True)

df_final.head()

         Capacity_Moment_Percentage  Capacity_Moment  Capacity_Shear_Percentage  Capacity_Shear  Capacity_Axial_Percentage  Capacity_Axial    g  tws   Bp   Lp  tp     Lh   e     d    p1     p2    p3        p4        p5  p6  p7  p8  p9  p10  p11  p12  ts  tbs  tst  Hole   p0  SpecialMomentFrames    BEAM  COLUMN DrawingCode Bolt SlipCritical      Normativas AceroEstructural EstandarTornillos    Source National_Annex            standard
Unicode
JBE6000                       121.0           242.94                          0             0.0                          0             0.0  110    0  190  705  20  245.0  40  40.0  90.7  198.6  90.7  140.6447  104.3553   0   0   0   0    0    0    0  12   10    0    22  0.0                  0.0  IPE300  HEA260         MOE  M20           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -
JBE6001                       121.0           125.60                          0             0.0                          0             0.0  110    0  200  466  20  135.0  35  40.0  89.5   45.0  50.0   45.0000  155.0000   0   0   0   0    0    0    0  10   10    0    18  0.0                  0.0  HEA180  HEA300         MOE  M16           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -
JBE6002                       121.0           242.94                          0             0.0                          0             0.0  110    0  190  705  20  245.0  40  40.0  90.7  198.6  90.7  140.6447  104.3553   0   0   0   0    0    0    0  12   10    0    22  0.0                  0.0  IPE300  HEA320         MOE  M20           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -
JBE6003                       121.0           166.04                          0             0.0                          0             0.0  110    0  220  565  20  215.0  35  40.0  90.0   90.0  90.0  111.4530  103.5470   0   0   0   0    0    0    0  10   10    0    18  0.0                  0.0  HEA200  HEA280         MOE  M16           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -
JBE6004                       121.0           287.86                          0             0.0                          0             0.0  120    0  240  600  25  210.0  40  40.0  92.0  126.0  92.0  104.1436  105.8564   0   0   0   0    0    0    0  12   10    0    22  0.0                  0.0  HEA240  HEA300         MOE  M20           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -

In [137]:
df_final.columns

Index(['Capacity_Moment_Percentage', 'Capacity_Moment', 'Capacity_Shear_Percentage', 'Capacity_Shear', 'Capacity_Axial_Percentage', 'Capacity_Axial', 'g', 'tws', 'Bp', 'Lp', 'tp', 'Lh', 'e', 'd', 'p1', 'p2', 'p3', 'p4', 'p5', 'p6', 'p7', 'p8', 'p9', 'p10', 'p11', 'p12', 'ts', 'tbs', 'tst', 'Hole', 'p0', 'SpecialMomentFrames', 'BEAM', 'COLUMN', 'DrawingCode', 'Bolt', 'SlipCritical', 'Normativas', 'AceroEstructural', 'EstandarTornillos', 'Source', 'National_Annex', 'standard'], dtype='str')

# QUITAR FILAS SPECIALMOMENTFRAMES VERDADERO

In [138]:
df_final.shape

(4767, 43)

In [139]:
df_final_c = df_final[df_final["SpecialMomentFrames"] != 1]

In [140]:
df_final_c.shape

(4722, 43)

In [141]:
(df_final_c["p0"] > 0).sum()

np.int64(0)

In [142]:
df_final = df_final_c.drop(columns=["p0", "SpecialMomentFrames"])

# AÑADIR DATOS DE TEKLA

In [143]:
eu = pd.read_csv(dir / 'tekla_eu.csv')
cad = pd.read_csv(dir / 'tekla_cad.csv')
resto = pd.read_csv(dir / "tekla_faltante.csv")

In [144]:
df_union = pd.concat([eu, cad, resto])
df_union = df_union[["tekla_nomenclature_1", "type", "d_mm", 
        "bf_mm", "tw_mm", "tf_mm", "r1_mm", "wely_mm", "w_kgm"
        ]]

In [145]:
df_union.dtypes

tekla_nomenclature_1        str
type                        str
d_mm                    float64
bf_mm                   float64
tw_mm                   float64
tf_mm                   float64
r1_mm                   float64
wely_mm                 float64
w_kgm                   float64
dtype: object

In [146]:
faltan_BEAM = set(df_final["BEAM"].unique()) - set(df_union["tekla_nomenclature_1"].unique())
faltan_COLUMN = set(df_final["COLUMN"].unique()) - set(df_union["tekla_nomenclature_1"].unique())

faltan_BEAM | faltan_COLUMN

set()

In [147]:
union_BEAM = (df_union.set_index('tekla_nomenclature_1')
    .add_prefix('BEAM_')
    .reset_index()
)

union_COLUMN = (df_union.set_index('tekla_nomenclature_1')
    .add_prefix('COLUMN_')
    .reset_index()
)
union_BEAM

    tekla_nomenclature_1 BEAM_type  BEAM_d_mm  BEAM_bf_mm  BEAM_tw_mm  BEAM_tf_mm  BEAM_r1_mm  BEAM_wely_mm  BEAM_w_kgm
0                 HEA100        HE       96.0       100.0         5.0         8.0        12.0         72.80   16.700001
1                HEA1000        HE      990.0       300.0        16.5        31.0        30.0      11190.00  272.000000
2                 HEA120        HE      114.0       120.0         5.0         8.0        12.0        106.30   19.900000
3                 HEA140        HE      133.0       140.0         5.5         8.5        12.0        155.40   24.700001
4                 HEA160        HE      152.0       160.0         6.0         9.0        15.0        220.10   30.400000
..                   ...       ...        ...         ...         ...         ...         ...           ...         ...
402      HI900-60-70*300        HI     1040.0       300.0        60.0        70.0         0.0      26041.54  753.600000
403      HI900060070*300        HI     1040.0       300.0        60.0        70.0         0.0      26041.54  753.600000
404      HI920-30-65*350        HI     1050.0       350.0        30.0        65.0         0.0      24760.09  573.800000
405      HI920-30-65*500        HI     1050.0       500.0        30.0        65.0         0.0      33782.40  726.900000
406               IPE180       IPE      180.0        91.0         5.3         8.0         9.0        146.00   18.800000

[407 rows x 9 columns]

In [148]:
df_final.shape

(4722, 41)

In [149]:
df_merge1 = pd.merge(df_final, union_BEAM, left_on="BEAM", right_on="tekla_nomenclature_1").drop(columns=["tekla_nomenclature_1"])
df_merge2 = pd.merge(df_merge1, union_COLUMN, left_on="COLUMN", right_on="tekla_nomenclature_1").drop(columns=["tekla_nomenclature_1"])
df_merge2

      Capacity_Moment_Percentage  Capacity_Moment  Capacity_Shear_Percentage  Capacity_Shear  Capacity_Axial_Percentage  Capacity_Axial    g  tws   Bp   Lp  tp     Lh   e     d     p1     p2     p3        p4        p5   p6   p7  p8  p9  p10  p11  p12  ts  tbs  tst  Hole    BEAM  COLUMN DrawingCode Bolt SlipCritical      Normativas AceroEstructural EstandarTornillos    Source National_Annex            standard BEAM_type  BEAM_d_mm  BEAM_bf_mm  BEAM_tw_mm  BEAM_tf_mm  BEAM_r1_mm  BEAM_wely_mm  BEAM_w_kgm COLUMN_type  COLUMN_d_mm  COLUMN_bf_mm  COLUMN_tw_mm  COLUMN_tf_mm  COLUMN_r1_mm  COLUMN_wely_mm  COLUMN_w_kgm
0                          121.0           242.94                          0             0.0                          0             0.0  110    0  190  705  20  245.0  40  40.0   90.7  198.6   90.7  140.6447  104.3553    0    0   0   0    0    0    0  12   10    0    22  IPE300  HEA260         MOE  M20           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -       IPE      300.0       150.0         7.1        10.7        15.0         557.0   42.200000          HE        250.0         260.0           7.5          12.5          24.0           836.4     68.199997
1                          121.0           125.60                          0             0.0                          0             0.0  110    0  200  466  20  135.0  35  40.0   89.5   45.0   50.0   45.0000  155.0000    0    0   0   0    0    0    0  10   10    0    18  HEA180  HEA300         MOE  M16           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -        HE      171.0       180.0         6.0         9.5        15.0         293.6   35.500000          HE        290.0         300.0           8.5          14.0          27.0          1260.0     88.300000
2                          121.0           242.94                          0             0.0                          0             0.0  110    0  190  705  20  245.0  40  40.0   90.7  198.6   90.7  140.6447  104.3553    0    0   0   0    0    0    0  12   10    0    22  IPE300  HEA320         MOE  M20           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -       IPE      300.0       150.0         7.1        10.7        15.0         557.0   42.200000          HE        310.0         300.0           9.0          15.5          27.0          1479.0     97.599998
3                          121.0           166.04                          0             0.0                          0             0.0  110    0  220  565  20  215.0  35  40.0   90.0   90.0   90.0  111.4530  103.5470    0    0   0   0    0    0    0  10   10    0    18  HEA200  HEA280         MOE  M16           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -        HE      190.0       200.0         6.5        10.0        18.0         388.6   42.299999          HE        270.0         280.0           8.0          13.0          24.0          1013.0     76.400002
4                          121.0           287.86                          0             0.0                          0             0.0  120    0  240  600  25  210.0  40  40.0   92.0  126.0   92.0  104.1436  105.8564    0    0   0   0    0    0    0  12   10    0    22  HEA240  HEA300         MOE  M20           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -        HE      230.0       240.0         7.5        12.0        21.0         675.1   60.299999          HE        290.0         300.0           8.5          14.0          27.0          1260.0     88.300000
...                          ...              ...                        ...             ...                        ...             ...  ...  ...  ...  ...  ..    ...  ..   ...    ...    ...    ...       ...       ...  ...  ...  ..  ..  ...  ...  ...  ..  ...  ...   ...     ...     ...         ...  ...          ...             ...              ...               ...       ...            ...                 ...       ...        ...         ...         ...         ...         ...           ...         ...         ...          ...           ...           ...           ...           ...             ...           ...
4717                       121.0           534.66                          0             0.0                          0             0.0  120    0  305  695  15  234.0  40  45.0  105.0   70.0  100.0  140.0000   70.0000  130    0   0   0    0    0    0  10   12    0    27  HEA300  HEM600         MLE  M24           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -        HE      290.0       300.0         8.5        14.0        27.0        1260.0   88.300000          HE        620.0         305.0          21.0          40.0          27.0          7660.0    285.000000
4718                       121.0          1037.23                          0             0.0                          0             0.0  140    0  305  849  15  291.0  45  55.0  125.0   75.0  140.0  190.0000   75.0000  150    0   0   0    0    0    0  10   25    0    30  HEB360  HEM600         MLE  M27           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -        HE      360.0       300.0        12.5        22.5        27.0        2400.0  142.000000          HE        620.0         305.0          21.0          40.0          27.0          7660.0    285.000000
4719                       121.0           505.28                          0             0.0                          0             0.0  110    0  200  880  20  323.0  40  40.0   90.0   55.0  240.0   90.0000  160.0000   55  110   0   0    0    0    0  10   12    0    22  IPE400  HEB240         MLE  M20           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -       IPE      400.0       180.0         8.6        13.5        21.0        1160.0   66.300000          HE        240.0         240.0          10.0          17.0          21.0           938.3     83.199997
4720                       121.0           722.55                          0             0.0                          0             0.0  135    0  300  815  20  325.0  45  55.0  120.0  120.0  265.0   75.0000  145.0000    0    0   0   0    0    0    0  10   20    0    30  HEB300  HEA360         MLE  M27           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -        HE      300.0       300.0        11.0        19.0        27.0        1678.0  117.000000          HE        350.0         300.0          10.0          17.5          27.0          1891.0    112.000000
4721                       121.0           722.55                          0             0.0                          0             0.0  135    0  300  730  20  242.0  45  50.0  120.0  120.0  180.0   75.0000  145.0000    0    0   0   0    0    0    0  12   20    0    30  HEB300  HEA450         MLE  M27           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -        HE      300.0       300.0        11.0        19.0        27.0        1678.0  117.000000          HE        440.0         300.0          11.5          21.0          27.0          2896.0    140.000000

[4722 rows x 57 columns]

In [150]:
df_merge2.drop(columns=["BEAM_r1_mm", "BEAM_wely_mm", "BEAM_w_kgm","COLUMN_r1_mm", "COLUMN_wely_mm", "COLUMN_w_kgm"],
                inplace=True)

# AÑADIR RESISTENCIAS ACERO Y TORNILLOS

In [151]:
df_aceros = pd.DataFrame([
    {
        "grado_acero": "S275JR",
        "fy_acero_mpa": 275.0,  # Límite elástico (MPa)
        "fu_acero_mpa": 430.0   # Resistencia a tracción (MPa)
    },
    {
        "grado_acero": "S355JR",
        "fy_acero_mpa": 355.0,
        "fu_acero_mpa": 490.0
    }
])

df_tornillos = pd.DataFrame([
    {
        "clase_tornillo": "8.8",
        "fy_tornillo_mpa": 640.0,  # Límite elástico (MPa) - Corregido
        "fu_tornillo_mpa": 800.0,  # Resistencia a tracción (MPa)
        "fv_tornillo_mpa": 480.0   # Resistencia a cortante (MPa)
    },
    {
        "clase_tornillo": "10.9",
        "fy_tornillo_mpa": 900.0,
        "fu_tornillo_mpa": 1000.0,
        "fv_tornillo_mpa": 500.0
    },
    {
        "clase_tornillo": "A325M",
        "fy_tornillo_mpa": 660.0,
        "fu_tornillo_mpa": 830.0,
        "fv_tornillo_mpa": 372.0
    }
])

In [152]:
df_merge2.shape

(4722, 51)

In [153]:
df_final2 = pd.merge(df_merge2, df_aceros, left_on="AceroEstructural", right_on="grado_acero")
df_final2.shape

(4722, 54)

In [154]:
df_final2['EstandarTornillos'] = df_final2['EstandarTornillos'].replace({ 'ASTM A325': "A325M"}).astype(str)

In [155]:
df_final3 = pd.merge(df_final2, df_tornillos, left_on="EstandarTornillos", right_on="clase_tornillo")
df_final3.shape

(4722, 58)

In [156]:
df_final3.drop(columns=["grado_acero", "clase_tornillo"], inplace=True)

In [157]:
df_final3.columns

Index(['Capacity_Moment_Percentage', 'Capacity_Moment', 'Capacity_Shear_Percentage', 'Capacity_Shear', 'Capacity_Axial_Percentage', 'Capacity_Axial', 'g', 'tws', 'Bp', 'Lp', 'tp', 'Lh', 'e', 'd', 'p1', 'p2', 'p3', 'p4', 'p5', 'p6', 'p7', 'p8', 'p9', 'p10', 'p11', 'p12', 'ts', 'tbs', 'tst', 'Hole', 'BEAM', 'COLUMN', 'DrawingCode', 'Bolt', 'SlipCritical', 'Normativas', 'AceroEstructural', 'EstandarTornillos', 'Source', 'National_Annex', 'standard', 'BEAM_type', 'BEAM_d_mm', 'BEAM_bf_mm', 'BEAM_tw_mm', 'BEAM_tf_mm', 'COLUMN_type', 'COLUMN_d_mm', 'COLUMN_bf_mm', 'COLUMN_tw_mm', 'COLUMN_tf_mm', 'fy_acero_mpa', 'fu_acero_mpa', 'fy_tornillo_mpa', 'fu_tornillo_mpa', 'fv_tornillo_mpa'], dtype='str')

In [158]:
df = df_final3
df.head()

   Capacity_Moment_Percentage  Capacity_Moment  Capacity_Shear_Percentage  Capacity_Shear  Capacity_Axial_Percentage  Capacity_Axial    g  tws   Bp   Lp  tp     Lh   e     d    p1     p2    p3        p4        p5  p6  p7  p8  p9  p10  p11  p12  ts  tbs  tst  Hole    BEAM  COLUMN DrawingCode Bolt SlipCritical      Normativas AceroEstructural EstandarTornillos    Source National_Annex            standard BEAM_type  BEAM_d_mm  BEAM_bf_mm  BEAM_tw_mm  BEAM_tf_mm COLUMN_type  COLUMN_d_mm  COLUMN_bf_mm  COLUMN_tw_mm  COLUMN_tf_mm  fy_acero_mpa  fu_acero_mpa  fy_tornillo_mpa  fu_tornillo_mpa  fv_tornillo_mpa
0                       121.0           242.94                          0             0.0                          0             0.0  110    0  190  705  20  245.0  40  40.0  90.7  198.6  90.7  140.6447  104.3553   0   0   0   0    0    0    0  12   10    0    22  IPE300  HEA260         MOE  M20           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -       IPE      300.0       150.0         7.1        10.7          HE        250.0         260.0           7.5          12.5         355.0         490.0            900.0           1000.0            500.0
1                       121.0           125.60                          0             0.0                          0             0.0  110    0  200  466  20  135.0  35  40.0  89.5   45.0  50.0   45.0000  155.0000   0   0   0   0    0    0    0  10   10    0    18  HEA180  HEA300         MOE  M16           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -        HE      171.0       180.0         6.0         9.5          HE        290.0         300.0           8.5          14.0         355.0         490.0            900.0           1000.0            500.0
2                       121.0           242.94                          0             0.0                          0             0.0  110    0  190  705  20  245.0  40  40.0  90.7  198.6  90.7  140.6447  104.3553   0   0   0   0    0    0    0  12   10    0    22  IPE300  HEA320         MOE  M20           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -       IPE      300.0       150.0         7.1        10.7          HE        310.0         300.0           9.0          15.5         355.0         490.0            900.0           1000.0            500.0
3                       121.0           166.04                          0             0.0                          0             0.0  110    0  220  565  20  215.0  35  40.0  90.0   90.0  90.0  111.4530  103.5470   0   0   0   0    0    0    0  10   10    0    18  HEA200  HEA280         MOE  M16           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -        HE      190.0       200.0         6.5        10.0          HE        270.0         280.0           8.0          13.0         355.0         490.0            900.0           1000.0            500.0
4                       121.0           287.86                          0             0.0                          0             0.0  120    0  240  600  25  210.0  40  40.0  92.0  126.0  92.0  104.1436  105.8564   0   0   0   0    0    0    0  12   10    0    22  HEA240  HEA300         MOE  M20           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -        HE      230.0       240.0         7.5        12.0          HE        290.0         300.0           8.5          14.0         355.0         490.0            900.0           1000.0            500.0

## DISTANCIAS

In [159]:
# de int a float
int_a_float = ['p6',
"p7",
'p8',
'p9',
'p10',
'p11',
'p12']

for col in int_a_float:
    df_final3[col] = df_final3[col].astype(float)

In [160]:
# Columnas p1 a p12
p_cols = [f"p{i}" for i in range(1, 13)]

# 1. Calcular la distancia total desde el borde superior hasta el último tornillo
# (e + la suma de todos los pX)
D_total = df["e"] + df[p_cols].sum(axis=1)

# 2. Calcular las posiciones acumuladas en mm
bolt_pos_mm = pd.DataFrame(index=df.index)
bolt_pos_mm["bolt_1_mm"] = df["e"]

# Suma acumulada de las pX
p_cumsum = df[p_cols].cumsum(axis=1)

for i in range(2, 14):  # Tornillos del 2 al 13
  bolt_pos_mm[f"bolt_{i}_mm"] = df["e"] + p_cumsum[f"p{i-1}"]

# 3. Convertir cada posición a porcentaje del total
bolt_pct = pd.DataFrame(index=df.index)
for i in range(1, 14):
  bolt_pct[f"bolt_{i}_pct"] = (bolt_pos_mm[f"bolt_{i}_mm"] / D_total)

# 4. Manejo de tornillos inexistentes (opcional):
# Si una fila tiene menos de 13 filas de tornillos, los tornillos sobrantes
# repetirán el 100%. Si prefieres que valgan 0% para el modelo de IA:
mask_exist = pd.DataFrame(True, index=df.index, columns=bolt_pct.columns)
mask_exist["bolt_1_pct"] = True
for i in range(2, 14):
  # Un tornillo existe si el p correspondiente anterior es mayor que 0
  mask_exist[f"bolt_{i}_pct"] = (df[f"p{i-1}"] > 0) & mask_exist[
      f"bolt_{i-1}_pct"
  ]

# Aplicar máscara: 0 en los tornillos no utilizados
bolt_pct = bolt_pct.where(mask_exist, 0.0)

# Unir las nuevas columnas de porcentaje al DataFrame principal
df_transformed = pd.concat([df, bolt_pct], axis=1)

In [161]:
df_transformed.tail(20)

      Capacity_Moment_Percentage  Capacity_Moment  Capacity_Shear_Percentage  Capacity_Shear  Capacity_Axial_Percentage  Capacity_Axial    g  tws   Bp    Lp  tp     Lh   e     d     p1     p2     p3     p4     p5     p6     p7   p8   p9  p10  p11  p12  ts  tbs  tst  Hole    BEAM           COLUMN DrawingCode Bolt SlipCritical      Normativas AceroEstructural EstandarTornillos    Source National_Annex            standard BEAM_type  BEAM_d_mm  BEAM_bf_mm  BEAM_tw_mm  BEAM_tf_mm COLUMN_type  COLUMN_d_mm  COLUMN_bf_mm  COLUMN_tw_mm  COLUMN_tf_mm  fy_acero_mpa  fu_acero_mpa  fy_tornillo_mpa  fu_tornillo_mpa  fv_tornillo_mpa  bolt_1_pct  bolt_2_pct  bolt_3_pct  bolt_4_pct  bolt_5_pct  bolt_6_pct  bolt_7_pct  bolt_8_pct  bolt_9_pct  bolt_10_pct  bolt_11_pct  bolt_12_pct  bolt_13_pct
4702                       121.0           505.28                          0             0.0                          0             0.0  110    0  200   880  15  323.0  40  40.0   90.0   55.0  240.0   90.0  160.0   55.0  110.0  0.0  0.0  0.0  0.0  0.0  10   12    0    22  IPE400           HEB400         MLE  M20           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -       IPE      400.0       180.0         8.6        13.5          HE        400.0         300.0          13.5          24.0         355.0         490.0            900.0           1000.0            500.0    0.047619    0.154762    0.220238    0.505952    0.613095    0.803571    0.869048         1.0         0.0          0.0          0.0          0.0          0.0
4703                       121.0           505.28                          0             0.0                          0             0.0  110    0  200   880  15  323.0  40  40.0   90.0   55.0  240.0   90.0  160.0   55.0  110.0  0.0  0.0  0.0  0.0  0.0  10   12    0    22  IPE400           HEB450         MLE  M20           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -       IPE      400.0       180.0         8.6        13.5          HE        450.0         300.0          14.0          26.0         355.0         490.0            900.0           1000.0            500.0    0.047619    0.154762    0.220238    0.505952    0.613095    0.803571    0.869048         1.0         0.0          0.0          0.0          0.0          0.0
4704                       121.0           629.38                          0             0.0                          0             0.0  120    0  300   730  25  251.0  40  45.0  105.0   70.0  120.0  155.0   70.0  130.0    0.0  0.0  0.0  0.0  0.0  0.0  10   15    0    27  HEA320           HEB400         MLE  M24           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -        HE      310.0       300.0         9.0        15.5          HE        400.0         300.0          13.5          24.0         355.0         490.0            900.0           1000.0            500.0    0.057971    0.210145    0.311594    0.485507    0.710145    0.811594    1.000000         0.0         0.0          0.0          0.0          0.0          0.0
4705                       121.0           534.66                          0             0.0                          0             0.0  120    0  300   695  25  234.0  40  45.0  105.0   70.0  100.0  140.0   70.0  130.0    0.0  0.0  0.0  0.0  0.0  0.0  10   12    0    27  HEA300           HEB400         MLE  M24           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -        HE      290.0       300.0         8.5        14.0          HE        400.0         300.0          13.5          24.0         355.0         490.0            900.0           1000.0            500.0    0.061069    0.221374    0.328244    0.480916    0.694656    0.801527    1.000000         0.0         0.0          0.0          0.0          0.0          0.0
4706                       121.0           534.66                          0             0.0                          0             0.0  120    0  300   695  25  234.0  40  45.0  105.0   70.0  100.0  140.0   70.0  130.0    0.0  0.0  0.0  0.0  0.0  0.0  25   12    0    27  HEA300           HEB320         MLE  M24           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -        HE      290.0       300.0         8.5        14.0          HE        320.0         300.0          11.5          20.5         355.0         490.0            900.0           1000.0            500.0    0.061069    0.221374    0.328244    0.480916    0.694656    0.801527    1.000000         0.0         0.0          0.0          0.0          0.0          0.0
4707                       121.0            85.28                          0             0.0                          0             0.0   95    0  140   495  25  162.0  35  35.0   75.0   45.0   70.0  100.0   45.0   90.0    0.0  0.0  0.0  0.0  0.0  0.0  12   10    0    18  IPE200           HEB300         MLE  M16           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -       IPE      200.0       100.0         5.6         8.5          HE        300.0         300.0          11.0          19.0         355.0         490.0            900.0           1000.0            500.0    0.076087    0.239130    0.336957    0.489130    0.706522    0.804348    1.000000         0.0         0.0          0.0          0.0          0.0          0.0
4708                       121.0           310.94                          0             0.0                          0             0.0  105    0  180   765  20  267.0  40  40.0   90.0   55.0  175.0  190.0   55.0  110.0    0.0  0.0  0.0  0.0  0.0  0.0  10   10    0    22  IPE330           HEA400         MLE  M20           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -       IPE      330.0       160.0         7.5        11.5          HE        390.0         300.0          11.0          19.0         355.0         490.0            900.0           1000.0            500.0    0.055944    0.181818    0.258741    0.503497    0.769231    0.846154    1.000000         0.0         0.0          0.0          0.0          0.0          0.0
4709                       121.0          1243.29                          0             0.0                          0             0.0  135    0  300   985  25  356.0  45  50.0  120.0   75.0  225.0  120.0  130.0   75.0  150.0  0.0  0.0  0.0  0.0  0.0  10   20    0    30  HEA450           HEB500         MLE  M27           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -        HE      440.0       300.0        11.5        21.0          HE        500.0         300.0          14.5          28.0         355.0         490.0            900.0           1000.0            500.0    0.047872    0.175532    0.255319    0.494681    0.622340    0.760638    0.840426         1.0         0.0          0.0          0.0          0.0          0.0
4710                       121.0           166.04                          0             0.0                          0             0.0  100    0  220   500  25  154.0  40  40.0   85.0   95.0  135.0  105.0    0.0    0.0    0.0  0.0  0.0  0.0  0.0  0.0  12   10    0    22  HEA200  HI900060070*300         MLE  M20           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -        HE      190.0       200.0         6.5        10.0          HI       1040.0         300.0          60.0          70.0         355.0         490.0            900.0           1000.0            500.0    0.086957    0.271739    0.478261    0.771739    1.000000    0.000000    0.000000         0.0         0.0          0.0          0.0          0.0          0.0
4711                       121.0          1539.42                          0             0.0                          0             0.0  150    0  305  1025  20  364.0  50  55.0  135.0   85.0  205.0  135.0  110.0   85.0  170.0  0.0  0.0  0.0  0.0  0.0  15   25    0    33  HEB450           HEM500         MLE  M30           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -        HE      450.0       300.0        14.0        26.0          HE        524.0         306.0          21.0          40.0         355.0         490.0            900.0           1000.0            500.0    0.051282    0.189744    0.276923    0.487179    0.625641    0.738462    0.825641         1.0         0.0          0.0          0.0          0.0          0.0
4712                       121.0          1539.42                          0             0.0                          0             0.0  150    0  300  1025  20  364.0  50  55.0  135.0   85.0  205.0  135.0  110.0   85.0  170.0  0.0  0.0  0.0  0.0  0.0  15   25    0    33  HEB450           HEB500         MLE  M30           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -        HE      450.0       300.0        14.0        26.0          HE        500.0         300.0          14.5          28.0         355.0         490.0            900.0           1000.0            500.0    0.051282    0.189744    0.276923    0.487179    0.625641    0.738462    0.825641         1.0         0.0          0.0          0.0          0.0          0.0
4713                       121.0          1249.48                          0             0.0                          0             0.0  140    0  300   915  25  323.0  45  50.0  125.0   75.0  175.0  125.0   95.0   75.0  155.0  0.0  0.0  0.0  0.0  0.0  12   25    0    30  HEB400           HEB500         MLE  M27           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -        HE      400.0       300.0        13.5        24.0          HE        500.0         300.0          14.5          28.0         355.0         490.0            900.0           1000.0            500.0    0.051724    0.195402    0.281609    0.482759    0.626437    0.735632    0.821839         1.0         0.0          0.0          0.0          0.0          0.0
4714                       121.0           990.46                          0             0.0                          0             0.0  135    0  300   895  25  315.0  45  50.0  120.0   75.0  175.0  120.0   95.0   75.0  145.0  0.0  0.0  0.0  0.0  0.0  12   20    0    30  HEA400           HEB450         MLE  M27           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -        HE      390.0       300.0        11.0        19.0          HE        450.0         300.0          14.0          26.0         355.0         490.0            900.0           1000.0            500.0    0.052941    0.194118    0.282353    0.488235    0.629412    0.741176    0.829412         1.0         0.0          0.0          0.0          0.0          0.0
4715                       121.0           287.86                          0             0.0                          0             0.0  105    0  260   575  25  186.0  40  40.0   90.0   55.0   75.0  110.0   55.0  110.0    0.0  0.0  0.0  0.0  0.0  0.0  12   10    0    22  HEA240           HEA550         MLE  M20           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -        HE      230.0       240.0         7.5        12.0          HE        540.0         300.0          12.5          24.0         355.0         490.0            900.0           1000.0            500.0    0.074766    0.242991    0.345794    0.485981    0.691589    0.794393    1.000000         0.0         0.0          0.0          0.0          0.0          0.0
4716                       121.0           287.86                          0             0.0                          0             0.0  105    0  260   575  15  186.0  40  40.0   90.0   55.0   75.0  110.0   55.0  110.0    0.0  0.0  0.0  0.0  0.0  0.0  10   10    0    22  HEA240           HEM600         MLE  M20           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -        HE      230.0       240.0         7.5        12.0          HE        620.0         305.0          21.0          40.0         355.0         490.0            900.0           1000.0            500.0    0.074766    0.242991    0.345794    0.485981    0.691589    0.794393    1.000000         0.0         0.0          0.0          0.0          0.0          0.0
4717                       121.0           534.66                          0             0.0                          0             0.0  120    0  305   695  15  234.0  40  45.0  105.0   70.0  100.0  140.0   70.0  130.0    0.0  0.0  0.0  0.0  0.0  0.0  10   12    0    27  HEA300           HEM600         MLE  M24           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -        HE      290.0       300.0         8.5        14.0          HE        620.0         305.0          21.0          40.0         355.0         490.0            900.0           1000.0            500.0    0.061069    0.221374    0.328244    0.480916    0.694656    0.801527    1.000000         0.0         0.0          0.0          0.0          0.0          0.0
4718                       121.0          1037.23                          0             0.0                          0             0.0  140    0  305   849  15  291.0  45  55.0  125.0   75.0  140.0  190.0   75.0  150.0    0.0  0.0  0.0  0.0  0.0  0.0  10   25    0    30  HEB360           HEM600         MLE  M27           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -        HE      360.0       300.0        12.5        22.5          HE        620.0         305.0          21.0          40.0         355.0         490.0            900.0           1000.0            500.0    0.056250    0.212500    0.306250    0.481250    0.718750    0.812500    1.000000         0.0         0.0          0.0          0.0          0.0          0.0
4719                       121.0           505.28                          0             0.0                          0             0.0  110    0  200   880  20  323.0  40  40.0   90.0   55.0  240.0   90.0  160.0   55.0  110.0  0.0  0.0  0.0  0.0  0.0  10   12    0    22  IPE400           HEB240         MLE  M20           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -       IPE      400.0       180.0         8.6        13.5          HE        240.0         240.0          10.0          17.0         355.0         490.0            900.0           1000.0            500.0    0.047619    0.154762    0.220238    0.505952    0.613095    0.803571    0.869048         1.0         0.0          0.0          0.0          0.0          0.0
4720                       121.0           722.55                          0             0.0                          0             0.0  135    0  300   815  20  325.0  45  55.0  120.0  120.0  265.0   75.0  145.0    0.0    0.0  0.0  0.0  0.0  0.0  0.0  10   20    0    30  HEB300           HEA360         MLE  M27           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -        HE      300.0       300.0        11.0        19.0          HE        350.0         300.0          10.0          17.5         355.0         490.0            900.0           1000.0            500.0    0.058442    0.214286    0.370130    0.714286    0.811688    1.000000    0.000000         0.0         0.0          0.0          0.0          0.0          0.0
4721                       121.0           722.55                          0             0.0                          0             0.0  135    0  300   730  20  242.0  45  50.0  120.0  120.0  180.0   75.0  145.0    0.0    0.0  0.0  0.0  0.0  0.0  0.0  12   20    0    30  HEB300           HEA450         MLE  M27           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -        HE      300.0       300.0        11.0        19.0          HE        440.0         300.0          11.5          21.0         355.0         490.0            900.0           1000.0            500.0    0.065693    0.240876    0.416058    0.678832    0.788321    1.000000    0.000000         0.0         0.0          0.0          0.0          0.0          0.0

In [162]:
df = df_transformed

In [163]:
df.head()

   Capacity_Moment_Percentage  Capacity_Moment  Capacity_Shear_Percentage  Capacity_Shear  Capacity_Axial_Percentage  Capacity_Axial    g  tws   Bp   Lp  tp     Lh   e     d    p1     p2    p3        p4        p5   p6   p7   p8   p9  p10  p11  p12  ts  tbs  tst  Hole    BEAM  COLUMN DrawingCode Bolt SlipCritical      Normativas AceroEstructural EstandarTornillos    Source National_Annex            standard BEAM_type  BEAM_d_mm  BEAM_bf_mm  BEAM_tw_mm  BEAM_tf_mm COLUMN_type  COLUMN_d_mm  COLUMN_bf_mm  COLUMN_tw_mm  COLUMN_tf_mm  fy_acero_mpa  fu_acero_mpa  fy_tornillo_mpa  fu_tornillo_mpa  fv_tornillo_mpa  bolt_1_pct  bolt_2_pct  bolt_3_pct  bolt_4_pct  bolt_5_pct  bolt_6_pct  bolt_7_pct  bolt_8_pct  bolt_9_pct  bolt_10_pct  bolt_11_pct  bolt_12_pct  bolt_13_pct
0                       121.0           242.94                          0             0.0                          0             0.0  110    0  190  705  20  245.0  40  40.0  90.7  198.6  90.7  140.6447  104.3553  0.0  0.0  0.0  0.0  0.0  0.0  0.0  12   10    0    22  IPE300  HEA260         MOE  M20           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -       IPE      300.0       150.0         7.1        10.7          HE        250.0         260.0           7.5          12.5         355.0         490.0            900.0           1000.0            500.0    0.060150    0.196541    0.495188    0.631579    0.843075         1.0         0.0         0.0         0.0          0.0          0.0          0.0          0.0
1                       121.0           125.60                          0             0.0                          0             0.0  110    0  200  466  20  135.0  35  40.0  89.5   45.0  50.0   45.0000  155.0000  0.0  0.0  0.0  0.0  0.0  0.0  0.0  10   10    0    18  HEA180  HEA300         MOE  M16           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -        HE      171.0       180.0         6.0         9.5          HE        290.0         300.0           8.5          14.0         355.0         490.0            900.0           1000.0            500.0    0.083433    0.296782    0.404052    0.523242    0.630513         1.0         0.0         0.0         0.0          0.0          0.0          0.0          0.0
2                       121.0           242.94                          0             0.0                          0             0.0  110    0  190  705  20  245.0  40  40.0  90.7  198.6  90.7  140.6447  104.3553  0.0  0.0  0.0  0.0  0.0  0.0  0.0  12   10    0    22  IPE300  HEA320         MOE  M20           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -       IPE      300.0       150.0         7.1        10.7          HE        310.0         300.0           9.0          15.5         355.0         490.0            900.0           1000.0            500.0    0.060150    0.196541    0.495188    0.631579    0.843075         1.0         0.0         0.0         0.0          0.0          0.0          0.0          0.0
3                       121.0           166.04                          0             0.0                          0             0.0  110    0  220  565  20  215.0  35  40.0  90.0   90.0  90.0  111.4530  103.5470  0.0  0.0  0.0  0.0  0.0  0.0  0.0  10   10    0    18  HEA200  HEA280         MOE  M16           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -        HE      190.0       200.0         6.5        10.0          HE        270.0         280.0           8.0          13.0         355.0         490.0            900.0           1000.0            500.0    0.067308    0.240385    0.413462    0.586538    0.800871         1.0         0.0         0.0         0.0          0.0          0.0          0.0          0.0
4                       121.0           287.86                          0             0.0                          0             0.0  120    0  240  600  25  210.0  40  40.0  92.0  126.0  92.0  104.1436  105.8564  0.0  0.0  0.0  0.0  0.0  0.0  0.0  12   10    0    22  HEA240  HEA300         MOE  M20           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -        HE      230.0       240.0         7.5        12.0          HE        290.0         300.0           8.5          14.0         355.0         490.0            900.0           1000.0            500.0    0.071429    0.235714    0.460714    0.625000    0.810971         1.0         0.0         0.0         0.0          0.0          0.0          0.0          0.0

# ELIMINAMOS LP

In [164]:
df.drop(columns=["Lp"], inplace=True)

# DISTANCIAS A ALAS

In [165]:
# 2. Posiciones absolutas en mm
y_beam_top = df["e"] + df["d"] + (df["BEAM_tf_mm"] / 2.0)

y_beam_bottom = (
    df["e"] + df["d"] + df["BEAM_d_mm"] - (df["BEAM_tf_mm"] / 2.0)
)

y_haunch = np.where(
    df["Lh"] > 0,
    df["e"]
    + df["d"]
    + df["BEAM_d_mm"]
    + df["Lh"]
    - (df["BEAM_tf_mm"] / 2.0),
    0.0,
)

# 3. Normalizar en rango 0-1 dividiendo directamente entre la variable D_total
df["beam_top_flange_pos"] = y_beam_top / D_total
df["beam_bottom_flange_pos"] = y_beam_bottom / D_total
df["haunch_flange_pos"] = np.where(df["Lh"] > 0, y_haunch / D_total, 0.0)

In [166]:
df.head()

   Capacity_Moment_Percentage  Capacity_Moment  Capacity_Shear_Percentage  Capacity_Shear  Capacity_Axial_Percentage  Capacity_Axial    g  tws   Bp  tp     Lh   e     d    p1     p2    p3        p4        p5   p6   p7   p8   p9  p10  p11  p12  ts  tbs  tst  Hole    BEAM  COLUMN DrawingCode Bolt SlipCritical      Normativas AceroEstructural EstandarTornillos    Source National_Annex            standard BEAM_type  BEAM_d_mm  BEAM_bf_mm  BEAM_tw_mm  BEAM_tf_mm COLUMN_type  COLUMN_d_mm  COLUMN_bf_mm  COLUMN_tw_mm  COLUMN_tf_mm  fy_acero_mpa  fu_acero_mpa  fy_tornillo_mpa  fu_tornillo_mpa  fv_tornillo_mpa  bolt_1_pct  bolt_2_pct  bolt_3_pct  bolt_4_pct  bolt_5_pct  bolt_6_pct  bolt_7_pct  bolt_8_pct  bolt_9_pct  bolt_10_pct  bolt_11_pct  bolt_12_pct  bolt_13_pct  beam_top_flange_pos  beam_bottom_flange_pos  haunch_flange_pos
0                       121.0           242.94                          0             0.0                          0             0.0  110    0  190  20  245.0  40  40.0  90.7  198.6  90.7  140.6447  104.3553  0.0  0.0  0.0  0.0  0.0  0.0  0.0  12   10    0    22  IPE300  HEA260         MOE  M20           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -       IPE      300.0       150.0         7.1        10.7          HE        250.0         260.0           7.5          12.5         355.0         490.0            900.0           1000.0            500.0    0.060150    0.196541    0.495188    0.631579    0.843075         1.0         0.0         0.0         0.0          0.0          0.0          0.0          0.0             0.128346                0.563383           0.931805
1                       121.0           125.60                          0             0.0                          0             0.0  110    0  200  20  135.0  35  40.0  89.5   45.0  50.0   45.0000  155.0000  0.0  0.0  0.0  0.0  0.0  0.0  0.0  10   10    0    18  HEA180  HEA300         MOE  M16           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -        HE      171.0       180.0         6.0         9.5          HE        290.0         300.0           8.5          14.0         355.0         490.0            900.0           1000.0            500.0    0.083433    0.296782    0.404052    0.523242    0.630513         1.0         0.0         0.0         0.0          0.0          0.0          0.0          0.0             0.190107                0.575089           0.896901
2                       121.0           242.94                          0             0.0                          0             0.0  110    0  190  20  245.0  40  40.0  90.7  198.6  90.7  140.6447  104.3553  0.0  0.0  0.0  0.0  0.0  0.0  0.0  12   10    0    22  IPE300  HEA320         MOE  M20           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -       IPE      300.0       150.0         7.1        10.7          HE        310.0         300.0           9.0          15.5         355.0         490.0            900.0           1000.0            500.0    0.060150    0.196541    0.495188    0.631579    0.843075         1.0         0.0         0.0         0.0          0.0          0.0          0.0          0.0             0.128346                0.563383           0.931805
3                       121.0           166.04                          0             0.0                          0             0.0  110    0  220  20  215.0  35  40.0  90.0   90.0  90.0  111.4530  103.5470  0.0  0.0  0.0  0.0  0.0  0.0  0.0  10   10    0    18  HEA200  HEA280         MOE  M16           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -        HE      190.0       200.0         6.5        10.0          HE        270.0         280.0           8.0          13.0         355.0         490.0            900.0           1000.0            500.0    0.067308    0.240385    0.413462    0.586538    0.800871         1.0         0.0         0.0         0.0          0.0          0.0          0.0          0.0             0.153846                0.500000           0.913462
4                       121.0           287.86                          0             0.0                          0             0.0  120    0  240  25  210.0  40  40.0  92.0  126.0  92.0  104.1436  105.8564  0.0  0.0  0.0  0.0  0.0  0.0  0.0  12   10    0    22  HEA240  HEA300         MOE  M20           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -        HE      230.0       240.0         7.5        12.0          HE        290.0         300.0           8.5          14.0         355.0         490.0            900.0           1000.0            500.0    0.071429    0.235714    0.460714    0.625000    0.810971         1.0         0.0         0.0         0.0          0.0          0.0          0.0          0.0             0.153571                0.542857           0.917857

# CLASIFICACIÓN TORNILLOS

In [167]:
def clasificar_tornillos_dataset(row):
  # 1. Calcular las posiciones absolutas de los tornillos activos (en mm)
  e = row["e"]
  p_cols = [f"p{i}" for i in range(1, 13)]

  y_bolts = [e]
  curr_y = e
  for col in p_cols:
    p = row[col]
    if p > 0:
      curr_y += p
      y_bolts.append(curr_y)
    else:
      break

  n_bolts = len(y_bolts)
  # Inicializar lista de 13 etiquetas con 'NO_BOLT'
  labels = ["NO_BOLT"] * 13

  if n_bolts == 0:
    return labels

  # 2. Asignar extremos absolutos
  labels[0] = "GLOBAL_EXT_TOP"
  labels[n_bolts - 1] = "GLOBAL_EXT_BOT"

  # 3. Límites geométricos
  y_beam_top = row["e"] + row["d"] + (row["BEAM_tf_mm"] / 2.0)
  y_beam_bot = (
      row["e"] + row["d"] + row["BEAM_d_mm"] - (row["BEAM_tf_mm"] / 2.0)
  )

  Lh = row["Lh"]
  y_haunch_bot = y_beam_bot + Lh if Lh > 0 else y_beam_bot

  # 4. Asignar índices a cada zona
  indices_beam = []
  indices_haunch = []

  for idx in range(n_bolts):
    y = y_bolts[idx]
    if y_beam_top <= y <= y_beam_bot:
      indices_beam.append(idx)
    elif Lh > 0 and y_beam_bot < y <= y_haunch_bot:
      indices_haunch.append(idx)

  # 5. Función auxiliar para calcular el rol dentro de una zona
  def asignar_roles(indices, prefix):
    N = len(indices)
    for pos, idx in enumerate(indices):
      # Preservar el primer y último tornillo global
      if idx == 0 or idx == (n_bolts - 1):
        continue

      i = pos + 1  # Base 1
      if N == 1:
        role = "SINGLE"
      elif i == 1:
        role = "FIRST"
      elif i == N:
        role = "LAST"
      elif N % 2 != 0:  # Impar
        center = (N + 1) // 2
        if i == center:
          role = "CENTER"
        elif i < center:
          role = "INTERMEDIATE_TOP"
        else:
          role = "INTERMEDIATE_BOTTOM"
      else:  # Par
        center_top = N // 2
        center_bot = center_top + 1
        if i == center_top:
          role = "CENTER_TOP"
        elif i == center_bot:
          role = "CENTER_BOTTOM"
        elif i < center_top:
          role = "INTERMEDIATE_TOP"
        else:
          role = "INTERMEDIATE_BOTTOM"

      labels[idx] = f"{prefix}_{role}"

  asignar_roles(indices_beam, "BEAM")
  asignar_roles(indices_haunch, "HAUNCH")

  return labels

In [168]:
label_cols = [f"bolt_{i}_label" for i in range(1, 14)]

# Generar DataFrame con las nuevas etiquetas
df_labels = df.apply(
    clasificar_tornillos_dataset, axis=1, result_type="expand"
)
df_labels.columns = label_cols

# Concatenar al DataFrame original
df = pd.concat([df, df_labels], axis=1)

In [170]:
df.drop(columns=p_cols, inplace=True)

In [171]:
df.head()

   Capacity_Moment_Percentage  Capacity_Moment  Capacity_Shear_Percentage  Capacity_Shear  Capacity_Axial_Percentage  Capacity_Axial    g  tws   Bp  tp     Lh   e     d  ts  tbs  tst  Hole    BEAM  COLUMN DrawingCode Bolt SlipCritical      Normativas AceroEstructural EstandarTornillos    Source National_Annex            standard BEAM_type  BEAM_d_mm  BEAM_bf_mm  BEAM_tw_mm  BEAM_tf_mm COLUMN_type  COLUMN_d_mm  COLUMN_bf_mm  COLUMN_tw_mm  COLUMN_tf_mm  fy_acero_mpa  fu_acero_mpa  fy_tornillo_mpa  fu_tornillo_mpa  fv_tornillo_mpa  bolt_1_pct  bolt_2_pct  bolt_3_pct  bolt_4_pct  bolt_5_pct  bolt_6_pct  bolt_7_pct  bolt_8_pct  bolt_9_pct  bolt_10_pct  bolt_11_pct  bolt_12_pct  bolt_13_pct  beam_top_flange_pos  beam_bottom_flange_pos  haunch_flange_pos    bolt_1_label bolt_2_label bolt_3_label  bolt_4_label   bolt_5_label    bolt_6_label bolt_7_label bolt_8_label bolt_9_label bolt_10_label bolt_11_label bolt_12_label bolt_13_label
0                       121.0           242.94                          0             0.0                          0             0.0  110    0  190  20  245.0  40  40.0  12   10    0    22  IPE300  HEA260         MOE  M20           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -       IPE      300.0       150.0         7.1        10.7          HE        250.0         260.0           7.5          12.5         355.0         490.0            900.0           1000.0            500.0    0.060150    0.196541    0.495188    0.631579    0.843075         1.0         0.0         0.0         0.0          0.0          0.0          0.0          0.0             0.128346                0.563383           0.931805  GLOBAL_EXT_TOP   BEAM_FIRST    BEAM_LAST  HAUNCH_FIRST    HAUNCH_LAST  GLOBAL_EXT_BOT      NO_BOLT      NO_BOLT      NO_BOLT       NO_BOLT       NO_BOLT       NO_BOLT       NO_BOLT
1                       121.0           125.60                          0             0.0                          0             0.0  110    0  200  20  135.0  35  40.0  10   10    0    18  HEA180  HEA300         MOE  M16           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -        HE      171.0       180.0         6.0         9.5          HE        290.0         300.0           8.5          14.0         355.0         490.0            900.0           1000.0            500.0    0.083433    0.296782    0.404052    0.523242    0.630513         1.0         0.0         0.0         0.0          0.0          0.0          0.0          0.0             0.190107                0.575089           0.896901  GLOBAL_EXT_TOP   BEAM_FIRST  BEAM_CENTER     BEAM_LAST  HAUNCH_SINGLE  GLOBAL_EXT_BOT      NO_BOLT      NO_BOLT      NO_BOLT       NO_BOLT       NO_BOLT       NO_BOLT       NO_BOLT
2                       121.0           242.94                          0             0.0                          0             0.0  110    0  190  20  245.0  40  40.0  12   10    0    22  IPE300  HEA320         MOE  M20           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -       IPE      300.0       150.0         7.1        10.7          HE        310.0         300.0           9.0          15.5         355.0         490.0            900.0           1000.0            500.0    0.060150    0.196541    0.495188    0.631579    0.843075         1.0         0.0         0.0         0.0          0.0          0.0          0.0          0.0             0.128346                0.563383           0.931805  GLOBAL_EXT_TOP   BEAM_FIRST    BEAM_LAST  HAUNCH_FIRST    HAUNCH_LAST  GLOBAL_EXT_BOT      NO_BOLT      NO_BOLT      NO_BOLT       NO_BOLT       NO_BOLT       NO_BOLT       NO_BOLT
3                       121.0           166.04                          0             0.0                          0             0.0  110    0  220  20  215.0  35  40.0  10   10    0    18  HEA200  HEA280         MOE  M16           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -        HE      190.0       200.0         6.5        10.0          HE        270.0         280.0           8.0          13.0         355.0         490.0            900.0           1000.0            500.0    0.067308    0.240385    0.413462    0.586538    0.800871         1.0         0.0         0.0         0.0          0.0          0.0          0.0          0.0             0.153846                0.500000           0.913462  GLOBAL_EXT_TOP   BEAM_FIRST    BEAM_LAST  HAUNCH_FIRST    HAUNCH_LAST  GLOBAL_EXT_BOT      NO_BOLT      NO_BOLT      NO_BOLT       NO_BOLT       NO_BOLT       NO_BOLT       NO_BOLT
4                       121.0           287.86                          0             0.0                          0             0.0  120    0  240  25  210.0  40  40.0  12   10    0    22  HEA240  HEA300         MOE  M20           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -        HE      230.0       240.0         7.5        12.0          HE        290.0         300.0           8.5          14.0         355.0         490.0            900.0           1000.0            500.0    0.071429    0.235714    0.460714    0.625000    0.810971         1.0         0.0         0.0         0.0          0.0          0.0          0.0          0.0             0.153571                0.542857           0.917857  GLOBAL_EXT_TOP   BEAM_FIRST    BEAM_LAST  HAUNCH_FIRST    HAUNCH_LAST  GLOBAL_EXT_BOT      NO_BOLT      NO_BOLT      NO_BOLT       NO_BOLT       NO_BOLT       NO_BOLT       NO_BOLT

# RATIOS ESTRUCTURALES

In [172]:
def agregar_ratios_estructurales(df):
  # --- 1. Ratios Geométricos Directos ---
  df["r_d_beam_col"] = df["BEAM_d_mm"] / df["COLUMN_d_mm"]
  df["r_bf_beam_col"] = df["BEAM_bf_mm"] / df["COLUMN_bf_mm"]
  df["r_tw_beam_col"] = df["BEAM_tw_mm"] / df["COLUMN_tw_mm"]
  df["r_tf_beam_col"] = df["BEAM_tf_mm"] / df["COLUMN_tf_mm"]

  # Relación Chapa con Viga y Columna
  df["r_tp_tf_beam"] = df["tp"] / df["BEAM_tf_mm"]
  df["r_Bp_bf_col"] = df["Bp"] / df["COLUMN_bf_mm"]
  df["r_Bp_bf_beam"] = df["Bp"] / df["BEAM_bf_mm"]

  # --- 2. Funciones auxiliares para Inercia y Wpl ---
  def calc_section_props(d, bf, tw, tf):
    area = 2 * bf * tf + (d - 2 * tf) * tw
    iy = (tw * (d - 2 * tf) ** 3) / 12.0 + 2 * (
        (bf * (tf**3)) / 12.0 + bf * tf * (((d - tf) / 2.0) ** 2)
    )
    wpl = bf * tf * (d - tf) + (tw * ((d - 2 * tf) ** 2)) / 4.0
    return iy, wpl

  # Inercias y Wpl Viga
  I_beam, Wpl_beam = calc_section_props(
      df["BEAM_d_mm"], df["BEAM_bf_mm"], df["BEAM_tw_mm"], df["BEAM_tf_mm"]
  )

  # Inercias y Wpl Columna
  I_col, Wpl_col = calc_section_props(
      df["COLUMN_d_mm"],
      df["COLUMN_bf_mm"],
      df["COLUMN_tw_mm"],
      df["COLUMN_tf_mm"],
  )

  # Ratios Mecánicos
  df["r_Iy_beam_col"] = I_beam / I_col
  df["r_Wpl_beam_col"] = Wpl_beam / Wpl_col

  # --- 3. Esbelteces Locales ---
  df["slenderness_beam_web"] = (
      df["BEAM_d_mm"] - 2 * df["BEAM_tf_mm"]
  ) / df["BEAM_tw_mm"]
  df["slenderness_col_web"] = (
      df["COLUMN_d_mm"] - 2 * df["COLUMN_tf_mm"]
  ) / df["COLUMN_tw_mm"]
  df["slenderness_col_flange"] = (
      df["COLUMN_bf_mm"] - df["COLUMN_tw_mm"]
  ) / (2 * df["COLUMN_tf_mm"])

  return df


# Aplicar al dataframe
df = agregar_ratios_estructurales(df)

In [175]:
# Lista de columnas de BEAM y COLUMN a eliminar
cols_to_drop = [
    "BEAM",
    "COLUMN",
    "BEAM_type",
    "BEAM_d_mm",
    "BEAM_bf_mm",
    "BEAM_tw_mm",
    "BEAM_tf_mm",
    "COLUMN_type",
    "COLUMN_d_mm",
    "COLUMN_bf_mm",
    "COLUMN_tw_mm",
    "COLUMN_tf_mm",
]

# Eliminar columnas del DataFrame
df = df.drop(columns=cols_to_drop, errors="ignore")

In [176]:
df.head()

   Capacity_Moment_Percentage  Capacity_Moment  Capacity_Shear_Percentage  Capacity_Shear  Capacity_Axial_Percentage  Capacity_Axial    g  tws   Bp  tp     Lh   e     d  ts  tbs  tst  Hole DrawingCode Bolt SlipCritical      Normativas AceroEstructural EstandarTornillos    Source National_Annex            standard  fy_acero_mpa  fu_acero_mpa  fy_tornillo_mpa  fu_tornillo_mpa  fv_tornillo_mpa  bolt_1_pct  bolt_2_pct  bolt_3_pct  bolt_4_pct  bolt_5_pct  bolt_6_pct  bolt_7_pct  bolt_8_pct  bolt_9_pct  bolt_10_pct  bolt_11_pct  bolt_12_pct  bolt_13_pct  beam_top_flange_pos  beam_bottom_flange_pos  haunch_flange_pos    bolt_1_label bolt_2_label bolt_3_label  bolt_4_label   bolt_5_label    bolt_6_label bolt_7_label bolt_8_label bolt_9_label bolt_10_label bolt_11_label bolt_12_label bolt_13_label  r_d_beam_col  r_bf_beam_col  r_tw_beam_col  r_tf_beam_col  r_tp_tf_beam  r_Bp_bf_col  r_Bp_bf_beam  r_Iy_beam_col  r_Wpl_beam_col  slenderness_beam_web  slenderness_col_web  slenderness_col_flange
0                       121.0           242.94                          0             0.0                          0             0.0  110    0  190  20  245.0  40  40.0  12   10    0    22         MOE  M20           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -         355.0         490.0            900.0           1000.0            500.0    0.060150    0.196541    0.495188    0.631579    0.843075         1.0         0.0         0.0         0.0          0.0          0.0          0.0          0.0             0.128346                0.563383           0.931805  GLOBAL_EXT_TOP   BEAM_FIRST    BEAM_LAST  HAUNCH_FIRST    HAUNCH_LAST  GLOBAL_EXT_BOT      NO_BOLT      NO_BOLT      NO_BOLT       NO_BOLT       NO_BOLT       NO_BOLT       NO_BOLT      1.200000       0.576923       0.946667       0.856000      1.869159     0.730769      1.266667       0.809091        0.694625             39.239437            30.000000               10.100000
1                       121.0           125.60                          0             0.0                          0             0.0  110    0  200  20  135.0  35  40.0  10   10    0    18         MOE  M16           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -         355.0         490.0            900.0           1000.0            500.0    0.083433    0.296782    0.404052    0.523242    0.630513         1.0         0.0         0.0         0.0          0.0          0.0          0.0          0.0             0.190107                0.575089           0.896901  GLOBAL_EXT_TOP   BEAM_FIRST  BEAM_CENTER     BEAM_LAST  HAUNCH_SINGLE  GLOBAL_EXT_BOT      NO_BOLT      NO_BOLT      NO_BOLT       NO_BOLT       NO_BOLT       NO_BOLT       NO_BOLT      0.589655       0.600000       0.705882       0.678571      2.105263     0.666667      1.111111       0.139326        0.238165             25.333333            30.823529               10.410714
2                       121.0           242.94                          0             0.0                          0             0.0  110    0  190  20  245.0  40  40.0  12   10    0    22         MOE  M20           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -         355.0         490.0            900.0           1000.0            500.0    0.060150    0.196541    0.495188    0.631579    0.843075         1.0         0.0         0.0         0.0          0.0          0.0          0.0          0.0             0.128346                0.563383           0.931805  GLOBAL_EXT_TOP   BEAM_FIRST    BEAM_LAST  HAUNCH_FIRST    HAUNCH_LAST  GLOBAL_EXT_BOT      NO_BOLT      NO_BOLT      NO_BOLT       NO_BOLT       NO_BOLT       NO_BOLT       NO_BOLT      0.967742       0.500000       0.788889       0.690323      1.869159     0.633333      1.266667       0.366720        0.389817             39.239437            31.000000                9.387097
3                       121.0           166.04                          0             0.0                          0             0.0  110    0  220  20  215.0  35  40.0  10   10    0    18         MOE  M16           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -         355.0         490.0            900.0           1000.0            500.0    0.067308    0.240385    0.413462    0.586538    0.800871         1.0         0.0         0.0         0.0          0.0          0.0          0.0          0.0             0.153846                0.500000           0.913462  GLOBAL_EXT_TOP   BEAM_FIRST    BEAM_LAST  HAUNCH_FIRST    HAUNCH_LAST  GLOBAL_EXT_BOT      NO_BOLT      NO_BOLT      NO_BOLT       NO_BOLT       NO_BOLT       NO_BOLT       NO_BOLT      0.703704       0.714286       0.812500       0.769231      2.000000     0.785714      1.100000       0.269966        0.385910             26.153846            30.500000               10.461538
4                       121.0           287.86                          0             0.0                          0             0.0  120    0  240  25  210.0  40  40.0  12   10    0    22         MOE  M20           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -         355.0         490.0            900.0           1000.0            500.0    0.071429    0.235714    0.460714    0.625000    0.810971         1.0         0.0         0.0         0.0          0.0          0.0          0.0          0.0             0.153571                0.542857           0.917857  GLOBAL_EXT_TOP   BEAM_FIRST    BEAM_LAST  HAUNCH_FIRST    HAUNCH_LAST  GLOBAL_EXT_BOT      NO_BOLT      NO_BOLT      NO_BOLT       NO_BOLT       NO_BOLT       NO_BOLT       NO_BOLT      0.793103       0.800000       0.882353       0.857143      2.083333     0.800000      1.000000       0.427938        0.542046             27.466667            30.823529               10.410714

# FUERZAS

In [177]:
# 1. Convertir los porcentajes de carga a ratios decimales (0.0 a 1.0+)
df["ratio_moment"] = df["Capacity_Moment_Percentage"] / 100.0
df["ratio_shear"] = df["Capacity_Shear_Percentage"] / 100.0
df["ratio_axial"] = df["Capacity_Axial_Percentage"] / 100.0

# 2. Eliminar las columnas originales de carga (tanto absolutas como los porcentajes sin escalar)
load_cols_to_drop = [
    "Capacity_Moment",
    "Capacity_Moment_Percentage",
    "Capacity_Shear",
    "Capacity_Shear_Percentage",
    "Capacity_Axial",
    "Capacity_Axial_Percentage",
]

df = df.drop(columns=load_cols_to_drop, errors="ignore")

In [178]:
df.head()

     g  tws   Bp  tp     Lh   e     d  ts  tbs  tst  Hole DrawingCode Bolt SlipCritical      Normativas AceroEstructural EstandarTornillos    Source National_Annex            standard  fy_acero_mpa  fu_acero_mpa  fy_tornillo_mpa  fu_tornillo_mpa  fv_tornillo_mpa  bolt_1_pct  bolt_2_pct  bolt_3_pct  bolt_4_pct  bolt_5_pct  bolt_6_pct  bolt_7_pct  bolt_8_pct  bolt_9_pct  bolt_10_pct  bolt_11_pct  bolt_12_pct  bolt_13_pct  beam_top_flange_pos  beam_bottom_flange_pos  haunch_flange_pos    bolt_1_label bolt_2_label bolt_3_label  bolt_4_label   bolt_5_label    bolt_6_label bolt_7_label bolt_8_label bolt_9_label bolt_10_label bolt_11_label bolt_12_label bolt_13_label  r_d_beam_col  r_bf_beam_col  r_tw_beam_col  r_tf_beam_col  r_tp_tf_beam  r_Bp_bf_col  r_Bp_bf_beam  r_Iy_beam_col  r_Wpl_beam_col  slenderness_beam_web  slenderness_col_web  slenderness_col_flange  ratio_moment  ratio_shear  ratio_axial
0  110    0  190  20  245.0  40  40.0  12   10    0    22         MOE  M20           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -         355.0         490.0            900.0           1000.0            500.0    0.060150    0.196541    0.495188    0.631579    0.843075         1.0         0.0         0.0         0.0          0.0          0.0          0.0          0.0             0.128346                0.563383           0.931805  GLOBAL_EXT_TOP   BEAM_FIRST    BEAM_LAST  HAUNCH_FIRST    HAUNCH_LAST  GLOBAL_EXT_BOT      NO_BOLT      NO_BOLT      NO_BOLT       NO_BOLT       NO_BOLT       NO_BOLT       NO_BOLT      1.200000       0.576923       0.946667       0.856000      1.869159     0.730769      1.266667       0.809091        0.694625             39.239437            30.000000               10.100000          1.21          0.0          0.0
1  110    0  200  20  135.0  35  40.0  10   10    0    18         MOE  M16           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -         355.0         490.0            900.0           1000.0            500.0    0.083433    0.296782    0.404052    0.523242    0.630513         1.0         0.0         0.0         0.0          0.0          0.0          0.0          0.0             0.190107                0.575089           0.896901  GLOBAL_EXT_TOP   BEAM_FIRST  BEAM_CENTER     BEAM_LAST  HAUNCH_SINGLE  GLOBAL_EXT_BOT      NO_BOLT      NO_BOLT      NO_BOLT       NO_BOLT       NO_BOLT       NO_BOLT       NO_BOLT      0.589655       0.600000       0.705882       0.678571      2.105263     0.666667      1.111111       0.139326        0.238165             25.333333            30.823529               10.410714          1.21          0.0          0.0
2  110    0  190  20  245.0  40  40.0  12   10    0    22         MOE  M20           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -         355.0         490.0            900.0           1000.0            500.0    0.060150    0.196541    0.495188    0.631579    0.843075         1.0         0.0         0.0         0.0          0.0          0.0          0.0          0.0             0.128346                0.563383           0.931805  GLOBAL_EXT_TOP   BEAM_FIRST    BEAM_LAST  HAUNCH_FIRST    HAUNCH_LAST  GLOBAL_EXT_BOT      NO_BOLT      NO_BOLT      NO_BOLT       NO_BOLT       NO_BOLT       NO_BOLT       NO_BOLT      0.967742       0.500000       0.788889       0.690323      1.869159     0.633333      1.266667       0.366720        0.389817             39.239437            31.000000                9.387097          1.21          0.0          0.0
3  110    0  220  20  215.0  35  40.0  10   10    0    18         MOE  M16           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -         355.0         490.0            900.0           1000.0            500.0    0.067308    0.240385    0.413462    0.586538    0.800871         1.0         0.0         0.0         0.0          0.0          0.0          0.0          0.0             0.153846                0.500000           0.913462  GLOBAL_EXT_TOP   BEAM_FIRST    BEAM_LAST  HAUNCH_FIRST    HAUNCH_LAST  GLOBAL_EXT_BOT      NO_BOLT      NO_BOLT      NO_BOLT       NO_BOLT       NO_BOLT       NO_BOLT       NO_BOLT      0.703704       0.714286       0.812500       0.769231      2.000000     0.785714      1.100000       0.269966        0.385910             26.153846            30.500000               10.461538          1.21          0.0          0.0
4  120    0  240  25  210.0  40  40.0  12   10    0    22         MOE  M20           NO  AISC-360-05/10           S355JR              10.9  European              -  AISC-360-05/10 - -         355.0         490.0            900.0           1000.0            500.0    0.071429    0.235714    0.460714    0.625000    0.810971         1.0         0.0         0.0         0.0          0.0          0.0          0.0          0.0             0.153571                0.542857           0.917857  GLOBAL_EXT_TOP   BEAM_FIRST    BEAM_LAST  HAUNCH_FIRST    HAUNCH_LAST  GLOBAL_EXT_BOT      NO_BOLT      NO_BOLT      NO_BOLT       NO_BOLT       NO_BOLT       NO_BOLT       NO_BOLT      0.793103       0.800000       0.882353       0.857143      2.083333     0.800000      1.000000       0.427938        0.542046             27.466667            30.823529               10.410714          1.21          0.0          0.0

# GUARDAR

In [ ]:
df = pd.read_parquet("data" / "global_data.parquet")