In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

In [2]:
pd.set_option("display.max_columns", None)  # Show all columns
pd.set_option("display.width", 1000)

In [4]:
data = pd.read_parquet(Path().cwd().parent / "data" / "dataset_final.parquet")

In [5]:
data["clase_tornillo"].value_counts()

clase_tornillo
10.9     2037
A325M    1161
Name: count, dtype: int64

In [8]:
data["grado_acero"].value_counts()

grado_acero
S355JR    3198
Name: count, dtype: int64

In [79]:
data.tail()

      Capacity_Moment  Capacity_Shear  Capacity_Axial    g  tws   Bp  tp   e     d     p1     p2     p3     p4     p5  p6  p7  p8  p9  p10  p11  p12  ts  tbs  tst  Hole     BEAM    COLUMN DrawingCode  Bolt SlipCritical grado_acero clase_tornillo                                   standard BEAM_type  BEAM_d_mm COLUMN_type  COLUMN_d_mm  fy_acero_mpa  fu_acero_mpa  fy_tornillo_mpa  fu_tornillo_mpa  fv_tornillo_mpa  n_cantonera  n_alma  Unicode          Lh tornillo_1    tornillo_2     tornillo_3         tornillo_4          tornillo_5 tornillo_6 tornillo_7 tornillo_8 tornillo_9 tornillo_10 tornillo_11           p1_transition                p2_transition                     p3_transition                          p4_transition                 p5_transition p6_transition p7_transition p8_transition p9_transition p10_transition
3193          26.7300       60.710000          0.0000   95    0  140  15  35  33.0   90.0   90.0    0.0    0.0    0.0   0   0   0   0    0    0    0  10   10    0    18   HEA120    HEA600         MLE    16           NO      S355JR           10.9                             AISC-360-05/10        HE        114          HE          590           355           490              900             1000              500            0       1  MLE6123    0.000000   superior  viga central       inferior           no_usado            no_usado   no_usado   no_usado   no_usado   no_usado    no_usado    no_usado  superior__viga central       viga central__inferior                            UNUSED                                 UNUSED                        UNUSED        UNUSED        UNUSED        UNUSED        UNUSED         UNUSED
3194         393.9400      306.720000          0.0000  120    0  190  20  35  35.0   80.0  240.0   80.0    0.0    0.0   0   0   0   0    0    0    0  12   12    0    22   IPE360    HEB700         MLE    20           NO      S355JR           10.9                             AISC-360-05/10       IPE        360          HE          700           355           490              900             1000              500            0       2  MLE6414    0.000000   superior  viga primero  viga inferior           inferior            no_usado   no_usado   no_usado   no_usado   no_usado    no_usado    no_usado  superior__viga primero  viga primero__viga inferior           viga inferior__inferior                                 UNUSED                        UNUSED        UNUSED        UNUSED        UNUSED        UNUSED         UNUSED
3195         591.0750      333.877500        426.5325  140    0  300  25  45  55.0  130.0   75.0  275.0   75.0  160.0   0   0   0   0    0    0    0  10   10   10    30   HEA340    HEB600         MHE    27          YES      S355JR          A325M                             AISC-360-05/10        HE        330          HE          600           355           490              660              830              372            2       2  MHE0127  266.735824   superior  viga primero  viga inferior  cantonera primero  cantonera inferior   inferior   no_usado   no_usado   no_usado    no_usado    no_usado  superior__viga primero  viga primero__viga inferior  viga inferior__cantonera primero  cantonera primero__cantonera inferior  cantonera inferior__inferior        UNUSED        UNUSED        UNUSED        UNUSED         UNUSED
3196         296.3205      311.818815          0.0000  110    0  220  20  50  70.0  135.0  135.0  135.0   90.0  155.0   0   0   0   0    0    0    0   0   10    0    27  W310X60  W360X196         MHE    24           NO      S355JR          A325M                                 CSA S16-09         W        305           W          371           355           490              660              830              372            2       2  MHE4101  245.000000   superior  viga primero  viga inferior  cantonera primero  cantonera inferior   inferior   no_usado   no_usado   no_usado    no_usado    no_usado  superior__viga primero  viga primero__viga inferior  viga inferior__cantonera primero  cantonera primero__cantonera inferior  cantonera inferior__inferior        UNUSED        UNUSED        UNUSED        UNUSED         UNUSED
3197         656.7500        0.000000          0.0000  140    0  320  25  50  50.0  130.0  130.0  195.0  110.0  130.0   0   0   0   0    0    0    0  15   15    0    30   HEA340    HEB600         MHE    27           NO      S355JR           10.9  EN 1993-1-8 - SP RK EN 1993-1-8:2005/2011        HE        330          HE          600           355           490              900             1000              500            2       2  MHE2253  265.000000   superior  viga primero  viga inferior  cantonera primero  cantonera inferior   inferior   no_usado   no_usado   no_usado    no_usado    no_usado  superior__viga primero  viga primero__viga inferior  viga inferior__cantonera primero  cantonera primero__cantonera inferior  cantonera inferior__inferior        UNUSED        UNUSED        UNUSED        UNUSED         UNUSED

In [80]:
excel = pd.read_excel(
    Path().cwd().parent / "data" / "CONEXIONES_MOMENTO_ATORNILLADAS_CHAPA_FRONTAL.xlsx"
)
excel.head()

   Unicode    BEAM  COLUMN  Capacity_Moment_Percentage  Capacity_Moment  Capacity_Shear_Percentage  Capacity_Shear  Capacity_Axial_Percentage  Capacity_Axial  Pr_Porcen DrawingCode    g  tws  Lws  Bws   Bp   Lp  tp     Lh   e     d  pfo    p1     p2    p3        p4        p5  p6  p7  p8  p9  p10  p11  p12  ts  tbs  tst   thw   thf  w1  w2 w3 w4 w5 w6 Bolt  Hole SlipCritical      Normativas AceroEstructural ElectrodoSoldadura EstandarTornillos  Ordinary_Moment_Frames Calculation_Tool    Source Designation  rib_thk  Representation_Angle  BoltConnectionTypeSelection National_Annex   p0  tso  Lst  SpecialMomentFrames MzEd_PanelZone Vgra Havg  Yieldmethod Acero_Estructural_Perfil
0  JBE6000  IPE300  HEA260                       121.0           242.94                          0             0.0                          0             0.0         50         MOE  110    0    0    0  190  705  20  245.0  40  40.0  NaN  90.7  198.6  90.7  140.6447  104.3553   0   0   0   0    0    0    0  12   10    0  10.0  10.0   0   6  0  0  6  6  M20    22           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19        0                     0                            0              -  0.0  0.0  0.0                  0.0              -    -    -          1.0                   S355JR
1  JBE6001  HEA180  HEA300                       121.0           125.60                          0             0.0                          0             0.0         50         MOE  110    0    0    0  200  466  20  135.0  35  40.0  NaN  89.5   45.0  50.0   45.0000  155.0000   0   0   0   0    0    0    0  10   10    0  10.0  10.0   0   5  0  0  6  6  M16    18           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19        0                     0                            0              -  0.0  0.0  0.0                  0.0            NaN  NaN  NaN          NaN                      NaN
2  JBE6002  IPE300  HEA320                       121.0           242.94                          0             0.0                          0             0.0         50         MOE  110    0    0    0  190  705  20  245.0  40  40.0  NaN  90.7  198.6  90.7  140.6447  104.3553   0   0   0   0    0    0    0  12   10    0  10.0  10.0   0   6  0  0  6  6  M20    22           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19        0                     0                            0              -  0.0  0.0  0.0                  0.0            NaN  NaN  NaN          NaN                      NaN
3  JBE6003  HEA200  HEA280                       121.0           166.04                          0             0.0                          0             0.0         50         MOE  110    0    0    0  220  565  20  215.0  35  40.0  NaN  90.0   90.0  90.0  111.4530  103.5470   0   0   0   0    0    0    0  10   10    0  10.0  10.0   0   5  0  0  6  6  M16    18           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19        0                     0                            0              -  0.0  0.0  0.0                  0.0            NaN  NaN  NaN          NaN                      NaN
4  JBE6004  HEA240  HEA300                       121.0           287.86                          0             0.0                          0             0.0         50         MOE  120    0    0    0  240  600  25  210.0  40  40.0  NaN  92.0  126.0  92.0  104.1436  105.8564   0   0   0   0    0    0    0  12   10    0  10.0  10.0   0   6  0  0  7  7  M20    22           NO  AISC-360-05/10           S355JR               E480              10.9                    True   Hojas de Excel  European     Tekla19        0                     0                            0              -  0.0  0.0  0.0                  0.0            NaN  NaN  NaN          NaN                      NaN

In [81]:
excel.columns

Index(['Unicode', 'BEAM', 'COLUMN', 'Capacity_Moment_Percentage', 'Capacity_Moment', 'Capacity_Shear_Percentage', 'Capacity_Shear', 'Capacity_Axial_Percentage', 'Capacity_Axial', 'Pr_Porcen', 'DrawingCode', 'g', 'tws', 'Lws', 'Bws', 'Bp', 'Lp', 'tp', 'Lh', 'e', 'd', 'pfo', 'p1', 'p2', 'p3', 'p4', 'p5', 'p6', 'p7', 'p8', 'p9', 'p10', 'p11', 'p12', 'ts', 'tbs', 'tst', 'thw', 'thf', 'w1', 'w2', 'w3', 'w4', 'w5', 'w6', 'Bolt', 'Hole', 'SlipCritical', 'Normativas', 'AceroEstructural', 'ElectrodoSoldadura', 'EstandarTornillos', 'Ordinary_Moment_Frames', 'Calculation_Tool', 'Source', 'Designation', 'rib_thk', 'Representation_Angle', 'BoltConnectionTypeSelection', 'National_Annex', 'p0', 'tso', 'Lst', 'SpecialMomentFrames', 'MzEd_PanelZone', 'Vgra', 'Havg', 'Yieldmethod', 'Acero_Estructural_Perfil'], dtype='str')

In [82]:
cols_interes = [
    "Unicode",
    "Capacity_Moment_Percentage",
    "Capacity_Shear_Percentage",
    "Capacity_Axial_Percentage",
]
df_excel_sub = excel[cols_interes]

# 3. Cruzar ambas tablas mediante la columna 'Unicode'
df = pd.merge(
    data, df_excel_sub, on="Unicode", how="left"
)

In [83]:
df.head()

,Capacity_Moment,Capacity_Shear,Capacity_Axial,g,tws,Bp,tp,e,d,p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,ts,tbs,tst,Hole,BEAM,COLUMN,DrawingCode,Bolt,SlipCritical,grado_acero,clase_tornillo,standard,BEAM_type,BEAM_d_mm,COLUMN_type,COLUMN_d_mm,fy_acero_mpa,fu_acero_mpa,fy_tornillo_mpa,fu_tornillo_mpa,fv_tornillo_mpa,n_cantonera,n_alma,Unicode,Lh,tornillo_1,tornillo_2,tornillo_3,tornillo_4,tornillo_5,tornillo_6,tornillo_7,tornillo_8,tornillo_9,tornillo_10,tornillo_11,p1_transition,p2_transition,p3_transition,p4_transition,p5_transition,p6_transition,p7_transition,p8_transition,p9_transition,p10_transition,Capacity_Moment_Percentage,Capacity_Shear_Percentage,Capacity_Axial_Percentage
0,298.57275,0.0000,0.0000,140,0,320,30,50,60.0,145.0,130.0,145.0,0.0,0.0,0,0,0,0,0,0,0,20,0,0,33,HEB300,HEB700,MLE,30,NO,S355JR,10.9,EN 1993-1-8 - SP RK EN 1993-1-8:2005/2011,HE,300,HE,700,355,490,900,1000,500,0,2,MLE2364,0.00000,superior,viga primero,viga inferior,inferior,no_usado,no_usado,no_usado,no_usado,no_usado,no_usado,no_usado,superior__viga primero,viga primero__viga inferior,viga inferior__inferior,UNUSED,UNUSED,UNUSED,UNUSED,UNUSED,UNUSED,UNUSED,45.0,0,0
1,1348.03440,1065.5325,832.2975,155,0,300,30,50,65.0,155.0,85.0,140.0,140.0,140.0,160,135,135,85,200,0,0,15,15,15,33,HEA700,HEB700,MHE,30,YES,S355JR,A325M,AISC-360-05/10,HE,690,HE,700,355,490,660,830,372,4,5,MHE0176,557.72036,superior,viga primero,viga central,viga central,viga central,viga inferior,cantonera primero,cantonera central,cantonera central,cantonera inferior,inferior,superior__viga primero,viga primero__viga central,viga central__viga central,viga central__viga central,viga central__viga inferior,viga inferior__cantonera primero,cantonera primero__cantonera central,cantonera central__cantonera central,cantonera central__cantonera inferior,cantonera inferior__inferior,60.0,50,10
2,219.78000,0.0000,0.0000,105,0,240,25,40,40.0,90.0,110.0,150.0,110.0,0.0,0,0,0,0,0,0,0,12,10,0,22,HEA220,HEB500,MLE,20,NO,S355JR,10.9,AISC-360-05/10,HE,210,HE,500,355,490,900,1000,500,1,2,MOE6213,170.00000,superior,viga primero,viga inferior,cantonera central,inferior,no_usado,no_usado,no_usado,no_usado,no_usado,no_usado,superior__viga primero,viga primero__viga inferior,viga inferior__cantonera central,cantonera central__inferior,UNUSED,UNUSED,UNUSED,UNUSED,UNUSED,UNUSED,121.0,0,0
3,591.07500,0.0000,0.0000,140,0,320,25,50,50.0,130.0,130.0,195.0,110.0,130.0,0,0,0,0,0,0,0,15,15,0,30,HEA340,HEB340,MHE,27,NO,S355JR,10.9,EN 1993-1-8 - SP RK EN 1993-1-8:2005/2011,HE,330,HE,340,355,490,900,1000,500,2,2,MHE2248,265.00000,superior,viga primero,viga inferior,cantonera primero,cantonera inferior,inferior,no_usado,no_usado,no_usado,no_usado,no_usado,superior__viga primero,viga primero__viga inferior,viga inferior__cantonera primero,cantonera primero__cantonera inferior,cantonera inferior__inferior,UNUSED,UNUSED,UNUSED,UNUSED,UNUSED,90.0,0,0
4,54.82000,97.1300,0.0000,90,0,220,15,40,39.0,85.0,60.0,85.0,0.0,0.0,0,0,0,0,0,0,0,10,10,0,22,HEA160,HEA320,MLE,20,NO,S355JR,10.9,AISC-360-05/10,HE,152,HE,310,355,490,900,1000,500,0,2,MLE6001,0.00000,superior,viga primero,viga inferior,inferior,no_usado,no_usado,no_usado,no_usado,no_usado,no_usado,no_usado,superior__viga primero,viga primero__viga inferior,viga inferior__inferior,UNUSED,UNUSED,UNUSED,UNUSED,UNUSED,UNUSED,UNUSED,70.0,50,0

In [84]:
df["ratio_moment"] = df["Capacity_Moment_Percentage"] / 100
df["ratio_shear"] = df["Capacity_Shear_Percentage"] / 100
df["ratio_axial"] = df["Capacity_Axial_Percentage"] / 100

In [85]:
df.drop(columns=["Capacity_Moment", "Capacity_Shear", "Capacity_Axial", "Capacity_Moment_Percentage", "Capacity_Shear_Percentage", "Capacity_Axial_Percentage"], inplace=True)

In [86]:
df.head()

     g  tws   Bp  tp   e     d     p1     p2     p3     p4     p5   p6   p7   p8  p9  p10  p11  p12  ts  tbs  tst  Hole    BEAM  COLUMN DrawingCode  Bolt SlipCritical grado_acero clase_tornillo                                   standard BEAM_type  BEAM_d_mm COLUMN_type  COLUMN_d_mm  fy_acero_mpa  fu_acero_mpa  fy_tornillo_mpa  fu_tornillo_mpa  fv_tornillo_mpa  n_cantonera  n_alma  Unicode         Lh tornillo_1    tornillo_2     tornillo_3         tornillo_4          tornillo_5     tornillo_6         tornillo_7         tornillo_8         tornillo_9         tornillo_10 tornillo_11           p1_transition                p2_transition                     p3_transition                          p4_transition                 p5_transition                     p6_transition                         p7_transition                         p8_transition                          p9_transition                p10_transition  ratio_moment  ratio_shear  ratio_axial
0  140    0  320  30  50  60.0  145.0  130.0  145.0    0.0    0.0    0    0    0   0    0    0    0  20    0    0    33  HEB300  HEB700         MLE    30           NO      S355JR           10.9  EN 1993-1-8 - SP RK EN 1993-1-8:2005/2011        HE        300          HE          700           355           490              900             1000              500            0       2  MLE2364    0.00000   superior  viga primero  viga inferior           inferior            no_usado       no_usado           no_usado           no_usado           no_usado            no_usado    no_usado  superior__viga primero  viga primero__viga inferior           viga inferior__inferior                                 UNUSED                        UNUSED                            UNUSED                                UNUSED                                UNUSED                                 UNUSED                        UNUSED          0.45          0.0          0.0
1  155    0  300  30  50  65.0  155.0   85.0  140.0  140.0  140.0  160  135  135  85  200    0    0  15   15   15    33  HEA700  HEB700         MHE    30          YES      S355JR          A325M                             AISC-360-05/10        HE        690          HE          700           355           490              660              830              372            4       5  MHE0176  557.72036   superior  viga primero   viga central       viga central        viga central  viga inferior  cantonera primero  cantonera central  cantonera central  cantonera inferior    inferior  superior__viga primero   viga primero__viga central        viga central__viga central             viga central__viga central   viga central__viga inferior  viga inferior__cantonera primero  cantonera primero__cantonera central  cantonera central__cantonera central  cantonera central__cantonera inferior  cantonera inferior__inferior          0.60          0.5          0.1
2  105    0  240  25  40  40.0   90.0  110.0  150.0  110.0    0.0    0    0    0   0    0    0    0  12   10    0    22  HEA220  HEB500         MLE    20           NO      S355JR           10.9                             AISC-360-05/10        HE        210          HE          500           355           490              900             1000              500            1       2  MOE6213  170.00000   superior  viga primero  viga inferior  cantonera central            inferior       no_usado           no_usado           no_usado           no_usado            no_usado    no_usado  superior__viga primero  viga primero__viga inferior  viga inferior__cantonera central            cantonera central__inferior                        UNUSED                            UNUSED                                UNUSED                                UNUSED                                 UNUSED                        UNUSED          1.21          0.0          0.0
3  140    0  320  25  50  50.0  130.0  130.0  195.0  110.0  130.0    0    0    0   0    0    0    0  15   15    0    30  HEA340  HEB340         MHE    27           NO      S355JR           10.9  EN 1993-1-8 - SP RK EN 1993-1-8:2005/2011        HE        330          HE          340           355           490              900             1000              500            2       2  MHE2248  265.00000   superior  viga primero  viga inferior  cantonera primero  cantonera inferior       inferior           no_usado           no_usado           no_usado            no_usado    no_usado  superior__viga primero  viga primero__viga inferior  viga inferior__cantonera primero  cantonera primero__cantonera inferior  cantonera inferior__inferior                            UNUSED                                UNUSED                                UNUSED                                 UNUSED                        UNUSED          0.90          0.0          0.0
4   90    0  220  15  40  39.0   85.0   60.0   85.0    0.0    0.0    0    0    0   0    0    0    0  10   10    0    22  HEA160  HEA320         MLE    20           NO      S355JR           10.9                             AISC-360-05/10        HE        152          HE          310           355           490              900             1000              500            0       2  MLE6001    0.00000   superior  viga primero  viga inferior           inferior            no_usado       no_usado           no_usado           no_usado           no_usado            no_usado    no_usado  superior__viga primero  viga primero__viga inferior           viga inferior__inferior                                 UNUSED                        UNUSED                            UNUSED                                UNUSED                                UNUSED                                 UNUSED                        UNUSED          0.70          0.5          0.0

In [89]:
df.tail()

        g  tws   Bp  tp   e     d     p1     p2     p3     p4     p5  p6  p7  p8  p9  p10  p11  p12  ts  tbs  tst  Hole     BEAM    COLUMN DrawingCode  Bolt SlipCritical grado_acero clase_tornillo                                   standard BEAM_type  BEAM_d_mm COLUMN_type  COLUMN_d_mm  fy_acero_mpa  fu_acero_mpa  fy_tornillo_mpa  fu_tornillo_mpa  fv_tornillo_mpa  n_cantonera  n_alma  Unicode          Lh tornillo_1    tornillo_2     tornillo_3         tornillo_4          tornillo_5 tornillo_6 tornillo_7 tornillo_8 tornillo_9 tornillo_10 tornillo_11           p1_transition                p2_transition                     p3_transition                          p4_transition                 p5_transition p6_transition p7_transition p8_transition p9_transition p10_transition  ratio_moment  ratio_shear  ratio_axial
3193   95    0  140  15  35  33.0   90.0   90.0    0.0    0.0    0.0   0   0   0   0    0    0    0  10   10    0    18   HEA120    HEA600         MLE    16           NO      S355JR           10.9                             AISC-360-05/10        HE        114          HE          590           355           490              900             1000              500            0       1  MLE6123    0.000000   superior  viga central       inferior           no_usado            no_usado   no_usado   no_usado   no_usado   no_usado    no_usado    no_usado  superior__viga central       viga central__inferior                            UNUSED                                 UNUSED                        UNUSED        UNUSED        UNUSED        UNUSED        UNUSED         UNUSED           0.7         0.50          0.0
3194  120    0  190  20  35  35.0   80.0  240.0   80.0    0.0    0.0   0   0   0   0    0    0    0  12   12    0    22   IPE360    HEB700         MLE    20           NO      S355JR           10.9                             AISC-360-05/10       IPE        360          HE          700           355           490              900             1000              500            0       2  MLE6414    0.000000   superior  viga primero  viga inferior           inferior            no_usado   no_usado   no_usado   no_usado   no_usado    no_usado    no_usado  superior__viga primero  viga primero__viga inferior           viga inferior__inferior                                 UNUSED                        UNUSED        UNUSED        UNUSED        UNUSED        UNUSED         UNUSED           0.7         0.50          0.0
3195  140    0  300  25  45  55.0  130.0   75.0  275.0   75.0  160.0   0   0   0   0    0    0    0  10   10   10    30   HEA340    HEB600         MHE    27          YES      S355JR          A325M                             AISC-360-05/10        HE        330          HE          600           355           490              660              830              372            2       2  MHE0127  266.735824   superior  viga primero  viga inferior  cantonera primero  cantonera inferior   inferior   no_usado   no_usado   no_usado    no_usado    no_usado  superior__viga primero  viga primero__viga inferior  viga inferior__cantonera primero  cantonera primero__cantonera inferior  cantonera inferior__inferior        UNUSED        UNUSED        UNUSED        UNUSED         UNUSED           1.0         0.50          0.1
3196  110    0  220  20  50  70.0  135.0  135.0  135.0   90.0  155.0   0   0   0   0    0    0    0   0   10    0    27  W310X60  W360X196         MHE    24           NO      S355JR          A325M                                 CSA S16-09         W        305           W          371           355           490              660              830              372            2       2  MHE4101  245.000000   superior  viga primero  viga inferior  cantonera primero  cantonera inferior   inferior   no_usado   no_usado   no_usado    no_usado    no_usado  superior__viga primero  viga primero__viga inferior  viga inferior__cantonera primero  cantonera primero__cantonera inferior  cantonera inferior__inferior        UNUSED        UNUSED        UNUSED        UNUSED         UNUSED           1.0         0.66          0.0
3197  140    0  320  25  50  50.0  130.0  130.0  195.0  110.0  130.0   0   0   0   0    0    0    0  15   15    0    30   HEA340    HEB600         MHE    27           NO      S355JR           10.9  EN 1993-1-8 - SP RK EN 1993-1-8:2005/2011        HE        330          HE          600           355           490              900             1000              500            2       2  MHE2253  265.000000   superior  viga primero  viga inferior  cantonera primero  cantonera inferior   inferior   no_usado   no_usado   no_usado    no_usado    no_usado  superior__viga primero  viga primero__viga inferior  viga inferior__cantonera primero  cantonera primero__cantonera inferior  cantonera inferior__inferior        UNUSED        UNUSED        UNUSED        UNUSED         UNUSED           1.0         0.00          0.0

In [88]:
df.to_parquet(Path().cwd().parent / "data" / "dataset_final.parquet")